{easy
	{balancingFactorBonus {cp 300.0} {mp 0.75} {payback 0.75} }
	{chargeFactors
		{value "*=0"}
	}
}
{normal
	{balancingFactorBonus {cp 350.0} {mp 1.0} {payback 1.0} }
	{chargeFactors
		{value "*=0"}
	}
}
{hard
	{balancingFactorBonus {cp 400.0} {mp 1.25} {payback 1.0} }
	{chargeFactors
		{value "*=0"}
	}
}
{heroic
	{balancingFactorBonus {cp 450.0} {mp 1.5} {payback 1.00} }
	{chargeFactors
		{value "*=0"}
	}
}