;Создано maaa - DTTGOC
;LocalGen2
;Проверено Bizon и zkv2000
;Перепроверено и переделано за Bizon и zkv2000
;rev 04.07.2022

{"mi17_unarmed_supl"						"<c(FFFFFF)e(shadow)>МИ-17 снабжения</c>"}
{"kornet_base_stan_isis"						"<c(FFFFFF)e(shadow)>9П163М-1 Корнет-П</c>"}
{"ptur_tow_isis"						"<c(FFFFFF)e(shadow)>BMG-71 TOW</c>"}
{"2b11_isis" "<c(FFFFFF)><e(shadow)>2С12 Сани</c>"}
{"brem-1" "<c(FFFFFF)><e(shadow)>БРЭМ-1</c>"}
{"hmmwv_isis" "<c(FFFFFF)><e(shadow)>HMMWV с ДШК</c>"}
{"kamaz_zu" "<c(FFFFFF)><e(shadow)>КАМАЗ ЗСУ-23-2</c>"}
{"zil131_2s1"	"<c(FFFFFF)e(shadow)>2С1 Гвоздика на базе ЗИЛ</c>"}
{"leopard_2a4_dz"	"<c(FFFFFF)e(shadow)>Леопрад 2А4 с ДЗ К1</c>"}
{"m1a1_lodka"	"<c(FFFFFF)e(shadow)>ГКР-1</c>"}
{"brdm2kz"	"<c(FFFFFF)e(shadow)>БРДМ-2</c>"}
{"uaz69s"	"<c(FFFFFF)e(shadow)>УАЗ-69М</c>"}

{"toyota_hilux_grad_p"	"<c(FFFFFF)e(shadow)>Toyota Hilux с Град-п</c>"}
{"toyota_hilux_nurs"	"<c(FFFFFF)e(shadow)>Toyota Hilux с УБ-32</c>"}
{"uazpzrk"	"<c(FFFFFF)e(shadow)>УАЗ с РПО Шмель</c>"}
{"uazm2"	"<c(FFFFFF)e(shadow)>УАЗ с М2 Browning</c>"}

{"mstasm2_odkb"	"<c(FFFFFF)e(shadow)>2С19 Мста-С</c>"}
{"kamaz_grad"	"<c(FFFFFF)e(shadow)>БМ–21А БелГрад</c>"}

{"mtlb_supl"	"<c(FFFFFF)e(shadow)>МТ-ЛБ с тяжёлыми боеприпасами</c>"}
{"9k35_strela_nurs"	"<c(FFFFFF)e(shadow)>МТ-ЛБ с УБ-32</c>"}
{"mig-21bis_pizdec"	"<c(FFFFFF)e(shadow)>СУ-7БМВЭК Ударный</c>"}
{"t80ybars"	"<c(FFFFFF)e(shadow)>Т-80 Барс</c>"}
{"t62_isis"	"<c(FFFFFF)e(shadow)>Т-62 Образца 1972 года</c>"}
{"su24m_kab"						"<c(FFFFFF)e(shadow)>СУ-24 КАБ</c>"}
{"su24m"							"<c(FFFFFF)e(shadow)>Су 24 противорадиолокационный</c>"}
{"su24m_strike"							"<c(FFFFFF)e(shadow)>Су-24 Ударный</c>"}
{"t-55_c60"									"<c(FFFFFF)e(shadow)>T-55А с башней С60</c>"}
{"hmmwv_knkrs"					"<c(FFFFFF)e(shadow)>HMMWV с ПТРК Конкурс</c>"}
{"tochka_y"					"<c(FFFFFF)e(shadow)>Точка-у</c>"}
{"mtlb_zu"					"<c(FFFFFF)e(shadow)>МТЛБ с ЗУ-23-2</c>"}
{"grad_p"					"<c(FFFFFF)e(shadow)>9П132 Град-П («Партизан»)</c>"}
{"m777"					"<c(FFFFFF)e(shadow)>155-мм гаубица M777</c>"}
{"btr-4e"						"<c(FFFFFF)e(shadow)>БТР-4 Буцефал</c>"}
{"btr-3e_no_pt"						"<c(FFFFFF)e(shadow)>БТР-3</c>"}
{"tos-1a_solntsepek_odkb"					"<c(FFFFFF)e(shadow)>ТОС-1А Солнцепек</c>"}
{"t72b3_blr"						"<c(FFFFFF)e(shadow)>T-72Б3 обр.2011</c>"}
{"mt12_with_mtlb"						"<c(FFFFFF)e(shadow)>МТЛБ с МТ-12 Рапира</c>"}
{"2c4_tulpan"						"<c(FFFFFF)e(shadow)>2с4 Тюльпан</c>"}
{"maz-537"						"<c(FFFFFF)e(shadow)>МАЗ-537</c>"}
{"gaz_tigr_dz"							"<c(FFFFFF)e(shadow)>ГАЗ-233014 Тигр</c>"}
{"mtlb_c60"								"<c(FFFFFF)e(shadow)>МТ-ЛБ с С-60</c>"}
{"mtlb_vmk_ogon"						"<c(FFFFFF)e(shadow)>МТ-ЛБ с РСЗО А-22 Огонь</c>"}
{"mtlb_c5_vasilek"						"<c(FFFFFF)e(shadow)>МТ-ЛБ с блоком С-5 и минометом Василек</c>"}

{"yaz_patrior"						"<c(FFFFFF)e(shadow)>УАЗ Патриот поддержки</c>"}
{"ural-4320_long_tent_h"						"<c(FFFFFF)e(shadow)>Урал снабжения</c>"}
{"ural-4320_long_zu23-2_h"						"<c(FFFFFF)e(shadow)>Урал 4320 с ЗУ-23-2 и доп.броней</c>"}
{"yaz_patrior_rapira"						"<c(FFFFFF)e(shadow)>УАЗ Патриот с МТ-12 Рапира</c>"}
{"yaz_patrior_kornet"						"<c(FFFFFF)e(shadow)>УАЗ Патриот с ПТРК Корнет</c>"}
{"yaz_patrior_zu23_2"						"<c(FFFFFF)e(shadow)>УАЗ Патриот с ЗУ-23-2</c>"}
{"2121_atgm"						"<c(FFFFFF)e(shadow)>Нива с ПТРК Корнет</c>"}
{"t-55_ser"						"<c(FFFFFF)e(shadow)>Т-55А</c>"}
{"t62m_v2_ser"						"<c(FFFFFF)e(shadow)>Т-62М</c>"}






