		{"special"
			{"ger"
				{"spy1" "Петер Герман"}
				{"spy2" "Торстен Шафер"}
			}
			{"hint" "Подсказка"}
		}
		{"mp"

		}
               
		{"mp2"
			{"srbsk"
				{"1st_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"1st_mg" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"army_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"1st_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"1st_rpg2" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"1st_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"1st_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"1st_smg3" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"1st_smg4" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"1st_snuper" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				
				{"civilian_guard_1" "<c(FFFFFF)>Солдат гражданского ополчения<c(FFFFFF)>"}
				{"civilian_guard_2" "<c(FFFFFF)>Солдат гражданского ополчения<c(FFFFFF)>"}
				{"civilian_guard_3" "<c(FFFFFF)>Солдат гражданского ополчения<c(FFFFFF)>"}
				{"civilian_guard_4" "<c(FFFFFF)>Солдат гражданского ополчения<c(FFFFFF)>"}
				{"civilian_guard_5" "<c(FFFFFF)>Солдат гражданского ополчения<c(FFFFFF)>"}
				{"civilian_guard_com" "<c(FFFFFF)>Командир гражданского ополчения<c(FFFFFF)>"}
				
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор. и техн.<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}
				
				{"pmc_com" "<c(FFFFFF)>Командир отряда ЧВК<c(FFFFFF)>"}
				{"pmc_mgun" "<c(FFFFFF)>Пулемётчик ЧВК<c(FFFFFF)>"}
				{"pmc_rpg" "<c(FFFFFF)>Гранатаметчик ЧВК<c(FFFFFF)>"}
				{"pmc_zek" "<c(FFFFFF)>Солдат-зек ЧВК<c(FFFFFF)>"}
				{"pmc_zek2" "<c(FFFFFF)>Солдат-зек ЧВК<c(FFFFFF)>"}
				{"pmc_zek3" "<c(FFFFFF)>Солдат-зек ЧВК<c(FFFFFF)>"}
			}
			{"iregular"
			 	{"army_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"army_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"army_mgunhelp" "<c(FFFFFF)>Помощник пулеметчика<c(FFFFFF)>"}
				{"army_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"army_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"army_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"army_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"army_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Сапёр<c(FFFFFF)>"}
				{"bazooker2" "<c(FFFFFF)>Тяжёлый гранатометчик<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор. и техн.<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}
			}
		
			{"rus"
				
				
				
				
				
				
				{"antipersonel_miner" "<c(FFFFFF)>ПП минер<c(FFFFFF)>"}
				{"antitank_miner" "<c(FFFFFF)>ПТ минер<c(FFFFFF)>"}
				{"bazooker" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"bazooker2" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"bazooker2_help" "<c(FFFFFF)>Помощник гранатометчика<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>инженер<c(FFFFFF)>"}
				{"engineer2" "<c(FFFFFF)>инженер<c(FFFFFF)>"}
				{"flamer" "<c(FFFFFF)>огнеметчик<c(FFFFFF)>"}
				{"flamer2" "<c(FFFFFF)>огнеметчик<c(FFFFFF)>"}
				{"mgun" "<c(FFFFFF)>пулеметчик<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>офицер<c(FFFFFF)>"}
				{"nav" "<c(FFFFFF)>наводчик<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Вертолетчик<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>сапер<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>разведчик<c(FFFFFF)>"}
				{"scout2" "<c(FFFFFF)>разведчик<c(FFFFFF)>"}
				{"smg" "<c(FFFFFF)>солдат<c(FFFFFF)>"}
				{"sniper" "<c(FFFFFF)>снайпер<c(FFFFFF)>"}
				{"omon" "<c(FFFFFF)>омон<c(FFFFFF)>"}
				{"omon2" "<c(FFFFFF)>омон<c(FFFFFF)>"}
				{"omon3" "<c(FFFFFF)>омон<c(FFFFFF)>"}
				{"minmen" "<c(FFFFFF)>Миномётчик<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"at_rifle" "<c(FFFFFF)>тяж. снайпер<c(FFFFFF)>"}
				{"pzrk" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"pzrkhelp" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}

				{"morspec_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"morspec_mgun2" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"morspec_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"morspec_sniper1" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"morspec_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"morspec_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"morspec_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"morspec_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"morspec_smg3" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"morspec_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"morspec_zamcom" "<c(FFFFFF)>Зам. командира<c(FFFFFF)>"}

				{"gru_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"gru_mgun2" "<c(FFFFFF)>Разведчик-пулеметчик<c(FFFFFF)>"}
				{"gru_mgun" "<c(FFFFFF)>Разведчик-пулеметчик<c(FFFFFF)>"}
				{"gru_radio" "<c(FFFFFF)>Разведчик-радист<c(FFFFFF)>"}
				{"gru_rpg" "<c(FFFFFF)>Разведчик-гранатометчик<c(FFFFFF)>"}
				{"gru_rpghelp" "<c(FFFFFF)>Разведчик-гранатометчик<c(FFFFFF)>"}
				{"gru_smg" "<c(FFFFFF)>Разведчик-стрелок<c(FFFFFF)>"}
				{"gru_smg2" "<c(FFFFFF)>Разведчик-стрелок<c(FFFFFF)>"}
				{"gru_smg3" "<c(FFFFFF)>Разведчик-стрелок<c(FFFFFF)>"}
				{"gru_sniper" "<c(FFFFFF)>Разведчик-снайпер<c(FFFFFF)>"}
				{"gru_zamcom" "<c(FFFFFF)>Старший разведчик<c(FFFFFF)>"}
				{"gru_com_art" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}

				{"mor_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"mor_mgun2" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"mor_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"mor_mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"mor_radio" "<c(FFFFFF)>Радист<c(FFFFFF)>"}
				{"mor_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"mor_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"mor_smg4" "<c(FFFFFF)>Огнеметчик<c(FFFFFF)>"}
				{"mor_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"mor_smg3" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"mor_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"mor_zamcom" "<c(FFFFFF)>Зам. командира<c(FFFFFF)>"}
				{"mor_at_rifle" "<c(FFFFFF)>тяж. снайпер<c(FFFFFF)>"}

				{"mso_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"mso_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"mso_mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"mso_radio" "<c(FFFFFF)>Радист<c(FFFFFF)>"}
				{"mso_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"mso_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"mso_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"mso_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"mso_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}

				{"spec_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"spec_flamer" "<c(FFFFFF)>Огнеметчик<c(FFFFFF)>"}
				{"spec_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"spec_mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"spec_radio" "<c(FFFFFF)>Радист<c(FFFFFF)>"}
				{"spec_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"spec_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"spec_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"spec_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"spec_zamcom" "<c(FFFFFF)>Зам. командира<c(FFFFFF)>"}
				{"spec_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				

				{"vdv_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"vdv_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"vdv_radio" "<c(FFFFFF)>Радист<c(FFFFFF)>"}
				{"vdv_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"vdv_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"vdv_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"vdv_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"vdv_zamcom" "<c(FFFFFF)>Зам. командира<c(FFFFFF)>"}
				{"vdv_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"vdv_tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vdv_tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}

				{"morpeh_sniper" "<c(FFFFFF)>Снайпер Морской Пехоты<c(FFFFFF)>"}
				{"morpeh_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"motostrelk_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"motostrelk_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}

				{"scout_mso_com" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
				{"scout_mso_mgun" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
				{"scout_mso_smg" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
				{"scout_mso_smg2" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
				{"scout_mso_sniper" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
            }
			{"usa"
				{"antipersonel_miner" "<c(FFFFFF)>ПП минер<c(FFFFFF)>"}
				{"antitank_miner" "<c(FFFFFF)>ПТ минер<c(FFFFFF)>"}
				{"bazooker" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"bazooker2" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Инженер<c(FFFFFF)>"}
				{"flamer" "<c(FFFFFF)>Огнеметчик<c(FFFFFF)>"}
				{"mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Вертолетчик<c(FFFFFF)>"}
				{"vertpilot_apache" "<c(FFFFFF)>Вертолетчик<c(FFFFFF)>"}
				{"vertpilot_viper" "<c(FFFFFF)>Вертолетчик<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Сапер<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
				{"at_rifle" "<c(FFFFFF)>Тяж. снайпер<c(FFFFFF)>"}
				{"smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"sniper1" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"vdv" "<c(FFFFFF)>Navy SEAL<c(FFFFFF)>"}
				{"minmen" "<c(FFFFFF)>Миномётчик<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"vehicle_supporter1" "<c(FFFFFF)>Водитель<c(FFFFFF)>"}
				{"vehicle_supporter2" "<c(FFFFFF)>Водитель<c(FFFFFF)>"}
				{"vehicle_supporter3" "<c(FFFFFF)>Водитель<c(FFFFFF)>"}
				{"pzrk" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"pzrkhelp" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
				{"pzrk_new" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"pzrkhelp_new" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
				{"smg2" "<c(FFFFFF)>Cолдат<c(FFFFFF)>"}
				{"smg3" "<c(FFFFFF)>Cолдат<c(FFFFFF)>"}
				{"vdv2" "<c(FFFFFF)>Navy SEAL<c(FFFFFF)>"}
				{"vdv3" "<c(FFFFFF)>Navy SEAL<c(FFFFFF)>"}
				{"vdv4" "<c(FFFFFF)>Navy SEAL<c(FFFFFF)>"}
				{"defend" "<c(FFFFFF)>Delta<c(FFFFFF)>"}
				{"defend2" "<c(FFFFFF)>Delta<c(FFFFFF)>"}
				{"defend3" "<c(FFFFFF)>Delta<c(FFFFFF)>"}
				{"defend4" "<c(FFFFFF)>Delta<c(FFFFFF)>"}
				{"defend5" "<c(FFFFFF)>Delta<c(FFFFFF)>"}

				{"defend_com" "<c(FFFFFF)>Delta<c(FFFFFF)>"}
				{"defend_mgun" "<c(FFFFFF)>Delta<c(FFFFFF)>"}

				{"delta_bazooker" "<c(FFFFFF)>Гранатометчик Delta Force<c(FFFFFF)>"}
				{"delta_com" "<c(FFFFFF)>Ком. группы Delta Force<c(FFFFFF)>"}
				{"delta_marksman" "<c(FFFFFF)>Снайпер Delta Force<c(FFFFFF)>"}
				{"delta_mgun" "<c(FFFFFF)>Пулеметчик Delta Force<c(FFFFFF)>"}
				{"delta_smg" "<c(FFFFFF)>Оператор Delta Force<c(FFFFFF)>"}
				{"delta_smg2" "<c(FFFFFF)>Оператор Delta Force<c(FFFFFF)>"}
				{"delta_smg3" "<c(FFFFFF)>Оператор Delta Force<c(FFFFFF)>"}

				{"navyseal_bazooker" "<c(FFFFFF)>Гранатометчик Navy Seal<c(FFFFFF)>"}
				{"navyseal_com" "<c(FFFFFF)>Ком. группы Navy Seal<c(FFFFFF)>"}
				{"navyseal_marksman" "<c(FFFFFF)>Снайпер Navy Seal<c(FFFFFF)>"}
				{"navyseal_mgun" "<c(FFFFFF)>Оператор Navy Seal<c(FFFFFF)>"}
				{"navyseal_smg" "<c(FFFFFF)>Оператор Navy Seal<c(FFFFFF)>"}
				{"navyseal_smg2" "<c(FFFFFF)>Оператор Navy Seal<c(FFFFFF)>"}
				{"navyseal_smg3" "<c(FFFFFF)>Оператор Navy Seal<c(FFFFFF)>"}

				{"elite_com" "<c(FFFFFF)>Ком. группы<c(FFFFFF)>"}
				{"elite_snip" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"oficer_smg" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"sailor" "<c(FFFFFF)>Моряк<c(FFFFFF)>"}
				{"sailor1" "<c(FFFFFF)>Моряк<c(FFFFFF)>"}
				{"sailor2" "<c(FFFFFF)>Моряк<c(FFFFFF)>"}
				{"smg_bazooker" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"smg_gren" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"smg_helpmgun" "<c(FFFFFF)>Помощник пулеметчика<c(FFFFFF)>"}
				{"smg_marksman" "<c(FFFFFF)>Меткий стрелок<c(FFFFFF)>"}
				{"smg_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"smg_new" "<c(FFFFFF)>Стрелок<c(FFFFFF)>"}
				{"smg_newcom" "<c(FFFFFF)>Ком. Fire Team<c(FFFFFF)>"}
				{"smg_jav" "<c(FFFFFF)>Оператор FGM-148 Javelin<c(FFFFFF)>"}
				{"smg_helpjav" "<c(FFFFFF)>Пом. оператора FGM-148 Javelin<c(FFFFFF)>"}

				{"tankman_new" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}

				{"usara_com" "<c(FFFFFF)>Ком. отряда<c(FFFFFF)>"}
				{"usara_grenade" "<c(FFFFFF)>Рейнджер<c(FFFFFF)>"}
				{"usara_bazooker" "<c(FFFFFF)>Оператор FGM-148 Javelin<c(FFFFFF)>"}
				{"usara_heavy_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"usara_at_rifle" "<c(FFFFFF)>Тяж. снайпер<c(FFFFFF)>"}
				{"usara_helpbazooker" "<c(FFFFFF)>Помощник оператора FGM-148 Javelin<c(FFFFFF)>"}
				{"usara_help_mgun" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"usara_light_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"usara_smg" "<c(FFFFFF)>Рейнджер<c(FFFFFF)>"}
				{"usara_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"usara_xm25" "<c(FFFFFF)>Снайп. гранатометчик<c(FFFFFF)>"}

				{"usmc_com" "<c(FFFFFF)>Ком. отряда<c(FFFFFF)>"}
				{"usmc_heavy_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"usmc_help_heavy_mgun" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"usmc_light_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"usmc_zamcom" "<c(FFFFFF)>Старший стрелок<c(FFFFFF)>"}
				{"usmc_bazooker" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"usmc_bazooker_jav" "<c(FFFFFF)>Оператор FGM-148 Javelin<c(FFFFFF)>"}
				{"usmc_bazooker_jav_support" "<c(FFFFFF)>Пом. оператора FGM-148 Javelin<c(FFFFFF)>"}
				{"usmc_sraw" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"usmc_marksman" "<c(FFFFFF)>Меткий стрелок<c(FFFFFF)>"}
				{"usmc_medic" "<c(FFFFFF)>Медик<c(FFFFFF)>"}
				{"usmc_saper" "<c(FFFFFF)>Сапер<c(FFFFFF)>"}
				{"usmc_smg" "<c(FFFFFF)>Стрелок<c(FFFFFF)>"}
;===============================================================
				{"us_army_sniper" "<c(FFFFFF)>Снайпер US Army<c(FFFFFF)>"}
				{"us_army_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"usmc_sniper" "<c(FFFFFF)>Снайпер USMC<c(FFFFFF)>"}
				{"usmc_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"usmc_smg2" "<c(FFFFFF)>Стрелок<c(FFFFFF)>"}
				{"usmc_heavy_sniper" "<c(FFFFFF)>Тяж. снайпер<c(FFFFFF)>"}
				{"operator_bpla" "<c(FFFFFF)>Оператор БПЛА<c(FFFFFF)>"}
				
				{"2smg_bazooker" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"2smg_bazooker2" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"2smg_heavy_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"2smg_gren" "<c(FFFFFF)>Гренадер<c(FFFFFF)>"}
				{"2smg_help_bazooker2" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"2smg_helpmgun" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"2smg_marksman" "<c(FFFFFF)>Меткий стрелок<c(FFFFFF)>"}
				{"2smg_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"2smg_new" "<c(FFFFFF)>Стрелок<c(FFFFFF)>"}
				{"2smg_newcom" "<c(FFFFFF)>Ком. отряда<c(FFFFFF)>"}
				
				{"delta_bazooker_sso" "<c(FFFFFF)>Гранатометчик Delta Force<c(FFFFFF)>"}
				{"delta_com_sso" "<c(FFFFFF)>Ком. группы Delta Force<c(FFFFFF)>"}
				{"delta_marksman_sso" "<c(FFFFFF)>Снайпер Delta Force<c(FFFFFF)>"}
				{"delta_mgun_sso" "<c(FFFFFF)>Пулеметчик Delta Force<c(FFFFFF)>"}
				{"delta_smg_sso" "<c(FFFFFF)>Оператор Delta Force<c(FFFFFF)>"}
				{"delta_smg2_sso" "<c(FFFFFF)>Оператор Delta Force<c(FFFFFF)>"}

				{"navyseal_com_art" "<c(FFFFFF)>Ком. группы Navy Seal<c(FFFFFF)>"}
				{"navyseal_marksman_art" "<c(FFFFFF)>Снайпер Navy Seal<c(FFFFFF)>"}
				{"navyseal_smg_art" "<c(FFFFFF)>Оператор Navy Seal<c(FFFFFF)>"}

				{"tankman_usmc" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman_usmc2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman_usmc3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}

				{"vehicle_supporter_usmc" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			}
			{"idf"
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"idf_bazooker" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"idf_bazooker2" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"idf_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"idf_marksman" "<c(FFFFFF)>Меткий стрелок<c(FFFFFF)>"}
				{"idf_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"idf_smg" "<c(FFFFFF)>Стрелок<c(FFFFFF)>"}
				{"idf_smg2" "<c(FFFFFF)>Стрелок<c(FFFFFF)>"}
				{"idf_at_rifle" "<c(FFFFFF)>Тяж. снайпер<c(FFFFFF)>"}
				{"idf_hmgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"idf_hmgun_help" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"idf_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"idf_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"sayeret_matkal_bazooker" "<c(FFFFFF)>Гранатометчик Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_bazooker2" "<c(FFFFFF)>Гранатометчик Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_com" "<c(FFFFFF)>Ком. отделения Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_heavy_mgun" "<c(FFFFFF)>Пулеметчик Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_marksman" "<c(FFFFFF)>Меткий стрелок Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_mgun" "<c(FFFFFF)>Пулеметчик Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_smg" "<c(FFFFFF)>Стрелок Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_smg2" "<c(FFFFFF)>Стрелок Sayeret Matkal<c(FFFFFF)>"}

			}
            {"frg"
				{"frg_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"frg_gren" "<c(FFFFFF)>Гренадёр<c(FFFFFF)>"}
				{"frg_light_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"frg_medic" "<c(FFFFFF)>Медик<c(FFFFFF)>"}
				{"frg_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"frg_mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Инженер<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"frg_rifleman" "<c(FFFFFF)>Стрелок<c(FFFFFF)>"}
				{"frg_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"frg_rpg2" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"frg_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"frg_rpghelp2" "<c(FFFFFF)>Оператор SPIKE-SR<c(FFFFFF)>"}
				{"frg_heavy_sniper" "<c(FFFFFF)>Тяж. снайпер<c(FFFFFF)>"}
				{"frg_heavy_sniper_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"frg_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"frg_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"frg2_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"frg2_gren" "<c(FFFFFF)>Гренадёр<c(FFFFFF)>"}
				{"frg2_medic" "<c(FFFFFF)>Медик<c(FFFFFF)>"}
				{"frg2_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"frg2_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"frg2_rpg2" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"frg2_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"ksk_com" "<c(FFFFFF)>Ком. отделения KSK<c(FFFFFF)>"}
				{"ksk_smg3" "<c(FFFFFF)>Оператор KSK<c(FFFFFF)>"}
				{"ksk_mgun" "<c(FFFFFF)>Пулеметчик KSK<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>Разведчик-диверсант<c(FFFFFF)>"}
				{"ksk_smg" "<c(FFFFFF)>Оператор KSK<c(FFFFFF)>"}
				{"ksk_smg2" "<c(FFFFFF)>Оператор KSK<c(FFFFFF)>"}
				{"ksk_rpg" "<c(FFFFFF)>Гранатомётчик KSK<c(FFFFFF)>"}
				{"ksk_marksman" "<c(FFFFFF)>Снайпер KSK<c(FFFFFF)>"}
				{"spec_ksk" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}	
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}	
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}	
				{"frg_operator_bpla" "<c(FFFFFF)>Оператор БПЛА<c(FFFFFF)>"}				
				{"gren_ksk" "<c(FFFFFF)>Гренадер KSK<c(FFFFFF)>"}				
				{"ksk_com_art" "<c(FFFFFF)>Ком. отделения KSK<c(FFFFFF)>"}				
				{"ksk_com_sso" "<c(FFFFFF)>Ком. отделения KSK<c(FFFFFF)>"}				
				{"ksk_marksman_art" "<c(FFFFFF)>Меткий стрелок KSK<c(FFFFFF)>"}				
				{"ksk_marksman_sso" "<c(FFFFFF)>Меткий стрелок KSK<c(FFFFFF)>"}				
				{"ksk_mgun_sso" "<c(FFFFFF)>Пулеметчик KSK<c(FFFFFF)>"}				
				{"ksk_rpg_sso" "<c(FFFFFF)>Гранатометчик KSK<c(FFFFFF)>"}				
				{"ksk_smg_art" "<c(FFFFFF)>Оператор KSK<c(FFFFFF)>"}				
				{"ksk_smg_sso" "<c(FFFFFF)>Оператор KSK<c(FFFFFF)>"}				
				{"ksk_smg2_sso" "<c(FFFFFF)>Оператор KSK<c(FFFFFF)>"}				
				{"ksk_smg3_sso" "<c(FFFFFF)>Оператор KSK<c(FFFFFF)>"}				
				{"marksman_ksk" "<c(FFFFFF)>Меткий стрелок KSK<c(FFFFFF)>"}				
				{"medik_ksk" "<c(FFFFFF)>Санитар KSK<c(FFFFFF)>"}				
				{"recon_ksk" "<c(FFFFFF)>Разведчик KSK<c(FFFFFF)>"}				
				{"mgun_ksk" "<c(FFFFFF)>Пулеметчик KSK<c(FFFFFF)>"}				
				{"oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"pzrk" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Сапер<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Вертолетчик<c(FFFFFF)>"}
			}
			{"fr"
				{"fr_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"fr_gren" "<c(FFFFFF)>Гренадёр<c(FFFFFF)>"}
				{"fr_light_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"fr_heavy_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"fr_heavy_mgun_help" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"fr_marksman" "<c(FFFFFF)>Меткий стрелок<c(FFFFFF)>"}
				{"fr_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"fr_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"fr_bazooker" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"fr_rpghelp" "<c(FFFFFF)>Пом. гранатомётчика<c(FFFFFF)>"}
				{"fr_eryx" "<c(FFFFFF)>Оператор ПТРК<c(FFFFFF)>"}
				{"fr_eryx_help" "<c(FFFFFF)>Пом.оператора ПТРК<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"fr_at_rifle" "<c(FFFFFF)>Анти-снайпер<c(FFFFFF)>"}
				{"fr_at_rifle_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"fr_vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Сапер<c(FFFFFF)>"}
				{"1er_rpima_fr_bazooker" "<c(FFFFFF)>Гранатомётчик 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_com" "<c(FFFFFF)>Ком. отделения 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_gren" "<c(FFFFFF)>Гренадёр 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_heavy_mgun" "<c(FFFFFF)>Пулеметчик 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_light_mgun" "<c(FFFFFF)>Пулеметчик 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_marksman" "<c(FFFFFF)>Меткий стрелок 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_smg" "<c(FFFFFF)>Стрелок 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_smg2" "<c(FFFFFF)>Стрелок 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_smg3" "<c(FFFFFF)>Стрелок 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_zamcom" "<c(FFFFFF)>Старший стрелок 1ER Rpima<c(FFFFFF)>"}
				{"antipersonel_miner" "<c(FFFFFF)>ПП минер<c(FFFFFF)>"}
				{"antitank_miner" "<c(FFFFFF)>ПТ минер<c(FFFFFF)>"}
				{"fr_scout" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
				{"fr_scout_com" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
				{"fr_scout_mgun" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
				{"fr_scout_smg" "<c(FFFFFF)>Разведчик<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Вертолетчик<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
			}
			{"hun"
				{"hun_bazooker" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"hun_rpghelp" "<c(FFFFFF)>Пом. гранатомётчика<c(FFFFFF)>"}

			}
			{"brit"
				{"brit_at_rifle" "<c(FFFFFF)>Анти-снайпер<c(FFFFFF)>"}
				{"brit_at_rifle_help" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"brit_marksman" "<c(FFFFFF)>Марксман<c(FFFFFF)>"}
				{"brit_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"brit2_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"brit_bazooker" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"brit2_bazooker" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"brit_bazooker_help" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"brit_gren" "<c(FFFFFF)>Гренадер<c(FFFFFF)>"}
				{"brit2_gren" "<c(FFFFFF)>Гренадер<c(FFFFFF)>"}
				{"brit_light_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"brit_smg" "<c(FFFFFF)>Стрелок<c(FFFFFF)>"}
				{"brit2_smg" "<c(FFFFFF)>Стрелок<c(FFFFFF)>"}
				{"brit_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"brit_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"brit_heavy_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
                {"brit_jav" "<c(FFFFFF)>Оператор FGM-148 Javelin<c(FFFFFF)>"}
                {"brit_javhelp" "<c(FFFFFF)>Помощник оператора FGM-148 Javelin<c(FFFFFF)>"}
				{"2sas_com" "<c(FFFFFF)>Ком. отделения SAS<c(FFFFFF)>"}
				{"2sas_heavy_mgun" "<c(FFFFFF)>Пулеметчик SAS<c(FFFFFF)>"}
				{"2sas_marksman" "<c(FFFFFF)>Марксман SAS<c(FFFFFF)>"}
				{"2sas_rocket_launcher" "<c(FFFFFF)>Гранатомётчик SAS<c(FFFFFF)>"}
				{"2sas_smg" "<c(FFFFFF)>Стрелок SAS<c(FFFFFF)>"}
				{"2sas_smg2" "<c(FFFFFF)>Стрелок SAS<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}	
				{"sas_bazooker" "<c(FFFFFF)>Гранатомётчик SAS<c(FFFFFF)>"}
				{"sas_com" "<c(FFFFFF)>Ком. отделения SAS<c(FFFFFF)>"}
				{"sas_heavy_mgun" "<c(FFFFFF)>Пулеметчик SAS<c(FFFFFF)>"}
				{"sas_light_mgun" "<c(FFFFFF)>Пулеметчик SAS<c(FFFFFF)>"}
				{"sas_marksman" "<c(FFFFFF)>Марксман SAS<c(FFFFFF)>"}
				{"sas_mgun" "<c(FFFFFF)>Пулеметчик SAS<c(FFFFFF)>"}
				{"sas_rifleman" "<c(FFFFFF)>Стрелок SAS<c(FFFFFF)>"}
				{"sas_rocket_launcher" "<c(FFFFFF)>Гранатаметчик SAS<c(FFFFFF)>"}
				{"sas_scout_bazooker" "<c(FFFFFF)>Диверсант  SAS<c(FFFFFF)>"}
				{"sas_scout_com" "<c(FFFFFF)>Диверсант  SAS<c(FFFFFF)>"}
				{"sas_scout_rifleman" "<c(FFFFFF)>Диверсант  SAS<c(FFFFFF)>"}
				{"sas_smg" "<c(FFFFFF)>Стрелок SAS<c(FFFFFF)>"}
				{"sas_smg2" "<c(FFFFFF)>Стрелок SAS<c(FFFFFF)>"}
				{"sas_smg3" "<c(FFFFFF)>Стрелок SAS<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Вертолетчик<c(FFFFFF)>"}
				{"vertpilot_apache" "<c(FFFFFF)>Вертолетчик<c(FFFFFF)>"}
			}
            {"cz"
				{"cz_bazooker" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"cz_bazooker2" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"2cz_bazooker2" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"cz_rpghelp" "<c(FFFFFF)>Пом. гранатомётчика<c(FFFFFF)>"}
				{"2cz_rpghelp" "<c(FFFFFF)>Пом. гранатомётчика<c(FFFFFF)>"}
				{"cz_mgunhelper" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"cz_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"cz_gren" "<c(FFFFFF)>Гренадёр<c(FFFFFF)>"}
				{"cz_medic" "<c(FFFFFF)>Медик<c(FFFFFF)>"}
				{"cz_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"cz_mgunhelper" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"cz_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}	
				{"cz_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}	
				{"cz_sniper" "<c(FFFFFF)>Меткий стрелок<c(FFFFFF)>"}
				{"elite" "<c(FFFFFF)>Диверсант<c(FFFFFF)>"}
				{"elite2" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"elite3" "<c(FFFFFF)>Диверсант<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Инженер<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}		
				{"pzrk_soldier" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"pzrk_help_soldier" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
				{"pzrk" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"pzrkhelp" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>Диверсант<c(FFFFFF)>"}
				{"sniper_cz" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			}
            {"pol"
				{"pol_borderguard" "<c(FFFFFF)>Пограничник<c(FFFFFF)>"}
				{"pol_bazooker" "<c(FFFFFF)>Оператор FGM-148 Javelin<c(FFFFFF)>"}
				{"pol_rpghelp" "<c(FFFFFF)>Пом. гранатомётчика<c(FFFFFF)>"}
				{"pol_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"pol_gren" "<c(FFFFFF)>Гренадёр<c(FFFFFF)>"}
				{"pol_medic" "<c(FFFFFF)>Медик<c(FFFFFF)>"}
				{"pol_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"pol_mgunhelper" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"pol_rpg" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"pol_rpghelp" "<c(FFFFFF)>Помощник гранатометчика <c(FFFFFF)>"}
				{"pol_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}	
				{"pol_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}	
				{"pol_sniper" "<c(FFFFFF)>Меткий стрелок<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}		
				{"pzrk_soldier" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"pzrk_help_soldier" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>Диверсант<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			}
            {"cn"
				{"antipersonel_miner" "<c(FFFFFF)>ПП минер<c(FFFFFF)>"}
				{"antitank_miner" "<c(FFFFFF)>ПТ минер<c(FFFFFF)>"}
				{"at_rifle" "<c(FFFFFF)>Тяж. снайпер<c(FFFFFF)>"}
				{"bazooker2" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"bazooker2_help" "<c(FFFFFF)>Помощник гранатометчика<c(FFFFFF)>"}
			
				{"elite_com" "<c(FFFFFF)>Ком. отделения спецназа 82nd Group Army<c(FFFFFF)>"}
				{"elite_mgun" "<c(FFFFFF)>Пулеметчик спецназа 82nd Group Army<c(FFFFFF)>"}
				{"elite_rpg" "<c(FFFFFF)>Гранатомётчик спецназа 82nd Group Army<c(FFFFFF)>"}
				{"elite_rpghelp" "<c(FFFFFF)>Помощник гранатометчика спецназа 82nd Group Army<c(FFFFFF)>"}
				{"elite_smg" "<c(FFFFFF)>Стрелок спецназа 82nd Group Army<c(FFFFFF)>"}
				{"elite_smg2" "<c(FFFFFF)>Стрелок спецназа 82nd Group Army<c(FFFFFF)>"}
				{"elite_sniper" "<c(FFFFFF)>Снайпер спецназа 82nd Group Army<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Инженер<c(FFFFFF)>"}
				{"engineer2" "<c(FFFFFF)>Инженер<c(FFFFFF)>"}
				{"flamer" "<c(FFFFFF)>Огнеметчик<c(FFFFFF)>"}
				
				{"ukr_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"ukr_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"ukr_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"ukr_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"ukr_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"ukr_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"ukr_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				
				{"taj_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"taj_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"taj_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"taj_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"taj_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"taj_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"taj_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}

				{"kz_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"kz_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"kz_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"kz_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"kz_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"kz_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"kz_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}

				{"bel_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"bel_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"bel_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"bel_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"bel_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"bel_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"bel_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}

				{"a_bel_res_com" "<c(FFFFFF)>Командир отделения территориальных войск<c(FFFFFF)>"}
				{"a_bel_res_mgun" "<c(FFFFFF)>Пулеметчик территориальных войск <c(FFFFFF)>"}
				{"a_bel_res_rpg" "<c(FFFFFF)>Гранатометчик территориальных войск<c(FFFFFF)>"}
				{"a_bel_res_smg" "<c(FFFFFF)>Солдат территориальных войск<c(FFFFFF)>"}
				{"a_bel_res_smg2" "<c(FFFFFF)>Солдат территориальных войск<c(FFFFFF)>"}
				
				
				{"avispas_com" "<c(FFFFFF)>Командир кубинских диверсантов<c(FFFFFF)>"}
				{"avispas_rpg" "<c(FFFFFF)>Кубинский диверсант<c(FFFFFF)>"}

				{"mso_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"mso_medic" "<c(FFFFFF)>Санитар<c(FFFFFF)>"}
				{"mso_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"mso_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"mso_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"mso_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"mso_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"mso_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
			
				{"oficer" "<c(FFFFFF)>офицер<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}
				{"pilot_fighter" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}
				{"pzrk" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"pzrkhelp" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Сапер<c(FFFFFF)>"}
				{"sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
			
				{"spec_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"spec_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"spec_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"spec_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"spec_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"spec_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"spec_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
			
				{"spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"vehicle_supporter_art" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Вертолетчик<c(FFFFFF)>"}
				{"vertpilot_z10" "<c(FFFFFF)>Вертолетчик<c(FFFFFF)>"}
				{"operator_bpla" "<c(FFFFFF)>Оператор БПЛА<c(FFFFFF)>"}
			}
            {"odkb"
				{"bel_borderguard" "<c(FFFFFF)>Пограничник<c(FFFFFF)>"}
				{"bel_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"bel_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"bel_mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"bel_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"bel_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"bel_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"bel_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"bel_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"bel_vertpilot" "<c(FFFFFF)>Летчик<c(FFFFFF)>"}
				{"bel_tankman" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"bel_tankman2" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"bel_tankman3" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
			
				{"iran_bazooker2" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"iran_bazooker2_help" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"iran_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"iran_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"iran_mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"iran_pilot" "<c(FFFFFF)>Летчик<c(FFFFFF)>"}
				{"iran_pzrk" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"iran_pzrkhelp" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
				{"iran_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"iran_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"iran_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"iran_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"iran_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"iran_tankman" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"iran_tankman2" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"iran_tankman3" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"iran_vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			
				{"kz_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"kz_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"kz_mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"kz_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"kz_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"kz_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"kz_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"kz_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"kz_tankman" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"kz_tankman2" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"kz_tankman3" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
			
				{"taj_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"taj_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"taj_mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"taj_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"taj_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"taj_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"taj_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"taj_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}			
			
				{"tankman" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
			
				{"vdv_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"vdv_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"vdv_radio" "<c(FFFFFF)>Радист<c(FFFFFF)>"}
				{"vdv_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"vdv_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"vdv_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"vdv_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"vdv_zamcom" "<c(FFFFFF)>Зам. командира<c(FFFFFF)>"}
				{"vdv_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"vdv_tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vdv_tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
			
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			}
		}

		{"single"
			{"rus"
				{"samoilov" "Александр Самойлов"}
				{"filipov" "Роман Филиппов"}
				{"sso" "Боец ССО РФ"}
				{"doronin" "Василий Доронин"}
				{"doronin_office" "Василий Доронин"}
				{"pankratov" "Дмитрий Панкратов"}
				{"grishenko" "Виктор Грищенко"}
				{"tretyak" "Андрей Третьяк"}
				{"rudzinskiy" "Андрей Рудзинский"}
				{"fomin" "Виктор Фомин"}
				{"gromov" "Юрий Громов"}
				{"sorokin" "Станислав Сорокин"}
				{"Podolansky" "Владимир Подолянский"}
				{"spec_com_Mishin" "Алексей Мишин"}
				{"spec_sniper_Tihomirov" "Константин Тихомиров"}
				{"spec_smgpod_Pozolotin" "Валерий Позолотин"}
				{"spec_radio_Klimov" "Глеб Климов"}
				{"spec_groza_Nasedkin" "Василий Наседкин"}
				{"spec_smgopt_Savin" "Виктор Савин"}
				{"spec_smgrpg_Aleksandrov" "Владимир Александров"}
				{"spec_mgun_Nasonov" "Макар Насонов"}
				{"spec_mgun1_Romanov" "Захар Романов"}
				{"spec_rpg_Zaycev" "Роман Зайцев"}
				{"spec_rpghelp_Belov" "Виталий Белов"}
				{"jivaev" "Эдуард Живаев"}
				{"genne" "Александр Генне"}
				{"luchnikov" "Аркадий Лучников"}
				{"sherbakov" "Виктор Щербаков"}
				{"arhipov" "Виктор Архипов"}
				{"judin" "Евгений Юдин"}
				{"mayor" "Майор Филимонов"}
				{"captain" "Капитан Морозов"}
				{"guba" "Полковник Губа"}
				{"volkov" "Ст.лейтенант Волков"}
				{"groz_burlakov" "Подполковник Семен Бурлаков, начштаба 81мсп"}
				{"groz_chernutskiy" "Майор А. Чернуцкий"}
				{"groz_chmirev" "Капитан Юрий Чмирев, ком. 1 роты"}
				{"groz_klapcov" "Подполковник Юрий Клапцов, нач. оперотдела 131омсбр"}
				{"groz_klupov" "Капитан Рустем Клупов, ком. 3 роты"}
				{"groz_kojura" "Ст. лейтенант Олег Кожура, медслужба"}
				{"groz_pulikovskiy" "Генерал-майор Константин Пуликовский, ком. группой Север"}
				{"groz_savin" "Полковник Иван Савин, комбриг 131омсбр"}
				{"groz_tupikov" "Подполковник Николай Тупиков, нач. медслужбы "}
				{"groz_vechkanov" "Капитан Игорь Вечканов, ком. 8 тр"}
				{"leviaf_11div949" "Контр-адмирал Валерий Варфоломеев, ком. 11 дивизии ПЛ"}
				{"leviaf_956bistriy" "Кап-один Александр Катков, ЭМ \"Быстрый\""}
				{"leviaf_956ushakov" "Кап-два Сергей Русаков, ЭМ \"Адм. Ушаков\""}
				{"leviaf_1144petr" "Кап-один Игорь Никитин, ТАРКР \"Петр Великий\""}
				{"leviaf_1164ust" "Кап-один Владимир Кузьмин, РКР \"Адм. Устинов\""}
				{"leviaf_fleetcom" "Вице-адмирал Александр Моисеев, ком. Северным флотом РФ"}
				{"leviaf_kuznecov" "Кап-один Сергей Артамонов, ТАКР \"Адм. Кузнецов\""}
				{"leviaf_officer" "Офицер ВМФ РФ"}
				{"zguralsky" "Павел Згуральский"}
			}
			{"usa"
				{"pittard" "Dana Pittard"}
				{"jackson" "Oliver Jackson"}
                {"steffens" "Michael Steffens"}
				{"bazooker" "Гранатометчик"}
				{"bazooker2" "Гранатометчик"}
				{"gren" "Гренадер"}
				{"help_bazooker2" "Пом. гранатометчика"}
				{"helpmgun" "Пом. пулеметчика"}
				{"marksman" "Меткий стрелок"}
				{"mgun" "Пулеметчик"}
				{"sailor" "Моряк"}
				{"smg" "Солдат"}
				{"smgcom" "Ком. отряда"}
				{"tankman" "Танкист"}
				{"us90-99_army_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"us90-99_army_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"us90-99_at" "<c(FFFFFF)>Тяж. снайпер<c(FFFFFF)>"}
				{"us90-99_help_at" "<c(FFFFFF)>Пом. снайпера<c(FFFFFF)>"}
				{"us90-99_oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"us90-99alpha_grenadier_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"us90-99alpha_heavy_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"us90-99alpha_rifleman" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"us90-99alpha_squad_leader" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"us90-99alpha_team_leader" "<c(FFFFFF)>Ком. Fire team<c(FFFFFF)>"}
				{"us90-99bravo_automatic_rifleman" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"us90-99bravo_grenadier_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"us90-99bravo_rifleman" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"us90-99bravo_team_leader" "<c(FFFFFF)>Ком. Fire team<c(FFFFFF)>"}
				{"us90-99engineer" "<c(FFFFFF)>Инженер<c(FFFFFF)>"}
				{"us90-99pzrk" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"us90-99pzrkhelp_new" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
				{"us90-99vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			}
			{"chn_summer"
				{"bazooker" "Гранатометчик"}
				{"defend" "Опытный боевик"}
				{"defend2" "Опытный боевик"}
				{"defend3" "Опытный боевик"}
				{"defend4" "Опытный боевик"}
				{"defend5" "Опытный боевик"}
				{"elite" "Опытный боевик"}
				{"elite2" "Опытный боевик"}
				{"elite3" "Опытный боевик"}
				{"lshturm" "Опытный боевик"}
				{"mg" "пулеметчик"}
				{"mg2" "пулеметчик"}
				{"mg3" "пулеметчик"}
				{"mgun" "пулеметчик"}
				{"minmen" "миномётчик"}
				{"minmen2" "миномётчик"}
				{"oficer" "офицер"}
				{"saper" "сапер"}
				{"shturm" "Опытный боевик"}
				{"shturm2" "Опытный боевик"}
				{"shturm3" "Опытный боевик"}
				{"smg" "солдат"}
				{"smg2" "солдат"}
				{"smg3" "солдат"}
				{"sniper" "снайпер"}
				{"tankman" "танкист"}
				{"tankman2" "ТТшник"}
				{"tankman3" "танкист"}
				{"vehicle_supporter" "Оператор воор./техн."}
				{"groz_kovalev" "Депутат Сергей Ковалев, правозащитник"}
				{"groz_maskhadov" "Аслан Масхадов, нач. Генштаба ЧРИ"}
			}
			{"chn_winter"
				{"bazooker" "гранатометчик"}
				{"defend" "Опытный боевик"}
				{"defend2" "Опытный боевик"}
				{"defend3" "Опытный боевик"}
				{"defend4" "Опытный боевик"}
				{"defend5" "Опытный боевик"}
				{"elite" "Опытный боевик"}
				{"elite2" "Опытный боевик"}
				{"elite3" "Опытный боевик"}
				{"lshturm" "Опытный боевик"}
				{"mg" "пулеметчик"}
				{"mg2" "пулеметчик"}
				{"mg3" "пулеметчик"}
				{"mgun" "пулеметчик"}
				{"minmen" "миномётчик"}
				{"minmen2" "миномётчик"}
				{"oficer" "офицер"}
				{"saper" "сапер"}
				{"shturm" "Опытный боевик"}
				{"shturm2" "Опытный боевик"}
				{"shturm3" "Опытный боевик"}
				{"smg" "солдат"}
				{"smg2" "солдат"}
				{"smg3" "солдат"}
				{"sniper" "снайпер"}
				{"tankman" "танкист"}
				{"tankman2" "ТТшник"}
				{"tankman3" "танкист"}
				{"vehicle_supporter" "Оператор воор./техн."}
				{"groz_kovalev" "Депутат Сергей Ковалев, правозащитник"}
				{"groz_maskhadov" "Аслан Масхадов, нач. Генштаба ЧРИ"}
			}
			{"fed_summer"
				{"antipersonel_miner" "ПП минер"}
				{"antitank_miner" "ПТ минер"}
				{"bazooker" "Гранатометчик"}
				{"bazooker2" "Гранатометчик"}
				{"engineer" "Инженер"}
				{"flamer" "Огнеметчик"}
				{"flamer2" "Огнеметчик"}
				{"mgun" "Пулеметчик"}
				{"oficer" "Офицер"}
				{"nav" "Наводчик"}
				{"pilot" "Пилот"}
				{"saper" "Сапер"}
				{"scout" "Разведчик"}
				{"scout2" "Разведчик"}
				{"smg" "Солдат"}
				{"sniper" "Снайпер"}
				{"omon" "ОМОН"}
				{"vdv" "ВДВ"}
				{"minmen" "Миномётчик"}
				{"tankman" "Танкист"}
				{"tankman2" "Танкист"}
				{"tankman3" "Танкист"}
				{"vehicle_supporter" "Оператор воор./техн."}
				{"at_rifle" "Тяж. снайпер"}
				{"elite" "Краповый берет"}
				{"elite2" "Краповый берет"}
				{"elite3" "Краповый берет"}
				{"smg2" "Солдат"}
				{"smg3" "Солдат"}
				{"omon2" "ОМОН"}
				{"omon3" "ОМОН"}
				{"vdv2" "ВДВ"}
				{"vdv3" "ВДВ"}
				{"defend" "Спецназ"}
				{"defend2" "Спецназ"}
				{"defend3" "Спецназ"}
				{"defend4" "Спецназ"}
				{"defend5" "Спецназ"}
            }
			{"fed_winter"
				{"antipersonel_miner" "ПП минер"}
				{"antitank_miner" "ПТ минер"}
				{"bazooker" "Гранатометчик"}
				{"bazooker2" "Гранатометчик"}
				{"engineer" "Инженер"}
				{"flamer" "Огнеметчик"}
				{"flamer2" "Огнеметчик"}
				{"mgun" "Пулеметчик"}
				{"oficer" "Офицер"}
				{"nav" "Наводчик"}
				{"pilot" "Пилот"}
				{"saper" "Сапер"}
				{"scout" "Разведчик"}
				{"scout2" "Разведчик"}
				{"smg" "Солдат"}
				{"sniper" "Снайпер"}
				{"omon" "ОМОН"}
				{"vdv" "ВДВ"}
				{"minmen" "Миномётчик"}
				{"tankman" "Танкист"}
				{"tankman2" "Танкист"}
				{"tankman3" "Танкист"}
				{"vehicle_supporter" "Оператор воор./техн."}
				{"at_rifle" "Тяж. снайпер"}
				{"elite" "Краповый берет"}
				{"elite2" "Краповый берет"}
				{"elite3" "Краповый берет"}
				{"smg2" "Солдат"}
				{"smg3" "Солдат"}
				{"omon2" "ОМОН"}
				{"omon3" "ОМОН"}
				{"vdv2" "ВДВ"}
				{"vdv3" "ВДВ"}
				{"defend" "Спецназ"}
				{"defend2" "Спецназ"}
				{"defend3" "Спецназ"}
				{"defend4" "Спецназ"}
				{"defend5" "Спецназ"}
            }
			{"twn"
				{"pzrk_new" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"pzrkhelp_new" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>танкист<c(FFFFFF)>"}
				{"twn_bazooker_jav" "<c(FFFFFF)>Оператор FGM-148 Javelin<c(FFFFFF)>"}
				{"twn_bazooker_jav_support" "<c(FFFFFF)>Пом. оператора FGM-148 Javelin<c(FFFFFF)>"}
				{"twn_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"twn_gren" "<c(FFFFFF)>Гренадер<c(FFFFFF)>"}
				{"twn_helpmgun" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"twn_marksman" "<c(FFFFFF)>Меткий стрелок<c(FFFFFF)>"}
				{"twn_medic" "<c(FFFFFF)>Медик<c(FFFFFF)>"}
				{"twn_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"twn_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"twn_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			}
			{"ukr"
				{"smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Летчик<c(FFFFFF)>"}

				{"mso_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"mso_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"mso_mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"mso_radio" "<c(FFFFFF)>Радист<c(FFFFFF)>"}
				{"mso_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"mso_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"mso_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"mso_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"mso_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}

				{"vdv_com" "<c(FFFFFF)>Командир отделения<c(FFFFFF)>"}
				{"vdv_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"vdv_radio" "<c(FFFFFF)>Радист<c(FFFFFF)>"}
				{"vdv_rpg" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"vdv_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"vdv_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"vdv_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"vdv_zamcom" "<c(FFFFFF)>Зам. командира<c(FFFFFF)>"}
				{"vdv_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"vdv_tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vdv_tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
			}
			{"arb"
				{"army_vehicle_rpg" "Гранатометчик"}
				{"army_com" "Ком. отделения"}
				{"army_mgun" "Пулеметчик"}			
				{"army_mgunhelp" "Пом. пулеметчика"}
				{"army_radio" "Радист"}
				{"army_rpg" "Гранатометчик"}
				{"army_rpghelp" "Пом. гранатометчика"}
				{"army_smg" "Солдат"}
				{"army_smg2" "Солдат"}
				{"army_sniper" "Снайпер"}
				{"army_tankman" "Танкист"}
				{"army_vehicle_supporter" "Оператор воор./техн."}
				{"army_saper" "Сапер"}				
				{"army_engineer" "Инженер"}
				{"boevik_mgun" "Пулеметчик"}
				{"boevik_rpg" "Гранатометчик"}
				{"boevik_rpghelp" "Пом. гранатометчика"}
				{"boevik_sharpshooter" "Стрелок"}
				{"boevik_smg" "Боевик"}
				{"boevik_smg1" "Боевик"}
				{"boevik_smg2" "Боевик"}
				{"boevik_sniper" "Снайпер"}
				{"boevik_tankman" "Танкист"}
				{"boevik_saper" "Сапер"}				
				{"boevik_engineer" "Инженер"}
				{"informator" "Аббас Хуршид"}
				{"rus_spec_com_Mishin" "Алексей Мишин"}
				{"rus_spec_sniper_Tihomirov" "Константин Тихомиров"}
				{"rus_spec_smgpod_Pozolotin" "Валерий Позолотин"}
				{"rus_spec_radio_Klimov" "Глеб Климов"}
				{"rus_spec_groza_Nasedkin" "Василий Наседкин"}
				{"rus_spec_smgopt_Savin" "Виктор Савин"}
				{"rus_spec_smgrpg_Aleksandrov" "Владимир Александров"}
				{"rus_spec_mgun_Nasonov" "Макар Насонов"}
				{"rus_spec_mgun1_Romanov" "Захар Романов"}
				{"rus_spec_rpg_Zaycev" "Роман Зайцев"}
				{"rus_spec_rpghelp_Belov" "Виталий Белов"}
				{"syr_hero_halid" "Захир Халид"}
				{"syr_hero_jabril" "Хасан Джабрил"}
				{"syr_hero_mahmud" "Тофик Махмуд"}
				{"syr_hero_malik" "Юсуф Малик"}
				{"syr_hero_mustafa" "Бакир Мустафа"}
				{"somani" "Фарид Сомани"}
				{"hussain" "Саддам Хуссейн"}
				{"haddad" "Джераб Хаддад"}
				{"umar" "Умар Аббас"}
				{"sso" "ССО"}
			}
			{"geo"
				{"geo_bazooker" "Гранатометчик"}
				{"geo_sniper" "Снайпер"}
				{"geo_mgun" "Пулеметчик"}
				{"geo_smg" "Солдат"}
				{"geo_smg2" "Солдат"}
				{"geo_specforces" "Спецназ"}
				{"geo_specforcesb" "Гранатометчик"}
				{"geo_specforcesm" "Пулеметчик"}
				{"geo_specforcess" "Снайпер"}	
				{"pilot" "Пилот"}
				{"tankman" "Танкист"}
				{"vehicle_supporter" "Оператор воор./техн."}		
 			}
			{"hun"
				{"engineer" "<c(FFFFFF)>Инженер<c(FFFFFF)>"}
				{"hun_bazooker" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"hun_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"hun_gren" "<c(FFFFFF)>Гренадёр<c(FFFFFF)>"}
				{"hun_medic" "<c(FFFFFF)>Медик<c(FFFFFF)>"}
				{"hun_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"hun_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}	
				{"hun_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}	
				{"hun_sniper" "<c(FFFFFF)>Меткий стрелок<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}		
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Инженер<c(FFFFFF)>"}
			}
			{"irq"
				{"irq_engineer" "<c(FFFFFF)>Инженер<c(FFFFFF)>"}
				{"irq_rpg" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"irq_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"irq_radio" "<c(FFFFFF)>Радист<c(FFFFFF)>"}
				{"irq_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"irq_mgunhelp" "<c(FFFFFF)>Пом. пулеметчик<c(FFFFFF)>"}
				{"irq_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}	
				{"irq_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}	
				{"irq_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}

				{"irq_recruits__rpg" "<c(FFFFFF)>Гранатометчик-призывник<c(FFFFFF)>"}	
				{"irq_recruits__smg" "<c(FFFFFF)>Солдат-призывник<c(FFFFFF)>"}	
				{"irq_recruits__smg2" "<c(FFFFFF)>Солдат-призывник<c(FFFFFF)>"}	
				{"irq_recruits_com" "<c(FFFFFF)>Ком. отделения-призывник<c(FFFFFF)>"}	
				{"irq_recruits_mgun" "<c(FFFFFF)>Пулеметчик-призывник<c(FFFFFF)>"}	

				{"irq_elite" "<c(FFFFFF)>Гвардеец<c(FFFFFF)>"}
				{"irq_elite2" "<c(FFFFFF)>Гвардеец<c(FFFFFF)>"}
				{"irq_elite3" "<c(FFFFFF)>Гвардеец<c(FFFFFF)>"}
				{"irq_elite4" "<c(FFFFFF)>Гвардеец<c(FFFFFF)>"}
				{"irq_officer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"irq_pzrk" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Пилот<c(FFFFFF)>"}		
				{"irq_tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
			}
			{"oksva"
				{"antipersonel_miner" "<c(FFFFFF)>ПП минер<c(FFFFFF)>"}
				{"antitank_miner" "<c(FFFFFF)>ПТ минер<c(FFFFFF)>"}
				{"bazooker" "<c(FFFFFF)>Гранатометчик<c(FFFFFF)>"}
				{"defend" "<c(FFFFFF)>Спецназ<c(FFFFFF)>"}
				{"defend2" "<c(FFFFFF)>Спецназ<c(FFFFFF)>"}
				{"defend3" "<c(FFFFFF)>Спецназ<c(FFFFFF)>"}
				{"defend4" "<c(FFFFFF)>Спецназ<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Инженер<c(FFFFFF)>"}
				{"flamer2" "<c(FFFFFF)>Огнеметчик<c(FFFFFF)>"}
				{"mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Сапер<c(FFFFFF)>"}
				{"smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"smg3" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vdv_com" "<c(FFFFFF)>ВДВ<c(FFFFFF)>"}
				{"vdv_mgun" "<c(FFFFFF)>ВДВ<c(FFFFFF)>"}
				{"vdv_rpg" "<c(FFFFFF)>ВДВ<c(FFFFFF)>"}
				{"vdv_smg" "<c(FFFFFF)>ВДВ<c(FFFFFF)>"}
				{"vdv_sniper" "<c(FFFFFF)>ВДВ<c(FFFFFF)>"}
				{"vdv_zamcom" "<c(FFFFFF)>ВДВ<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Летчик<c(FFFFFF)>"}
			}
			{"est"
				{"est_at_rifle" "<c(FFFFFF)>Анти-снайпер<c(FFFFFF)>"}
				{"est_at_rifle_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"est_bazooker" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"est_bazooker_jav" "<c(FFFFFF)>Оператор FGM-148 Javelin<c(FFFFFF)>"}
				{"est_bazooker_jav_support" "<c(FFFFFF)>Помощник оператора FGM-148 Javelin<c(FFFFFF)>"}
				{"est_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"est_gren" "<c(FFFFFF)>Гренадёр<c(FFFFFF)>"}
				{"est_medic" "<c(FFFFFF)>Медик<c(FFFFFF)>"}
				{"est_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"est_mgunhelper" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"est_oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"est_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"est_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"est_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"est_sniper" "<c(FFFFFF)>снайпер<c(FFFFFF)>"}
				{"est_tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"est_vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			}
			{"jap"
				{"jap_bazooker" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"jap_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"jap_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"jap_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"jap_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"jap_sniper" "<c(FFFFFF)>снайпер<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"jap_mgun_help" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"jap_marksman" "<c(FFFFFF)>Меткий стрелок<c(FFFFFF)>"}
				{"jap_army_spotter" "<c(FFFFFF)>Наводчик<c(FFFFFF)>"}
				{"pzrk_new" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"pzrkhelp_new" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
			}
			{"lat"
				{"lat_bazooker" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"lat_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"lat_gren" "<c(FFFFFF)>Гренадёр<c(FFFFFF)>"}
				{"lat_medic" "<c(FFFFFF)>Медик<c(FFFFFF)>"}
				{"lat_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"lat_mgunhelper" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"lat_oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"lat_pzrk_soldier" "<c(FFFFFF)>Оператор ПЗРК<c(FFFFFF)>"}
				{"lat_pzrk_help_soldier" "<c(FFFFFF)>Пом. ПЗРК<c(FFFFFF)>"}
				{"lat_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"lat_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"lat_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"lat_sniper" "<c(FFFFFF)>снайпер<c(FFFFFF)>"}
				{"lat_tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"lat_vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			}
			{"lit"
				{"lit_bazooker" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"lit_com" "<c(FFFFFF)>Ком. отделения<c(FFFFFF)>"}
				{"lit_gren" "<c(FFFFFF)>Гренадёр<c(FFFFFF)>"}
				{"lit_kasp" "<c(FFFFFF)>Солдат KASP<c(FFFFFF)>"}
				{"lit_kasp_bazooker" "<c(FFFFFF)>Гранатомётчик KASP<c(FFFFFF)>"}
				{"lit_kasp_mgun" "<c(FFFFFF)>Пулеметчик KASP<c(FFFFFF)>"}
				{"lit_kasp_sniper" "<c(FFFFFF)>снайпер KASP<c(FFFFFF)>"}
				{"lit_medic" "<c(FFFFFF)>Медик<c(FFFFFF)>"}
				{"lit_mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"lit_mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"lit_oficer" "<c(FFFFFF)>Офицер<c(FFFFFF)>"}
				{"lit_rpghelp" "<c(FFFFFF)>Пом. гранатометчика<c(FFFFFF)>"}
				{"lit_smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"lit_smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"lit_sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"lit_tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"lit_vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			}
			{"cu"
				{"rafael_leon_de_rubio" "<c(FFFFFF)>Рафаэль Леон де Рубио<c(FFFFFF)>"}
				{"avispas" "<c(FFFFFF)>Черная Оса<c(FFFFFF)>"}
				{"avispas_com" "<c(FFFFFF)>Черная Оса ком. отделения<c(FFFFFF)>"}
				{"avispas_marksman" "<c(FFFFFF)>Черная Оса меткий стрелок<c(FFFFFF)>"}
				{"avispas_mgun" "<c(FFFFFF)>Черная Оса пулеметчик<c(FFFFFF)>"}
				{"avispas_rpg" "<c(FFFFFF)>Черная Оса гранатометчик<c(FFFFFF)>"}
				{"avispas_smg" "<c(FFFFFF)>Черная Оса<c(FFFFFF)>"}
				{"avispas_smg2" "<c(FFFFFF)>Черная Оса<c(FFFFFF)>"}
				{"avispas_smg3" "<c(FFFFFF)>Черная Оса<c(FFFFFF)>"}
				{"mgun" "<c(FFFFFF)>Пулеметчик<c(FFFFFF)>"}
				{"mgunhelp" "<c(FFFFFF)>Пом. пулеметчика<c(FFFFFF)>"}
				{"radio" "<c(FFFFFF)><c(FFFFFF)>"}
				{"rpg" "<c(FFFFFF)>Гранатомётчик<c(FFFFFF)>"}
				{"smg" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"smg2" "<c(FFFFFF)>Солдат<c(FFFFFF)>"}
				{"sniper" "<c(FFFFFF)>Снайпер<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Танкист<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Оператор воор./техн.<c(FFFFFF)>"}
			}
		}
		{"civilian"
			{"civilian1" "Гражданский"}
			{"civilian2" "Гражданский"}
			{"civilian3" "Гражданский"}
			{"civilian4" "Гражданский"}
			{"civilian5" "Гражданский"}
			{"civilian6" "Гражданский"}
			{"civilian7" "Гражданский"}
			{"civilian8" "Гражданский"}
			{"civilian9" "Гражданский"}
			{"civilian10" "Гражданский"}
			{"civilian11" "Гражданский"}
			{"civilian1_cu" "Гражданский"}
			{"civilian2_cu" "Гражданский"}
			{"civilian3_cu" "Гражданский"}
			{"civilian4_cu" "Гражданский"}
			{"civilian5_cu" "Гражданский"}
			{"civilian6_cu" "Гражданский"}
			{"civilian7_cu" "Гражданский"}
			{"civilian8_cu" "Гражданский"}
			{"civilian9_cu" "Гражданский"}
			{"civilian10_cu" "Гражданский"}
			{"civilian11_cu" "Гражданский"}
			{"civguarda1" "Охранник"}
			{"civguarda2" "Охранник"}
			{"civguarda3" "Охранник"}
			{"civguarda4" "Охранник"}
			{"civguardb1" "Охранник"}
			{"civguardb2" "Охранник"}
			{"civguardb3" "Охранник"}
			{"civguardb4" "Охранник"}
			{"cw_civilian_med" "Врач"}
			{"cw_civilian_med_rus" "Врач"}
			{"cw_civilian_worker" "Рабочий"}
			{"cw_civilian_worker1" "Рабочий"}
			{"priv_mil_smg" "Стрелок ЧВК"}
			{"priv_mil_smg1" "Стрелок ЧВК"}
			{"priv_mil_marksman" "Марксман ЧВК"}
			{"priv_mil_rpg" "Специалист ЧВК"}
		}