;Создано maaa - DTTGOC
;LocalGen2
;Проверено Bizon и zkv2000
;Перепроверено и переделано за Bizon и zkv2000
;rev 05.07.2022
			{"mtlbm_odkb"								"<c(FFFFFF)e(shadow)>Отделение Белоруских мотострелков на МТЛБМ</c>"}		
			{"bmp1_new_odkb"								"<c(FFFFFF)e(shadow)>Войска ОДКБ(Казахстан) на БМП 1</c>"}
			{"bel_diversant"								"<c(FFFFFF)e(shadow)>Белоруские диверсанты</c>"}
			{"odkb_peha(cn)"								"<c(ABCDEF)e(shadow)>Сухопутные войска Беларуси</c>"}
			{"grad_p"								"<c(cc0000)e(shadow)>Град-П</c>"}
			{"kamaz-6350_churki"								"<c(FFFFFF)e(shadow)>Добровольцы ШОС </c>"}
			{"Hagi_wagner_grup"								"<c(FFFFFF)e(shadow)>Отделение ЧВК 'Хаги Вагнер групп'</c>"}
			{"bmp3idzsso"								"<c(FFFFFF)e(shadow)>Отделение ССО на БМП3 С ДЗ</c>"}
			{"BLR_reservist"								"<c(FFFFFF)e(shadow)>Территориальные войска Беларуси</c>"}
			{"BLR_motopehota"								"<c(FFFFFF)e(shadow)>Мобильные силы Беларуси</c>"}

			{"regular_non_mech_peha(iregular)" 						"<c(FFFFFF)e(shadow)>Иррегулярная пехота</c>"}
			{"regular_at2(iregular)" 						"<c(FFFFFF)e(shadow)>Истребители танков</c>"}
			{"gaz_66i" 						"<c(FFFFFF)e(shadow)>Пехота на ГАЗ-66</c>"}
			{"btr60i" 						"<c(FFFFFF)e(shadow)>Пехота на БТР-60</c>"}
			{"bmp1_newi" 						"<c(FFFFFF)e(shadow)>Пехота на БМП-1</c>"}
			{"pzrk(iregular)" 						"<c(FFFFFF)e(shadow)>Отряд ПЗРК</c>"}
			{"pzrk2_iregular" 						"<c(FFFFFF)e(shadow)>Мобильный отряд ПЗРК</c>"}
			{"brdm2_strelaii" 						"<c(FFFFFF)e(shadow)>СТРЕЛА-1</c>"}
			{"Shilka_i" 						"<c(FFFFFF)e(shadow)>ЗСУ-23-4 Шилка</c>"}
			{"9k35_strela-10" 						"<c(FFFFFF)e(shadow)>9К35 Стрела-10</c>"}
			{"type63_rocket2i" 						"<c(FFFFFF)e(shadow)>Тип 63</c>"}
			{"zu23-2i" 						"<c(FFFFFF)e(shadow)>ЗУ-23-2</c>"}
			{"2c3_akaciya_irg" 						"<c(FFFFFF)e(shadow)>2С3 Акация</c>"}
			{"bmp2_new_irg" 						"<c(FFFFFF)e(shadow)>БМП-2</c>"}
			{"bmd1pi" 						"<c(FFFFFF)e(shadow)>Отряд быстрого реагирования на БМД-1П</c>"}
			{"m113a_irg" 						"<c(FFFFFF)e(shadow)>Отряд пехоты на М113</c>"}
			{"sso_irg" 						"<c(FFFFFF)e(shadow)>Диверсанты на МИ-17</c>"}

			{"tankman(iregular)" 						"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"vehicle_supporter(iregular)" 						"<c(FFFFFF)e(shadow)>Операторы воор./техн.</c>"}
			{"pilot(iregular)" 						"<c(FFFFFF)e(shadow)>Пилот</c>"}	
;________________________________________________________________________________________________________
;Китай
	;общие войска
			{"bazookers2(cn)" 						"<c(FFFFFF)e(shadow)>Расчет РПГ</c>"}
			{"pzrk(cn)"								"<c(FFFFFF)e(shadow)>Расчет ПЗРК</c>"}
			{"mso(cn)"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(срочн.)A</c>"} 
			{"zsl-92ai"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(срочн.) на ZSL-92A</c>"} 
			{"shaanxi_sx2190_passengeri"			"<c(FFFFFF)e(shadow)>Отделение мотострелков(срочн.) на Shaanxi SX2190</c>"}
	;бригада поддержки
			{"tankman(cn)"							"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"tankmans(cn)"							"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"tankman3(cn)"							"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"tankmans3(cn)"						"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"vehicle_supporter(cn)"				"<c(FFFFFF)e(shadow)>Оператор воор./техн.</c>"}
			{"pilot(cn)"							"<c(FFFFFF)e(shadow)>Пилот</c>"}	
			{"operator_bpla(cn)"					"<c(FFFFFF)e(shadow)>CH-802 Rainbow БПЛА</c>"}
	;Авиационная бригада
			{"sso_cn"								"<c(FFFFFF)e(shadow)>Отделение разведчиков на Ми-171</c>"}
	;артбригада
			{"miners(cn)"							"<c(FFFFFF)e(shadow)>Минеры</c>"}
			{"sappers(cn)"							"<c(FFFFFF)e(shadow)>Саперы</c>"}
			{"spotters(cn)"							"<c(FFFFFF)e(shadow)>Передовые арткорректировшики</c>"}
	;тяжелая бригада
            {"spec(cn)"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.)</c>"} 			
			{"elite(cn)"							"<c(FFFFFF)e(shadow)>Отделение спецназа Xinjiang</c>"}
			{"shaanxi_sx2190_passengeri_cnheavy"	"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.) на Shaanxi SX2190</c>"} 
            {"zbd86ai"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.) на ZBD-86A</c>"} 			
			{"zbd04ai"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.) на ZBD-04A</c>"} 
			{"snipers2(cn)"							"<c(FFFFFF)e(shadow)>Снайперская пара</c>"}
			{"at_rifle(cn)"							"<c(FFFFFF)e(shadow)>12.7мм Снайперская пара</c>"}
	;Средняя бригада
            {"spec2(cn)"							"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.)</c>"} 			
			{"elite2(cn)"							"<c(FFFFFF)e(shadow)>Отделение спецназа Xinjiang</c>"}
			{"shaanxi_sx2190_passengeri_cnmed"		"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.) на Shaanxi SX2190</c>"} 
			{"zsl-92bi"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.) на ZSL-92B</c>"}
			{"zbl_08_atgmi"							"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.) на ZBL-08</c>"}
			{"flamers(cn)"							"<c(FFFFFF)e(shadow)>Огнеметная пара</c>"}
	;Сводный контингент ШОС
;________________________________________________________________________________________________________
;нато
	;общие войска
			{"cz_rpg(nato)"							"<c(FFFFFF)e(shadow)>Расчет РПГ M3 MAAWS</c>"}
			{"pzrk(nato)"							"<c(FFFFFF)e(shadow)>Расчет ПЗРК</c>"}
			{"tatra_t810i"							"<c(FFFFFF)e(shadow)>Отделение пехоты Чехии на TATRA T810</c>"}
			{"cz(nato)"								"<c(FFFFFF)e(shadow)>Отделение пехоты Чехии</c>"}
			{"vab_t20i"								"<c(FFFFFF)e(shadow)>Отряд пехоты Чехии на VAB T20</c>"}
			
	;бригада поддержки
			{"tankman(nato)"						"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"vehicle_supporter(nato)"				"<c(FFFFFF)e(shadow)>Оператор воор./техн.</c>"}
			{"pilot(nato)"							"<c(FFFFFF)e(shadow)>Пилот</c>"}
			{"operator_bpla(nato)"					"<c(FFFFFF)e(shadow)>EMT Aladin БПЛА</c>"}
	;воздушное командование союзников нато
			{"nh90sas"								"<c(FFFFFF)e(shadow)>Отделение SAS на NH-90</c>"}
	;противовоздушная и противоракетная оборона нато
			{"hawk_rls_nato"						"<c(FFFFFF)e(shadow)>MIM-23 Hawk AN/MPQ-50 IPAR</c>"}
	;полевая артиллерия нато
			{"miner(nato)"							"<c(FFFFFF)e(shadow)>Минеры</c>"}
			{"sappers(nato)"						"<c(FFFFFF)e(shadow)>Саперы</c>"}
			{"brit_scouts(nato)"					"<c(FFFFFF)e(shadow)>Передовые арткорректировшики SAS</c>"}
	;бундесвер
			{"frg_ksk(nato)"						"<c(FFFFFF)e(shadow)>Отделение KSK</c>"}
			{"frg_snip(nato)"						"<c(FFFFFF)e(shadow)>Снайперская пара</c>"}
			{"frg_h_snip(nato)"						"<c(FFFFFF)e(shadow)>12.7мм Снайперская пара</c>"}
		    {"frg(nato)"							"<c(FFFFFF)e(shadow)>Отделение панцергренадеров</c>"}
		    {"man_passenjeri"						"<c(FFFFFF)e(shadow)>Отделение панцергренадеров на Man Kat1</c>"}
			{"marder_1a3i"							"<c(FFFFFF)e(shadow)>Отделение панцергренадеров на Marder 1A3</c>"}
			{"boxer_mguni"							"<c(FFFFFF)e(shadow)>Отделение панцергренадеров на Boxer A1</c>"}
			{"boxer_gmgi"							"<c(FFFFFF)e(shadow)>Отделение панцергренадеров на Boxer A2</c>"}
			{"boxer_guni"							"<c(FFFFFF)e(shadow)>Отделение панцергренадеров на Boxer IFV Lance</c>"}
			{"pumai"								"<c(FFFFFF)e(shadow)>Отделение панцергренадеров на SpZ Puma</c>"}
			{"puma_pturi"							"<c(FFFFFF)e(shadow)>Отделение панцергренадеров на SpZ Puma с ПТУР</c>"}
	;вооруженные силы его величества
			{"brit_squad_elite(nato)"				"<c(FFFFFF)e(shadow)>Отделение ССО SAS</c>"}
			{"gb(nato)"								"<c(FFFFFF)e(shadow)>Отделение пехоты"}
			{"man_sx44i"							"<c(FFFFFF)e(shadow)>Отделение пехоты на Man SX44</c>"}
			{"warriori"								"<c(FFFFFF)e(shadow)>Отделение пехоты на MCV-80 Warrior</c>"}
			{"warrior_wrap2i"						"<c(FFFFFF)e(shadow)>Отделение пехоты на MCV-80 Warrior WRAP-2</c>"}
			{"fv432_mk2i"							"<c(FFFFFF)e(shadow)>Отделение пехоты на FV432</c>"}
			{"boxer_gun_noptur_gbi"					"<c(FFFFFF)e(shadow)>Отделение пехоты на ARTEC Boxer</c>"}
			{"brit_jav(nato)"						"<c(FFFFFF)e(shadow)>Расчет ПТРК Javelin</c>"}
			{"brit_shipers(nato)"					"<c(FFFFFF)e(shadow)>Снайперская пара</c>"}
			{"at_rifle_brit(nato)"					"<c(FFFFFF)e(shadow)>12.7мм Снайперская пара</c>"}
	;вооружённые силы франции
			{"fr_squad_elite(nato)"					"<c(FFFFFF)e(shadow)>Отделение ССО 1er RPIMa</c>"}
			{"at_rifle_fr(nato)"					"<c(FFFFFF)e(shadow)>12.7мм Снайперская пара</c>"}
			{"marksman_squad_fr(nato)"				"<c(FFFFFF)e(shadow)>Снайперский отряд 1er RPIMa</c>"}
			{"fr(nato)"								"<c(FFFFFF)e(shadow)>Отделение пехоты"}
			{"renault_gbc_180i"						"<c(FFFFFF)e(shadow)>Отделение пехоты на Renault GBC 180"}
			{"vbci_vpci"							"<c(FFFFFF)e(shadow)>Отделение пехоты с ПТРК на VBCI VPC</c>"}
			{"vbcii"								"<c(FFFFFF)e(shadow)>Отделение пехоты на VBCI</c>"}
			{"vbci_2i"								"<c(FFFFFF)e(shadow)>Отделение пехоты на VBCI-2</c>"}	
;________________________________________________________________________________________________________
;россия
	;общие войска
			{"bazookers2(rus)"						"<c(FFFFFF)e(shadow)>Расчет РПГ-29</c>"}
			{"pzrk(rus)"							"<c(FFFFFF)e(shadow)>Расчет ПЗРК</c>"}
			{"mso(rus)"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(срочн.)</c>"}
			{"btr80_newi"							"<c(FFFFFF)e(shadow)>Отделение мотострелков(срочн.) на БТР-80 Обр.2008</c>"}
			{"btr82ai"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(срочн.) на БТР-82А</c>"} 
			{"Ural375i"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(срочн.) на Урал-4320</c>"}
	;бригада поддержки
			{"tankman(rus)"							"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"tankmans(rus)"						"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"tankman3(rus)"						"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"tankmans3(rus)"						"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"vehicle_supporter(rus)"				"<c(FFFFFF)e(shadow)>Оператор воор./техн.</c>"}
			{"pilot(rus)"							"<c(FFFFFF)e(shadow)>Пилот</c>"}	
	;Бригада ВКС
			{"su-34_accurate_2"						"<c(FFFFFF)e(shadow)>Су-34 высокоточный</c>"}
	;Бригада ПВО
			{"sso"									"<c(FFFFFF)e(shadow)>Отделение ССО на Ми-8МТВ</c>"}
	;артбригада
			{"miners(rus)"							"<c(FFFFFF)e(shadow)>Минеры</c>"}
			{"sappers(rus)"							"<c(FFFFFF)e(shadow)>Саперы</c>"}
			{"spotters(rus)"						"<c(FFFFFF)e(shadow)>Передовые арткорректировшики</c>"}
	;бригада вдв
			{"stormtroopers2(rus)"					"<c(FFFFFF)e(shadow)>Отделение ВДВ</c>"}
			{"btr-di"								"<c(FFFFFF)e(shadow)>Отделение ВДВ на БТР-Д</c>"}
			{"bmd2i"								"<c(FFFFFF)e(shadow)>Отделение ВДВ на БМД-2</c>"}
			{"bmd4m_sadovnitsai"						"<c(FFFFFF)e(shadow)>Отделение ВДВ на БМД-4М Садовница</c>"}
			{"mi17_unarmedi"						"<c(FFFFFF)e(shadow)>Отделение ВДВ на Ми-8МТВ</c>"}
	;мотострелковая бригада
			{"elite(rus)"							"<c(FFFFFF)e(shadow)>Отделение ССО</c>"}
			{"mot(rus)"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.)</c>"} 
			{"ural375i_mot"							"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.) на Урал-4320</c>"} 
            {"BMP2_newi"							"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.) на БМП-2</c>"} 			
			{"bmp3_2i"								"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.) на БМП-3</c>"}
			{"bmp2m_newi"							"<c(FFFFFF)e(shadow)>Отделение мотострелков(контр.) на БМП-2М Бережок</c>"} 
			{"minmen(rus)"							"<c(FFFFFF)e(shadow)>Стрелок с РГ-6</c>"}
			{"snipers2(rus)"						"<c(FFFFFF)e(shadow)>Снайперская пара</c>"}
			{"at_rifle(rus)"						"<c(FFFFFF)e(shadow)>12.7мм Снайперская пара</c>"}
			{"t72b3m"								"<c(FFFFFF)e(shadow)>Т-72Б3М</c>"}
	;бригада морской пехоты
			{"morspec(rus)"							"<c(FFFFFF)e(shadow)>Отделение спецназа ВМФ</c>"}
		    {"mor(rus)"								"<c(FFFFFF)e(shadow)>Отделение морской пехоты</c>"} 
		    {"mor_flame(rus)"						"<c(FFFFFF)e(shadow)>Отделение морской пехоты с огнеметчиками</c>"} 
		    {"ural375i_mor"							"<c(FFFFFF)e(shadow)>Отделение морской пехоты на Урал-4320</c>"} 
			{"bmp2_newi2"							"<c(FFFFFF)e(shadow)>Отделение морской пехоты на БМП-2</c>"}
			{"bmp3i"								"<c(FFFFFF)e(shadow)>Отделение морской пехоты на БМП-3</c>"} 
			{"snipers(rus)"							"<c(FFFFFF)e(shadow)>Снайперская пара</c>"}
			{"at_rifle_mor(rus)"					"<c(FFFFFF)e(shadow)>12.7мм Снайперская пара</c>"}
			{"mtlbo"								"<c(FFFFFF)e(shadow)>Отряд огнеметчиков на МТ-ЛБ</c>"} 
;________________________________________________________________________________________________________
;usa
	;общие войска
			{"bazookers(usa)"						"<c(FFFFFF)e(shadow)>Расчет РПГ M3 MAAWS</c>"}
			{"bazookers2(usa)"						"<c(FFFFFF)e(shadow)>Расчет ПТРК Javelin</c>"}
			{"pzrk(usa)"							"<c(FFFFFF)e(shadow)>Расчет ПЗРК</c>"}
			{"smg(usa)"								"<c(FFFFFF)e(shadow)>Стрелковое отделение</c>"} 
			{"m939i"								"<c(FFFFFF)e(shadow)>Стрелковое отделение на М939</c>"} 
			{"mtvr_m2i"								"<c(FFFFFF)e(shadow)>Стрелковое отделение на Oshkosh MTVR Mk27</c>"}
	;бригада поддержки
			{"tankman(usa)"							"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"tankmans(usa)"						"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"tankman3(usa)"						"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"tankmans3(usa)"						"<c(FFFFFF)e(shadow)>Танкисты</c>"}
			{"vehicle_supporter(usa)"				"<c(FFFFFF)e(shadow)>Оператор воор./техн.</c>"}
			{"operator_bpla(usa)"					"<c(FFFFFF)e(shadow)>RQ-11 Raven БПЛА</c>"}
			{"pilot(usa)"							"<c(FFFFFF)e(shadow)>Пилот</c>"}
	;ввс сша (usaf)
			{"sso_usa"								"<c(FFFFFF)e(shadow)>Отделение Delta force на MH-6</c>"}
	;отделение полевой артиллерии армии сша
			{"miners(usa)"							"<c(FFFFFF)e(shadow)>Минеры</c>"}
			{"sappers(usa)"							"<c(FFFFFF)e(shadow)>Саперы</c>"}
			{"usaspot(usa)"							"<c(FFFFFF)e(shadow)>Отряд корректировщиков</c>"}
	;цахал (аои)
			{"idf_vdv(usa)"							"<c(FFFFFF)e(shadow)>Отделение Sayeret Matkal</c>"}
			{"idf(usa)"								"<c(FFFFFF)e(shadow)>Пехотное отделение</c>"}
			{"m113ai"								"<c(FFFFFF)e(shadow)>Отделение на М113</c>"}
			{"nameri"								"<c(FFFFFF)e(shadow)>Отделение на Namer</c>"}
			{"idf_at_rifle(usa)"					"<c(FFFFFF)e(shadow)>12.7мм Снайперская пара</c>"}
			{"idf_sniper(usa)"						"<c(FFFFFF)e(shadow)>Снайперская пара</c>"}
	;армия сша
			{"defend(usa)"							"<c(FFFFFF)e(shadow)>Отделение Delta force</c>"}
			{"usara(usa)"							"<c(FFFFFF)e(shadow)>Отделение рейнджеров</c>"}
			{"m939i_usarmy"							"<c(FFFFFF)e(shadow)>Отделение рейнджеров на М939</c>"}
			{"m2a3_brati"							"<c(FFFFFF)e(shadow)>Отделение рейнджеров на M2A3 Bradley</c>"}
			{"m1126jav"								"<c(FFFFFF)e(shadow)>Отделение рейнджеров на M1126 Stryker с ПТРК</c>"}
			{"m1126_mk19"							"<c(FFFFFF)e(shadow)>Отделение рейнджеров на M1126 Stryker с Mk19</c>"}
			{"m1126i"								"<c(FFFFFF)e(shadow)>Отделение рейнджеров на M1126 Stryker с M2</c>"}
			{"m1296i"								"<c(FFFFFF)e(shadow)>Отделение рейнджеров на M1296 Stryker Dragoon</c>"}
			{"us_army_sniper(usa)"					"<c(FFFFFF)e(shadow)>Снайперская пара</c>"}
			{"at_rifle(usa)"						"<c(FFFFFF)e(shadow)>12.7мм Снайперская пара</c>"}
	;корпус морской пехоты сша (usmc)
			{"navy_seals(usa)"						"<c(FFFFFF)e(shadow)>Отделение Navy SEALs</c>"}
			{"usmc(usa)"							"<c(FFFFFF)e(shadow)>Отделение морской пехоты</c>"}
			{"m939i_usmc"							"<c(FFFFFF)e(shadow)>Отделение морской пехоты на М939</c>"}
			{"aavp7i"								"<c(FFFFFF)e(shadow)>Отделение морской пехоты на AAVP-7A1 EAKK</c>"}
			{"lav25i"								"<c(FFFFFF)e(shadow)>Отделение Морской пехоты на LAV-25</c>"}
			{"usmc_sturm(usa)"						"<c(FFFFFF)e(shadow)>Штурмовой отряд морской пехоты</c>"}
			{"usmc_mgun(usa)"						"<c(FFFFFF)e(shadow)>Пулеметный отряд морской пехоты</c>"}
			{"usmc_sniper(usa)"						"<c(FFFFFF)e(shadow)>Снайперская пара</c>"}
			{"usmc_heavy_sniper(usa)"				"<c(FFFFFF)e(shadow)>12.7мм Снайперская пара</c>"}
;________________________________________________________________________________________________________
;другое
    ;china
	    {"box_weapon_cn_krasnopol"					"155мм корректируемый<c(FFAF00)> 3ОФ39<c(FFFFFF)><c(00FF00)> «Краснополь»<c(FFFFFF)>"}
	;nato
		{"bazooker_idf(nato)"						"Гранатометчик"}
		{"brit_squad(nato)"							"Пехота Великобритании"}
		{"cz_squad(nato)"							"Пехота Чешской Республики"}
		{"fr_ptrk(nato)"							"ПТРК ERYX"}
		{"fr_scouts(nato)"							"Диверсант"}
		{"fr_scouts(nato)"							"Диверсионный отряд «1ER Rpima»"}
		{"fr_squad(nato)"							"Пехота Франции"}
		{"frg_rpg(nato)"							"Гранатометчик"}
		{"frg_scouts(nato)"							"Диверсант"}
		{"frg_squad(nato)"							"Панцергренадеры"}
		{"hun_rpg(nato)"							"Расчет РПГ-7 Венгрии"}
		{"hun_squad(nato)"							"Легкая пехота"}
		{"idf_squad(nato)"							"Пехота ЦАХАЛ"}
		{"sapper(nato)"								"<c(FFFFFF)>"}
		{"tpz1a6_uki"								"<c(FFFFFF)>Пехота Великобритании на NBC Fox"}
		{"tpz1a6i"									"Infantry Czech on TpZ 1A6 Fuchs"}
		{"vab_recoi"								"<c(FFFFFF)>Пехота Франции на VAB Reco"}
		{"box_weapon_nato_vulcan"					"155mm корректируемый<c(FFAF00)><c(00FF00)> «Vulcan»<c(FFFFFF)>"}
		
	;россия
		{"ap_miners(rus)"							"ПП минеры"}
		{"at_miners(rus)"							"ПТ минеры"}
		{"bazookers(rus)"							"Расчет РПГ-7"}
		{"bazookers3(rus)"							"Гранатометчик"}
		{"defend(rus)"								"Морская пехота"}
		{"engineer(rus)"							"Инженер"}
		{"flamers(rus)"								"Огнеметчик"}
		{"flamers2(rus)"							"Реакт. огнеметчик"}
		{"mgs(rus)"									"Пулеметчик"}
		{"nav(rus)"									"Наводчик"}
		{"officer(rus)"								"Офицер"}
		{"scout2(rus)"								"Разведчик"}
		{"scouts(rus)"								"Разведчик"}
		{"smgs(rus)"								"Мотострелки"}
		{"spec(rus)"								"<c(FFFFFF)>Спецназ"}
		{"stormtroopers(rus)"						"ОМОН"}
		{"box_weapon_rus_krasnopol"					"152мм корректируемый<c(FFAF00)> 3ОФ39<c(FFFFFF)><c(00FF00)> «Краснополь»<c(FFFFFF)>"}
		{"box_weapon_rus_smerch_cl"					"Смерч<c(FFAF00)> Кассетный осколочный<c(FFFFFF)>"}
		{"box_weapon_rus_smerch_tb"					"Смерч<c(FFAF00)> Термобарический<c(FFFFFF)>"}
		{"box_weapon_rus_tornado_s_fg"				"Торнадо-С<c(FFAF00)> Фугасный высокоточный<c(FFFFFF)>"}
	;usa
		{"ap_miners(usa)"							"ПП минеры"}
		{"at_miners(usa)"							"ПТ минеры"}
		{"bazookers3(usa)"							"Гранатометчик"}
		{"elite(usa)"								"Рейнджеры"}
		{"engineer(usa)"							"Инженер"}
		{"flamers(usa)"								"Огнеметчик"}
		{"idf_squad(usa)"							"Пехота ЦАХАЛ"}
		{"marksman(usa)"							"Марксман"}
		{"minmen(usa)"								"Миномётчик"}
		{"officer(usa)"								"Офицер"}
		{"scouts(usa)"								"Разведчик"}
		{"smgs(usa)"								"Пехота"}
		{"snipers(usa)"								"<c(FFFFFF)>Снайперская пара"}
		{"stormtroopers2(usa)"						"Морская пехота"}
		{"box_weapon_usa_excalibur"					"155mm корректируемый<c(FFAF00)> M982<c(FFFFFF)><c(00FF00)> «Excalibur»<c(FFFFFF)> Block 1A-2"}
		{"box_weapon_usa_gmlrs_cl"					"GMLRS<c(FFAF00)> M31A1 кассетный<c(FFFFFF)>"}
		{"box_weapon_usa_gmlrs_aw"					"GMLRS<c(FFAF00)> M31A1 Alternate Warhead<c(FFFFFF)>"}
;________________________________________________________________________________________________________