;Создано maaa - DTTGOC
;LocalGen2
;Проверено Bizon и zkv2000
;Перепроверено и переделано за Bizon и zkv2000
;rev 04.07.2022
{"btr3e_whth_pt"						"<c(FFFFFF)e(shadow)>БТР-3</c>"}
{"btr3e"						"<c(FFFFFF)e(shadow)>БТР-3</c>"}
{"mtlb_kamikadze"						"<c(FFFFFF)e(shadow)>МТ-ЛБ</c>"}


{"btr4e1_ptur"						"<c(FFFFFF)e(shadow)>БТР-4 Буцефал</c>"}
{"btr4e1"						"<c(FFFFFF)e(shadow)>БТР-4 Буцефал</c>"}
{"btr4e1i"						"<c(FFFFFF)e(shadow)>БТР-4 Буцефал</c>"}
{"btr4e"						"<c(FFFFFF)e(shadow)>БТР-4 Буцефал</c>"}
{"btr4e_i"						"<c(FFFFFF)e(shadow)>БТР-4 Буцефал</c>"}
{"btr4e1_whth_pt"								"<c(FFFFFF)e(shadow)>БТР-4Е</c>"}



{"mi24vbomb"								"<c(FFFFFF)e(shadow)>МИ-25</c>"}
{"toyota_hilux_kornet"								"<c(FFFFFF)e(shadow)>Toyota Hilux с ПТРК Корнет</c>"}
{"ztq-15"								"<c(FFFFFF)e(shadow)>ZTQ-15</c>"}
{"2s7m_malka"								"<c(FFFFFF)e(shadow)>2C7М 'Малка'</c>"}
{"uaz469_spg9"								"<c(FFFFFF)e(shadow)>УАЗ-469 с СПГ-9</c>"}
{"uaz469_ub32"								"<c(FFFFFF)e(shadow)>УАЗ-469 с УБ-32</c>"}
{"1s91_kub_radar"								"<c(FFFFFF)e(shadow)>СУРН 1с91</c>"}
{"2k12_kub"								"<c(FFFFFF)e(shadow)>2П25 КУБ</c>"}
{"milan_stan_2"								"<c(FFFFFF)e(shadow)>MILAN-ER</c>"}
{"t64-55"								"<c(FFFFFF)e(shadow)>Т-64-55</c>"}
{"dozor-b_1"								"<c(FFFFFF)e(shadow)>Дозор-Б</c>"}
{"brdm2grom"								"<c(FFFFFF)e(shadow)>БРДМ-2 С 2А28</c>"}
{"brdm_zu"								"<c(FFFFFF)e(shadow)>БРДМ-2 С ЗУ-23</c>"}
{"t-64b_ser"								"<c(FFFFFF)e(shadow)>T-64Б Сосна обр.1980</c>"}
{"9k33_osa_akm"						"<c(FFFFFF)e(shadow)>Оса</c>"}
{"9k33_osa_akm_isis"						"<c(FFFFFF)e(shadow)>Оса</c>"}

{"toyota_hilux_tow"						"<c(FFFFFF)e(shadow)>Toyota Hilux с TOW</c>"}
{"2s7_pion"						"<c(FFFFFF)e(shadow)>2C7 Пион</c>"}

{"su-34_umpk"						"<c(FFFFFF)e(shadow)>СУ-34 УМПК</c>"}
{"mi17_unarmed_supl"						"<c(FFFFFF)e(shadow)>МИ-17 снабжения</c>"}
{"kornet_base_stan_isis"						"<c(FFFFFF)e(shadow)>9П163М-1 Корнет-П</c>"}
{"ptur_tow_isis"						"<c(FFFFFF)e(shadow)>BMG-71 TOW</c>"}
{"2b11_isis" "<c(FFFFFF)><e(shadow)>2С12 Сани</c>"}
{"brem-1" "<c(FFFFFF)><e(shadow)>БРЭМ-1</c>"}
{"brem-1_s" "<c(FFFFFF)><e(shadow)>БРЭМ-1</c>"}
{"hmmwv_isis" "<c(FFFFFF)><e(shadow)>HMMWV с ДШК</c>"}
{"kamaz_zu" "<c(FFFFFF)><e(shadow)>КАМАЗ ЗСУ-23-2</c>"}
{"zil131_2s1"	"<c(FFFFFF)e(shadow)>2С1 Гвоздика на базе ЗИЛ</c>"}
{"2c1"	"<c(FFFFFF)e(shadow)>2С1 Гвоздика</c>"}
{"2c1_rus"	"<c(FFFFFF)e(shadow)>2С1 Гвоздика</c>"}
{"2c1_isis"	"<c(FFFFFF)e(shadow)>2С1 Гвоздика</c>"}

{"t-55_rus"	"<c(FFFFFF)e(shadow)>Т-55 Артиллерийский</c>"}


{"mig-21bis_harm"		"<c(FFFFFF)e(shadow)>МИГ-21М противорадиолокационный</c>"}
{"chekan"							"<c(FFFFFF)e(shadow)>Чекан</c>"}
{"2c23"							"<c(FFFFFF)e(shadow)>2С23 НОНА-СВК</c>"}



{"leopard_2a4_dz"	"<c(FFFFFF)e(shadow)>Леопрад 2А4 с ДЗ К1</c>"}
{"m1a1_lodka"	"<c(FFFFFF)e(shadow)>ГКР-1</c>"}
{"brdm2kz"	"<c(FFFFFF)e(shadow)>БРДМ-2</c>"}
{"brdm2sr"	"<c(FFFFFF)e(shadow)>БРДМ-2</c>"}

{"uaz69s"	"<c(FFFFFF)e(shadow)>УАЗ-69М</c>"}

{"toyota_hilux_t69"	"<c(FFFFFF)e(shadow)>Toyota Hilux с Тип-69</c>"}
{"toyota_hilux_grad_p"	"<c(FFFFFF)e(shadow)>Toyota Hilux с Град-п</c>"}
{"toyota_hilux_nurs"	"<c(FFFFFF)e(shadow)>Toyota Hilux с УБ-32</c>"}
{"uazpzrk"	"<c(FFFFFF)e(shadow)>УАЗ с РПО Шмель</c>"}
{"uazm2"	"<c(FFFFFF)e(shadow)>УАЗ с М2 Browning</c>"}

{"mstasm2_odkb"	"<c(FFFFFF)e(shadow)>2С19 Мста-С</c>"}
{"kamaz_grad"	"<c(FFFFFF)e(shadow)>БМ–21А БелГрад</c>"}


{"m777a2"					"<c(FFFFFF)e(shadow)>155-мм гаубица M777А2</c>"}
{"m777a1"					"<c(FFFFFF)e(shadow)>155-мм гаубица M777А1</c>"}
{"mtlb_supl"	"<c(FFFFFF)e(shadow)>МТ-ЛБ с тяжёлыми боеприпасами</c>"}
{"9k35_strela_nurs"	"<c(FFFFFF)e(shadow)>МТ-ЛБ с УБ-32</c>"}
{"mig-21bis_pizdec"	"<c(FFFFFF)e(shadow)>СУ-7БМВЭК Ударный</c>"}
{"t80ybars"	"<c(FFFFFF)e(shadow)>Т-80 Барс</c>"}
{"t62_isis"	"<c(FFFFFF)e(shadow)>Т-62 Образца 1972 года</c>"}
{"su24m_kab"						"<c(FFFFFF)e(shadow)>СУ-24 КАБ</c>"}
{"su24m"							"<c(FFFFFF)e(shadow)>Су 24 противорадиолокационный</c>"}
{"su24m_strike"							"<c(FFFFFF)e(shadow)>Су-24 Ударный</c>"}
{"t-55_c60"									"<c(FFFFFF)e(shadow)>T-55А с башней С60</c>"}
{"hmmwv_knkrs"					"<c(FFFFFF)e(shadow)>HMMWV с ПТРК Конкурс</c>"}
{"tochka_y"					"<c(FFFFFF)e(shadow)>Точка-у</c>"}
{"tochka_y_wagner"					"<c(FFFFFF)e(shadow)>Точка-у</c>"}
{"mtlb_zu"					"<c(FFFFFF)e(shadow)>МТЛБ с ЗУ-23-2</c>"}
{"grad_p"					"<c(FFFFFF)e(shadow)>9П132 Град-П («Партизан»)</c>"}
{"m777"					"<c(FFFFFF)e(shadow)>155-мм гаубица M777</c>"}

{"tos-1a_solntsepek_odkb"					"<c(FFFFFF)e(shadow)>ТОС-1А Солнцепек</c>"}
{"t72b3_blr"						"<c(FFFFFF)e(shadow)>T-72Б3 обр.2011</c>"}
{"t72a_ser"						"<c(FFFFFF)e(shadow)>T-72А обр.1983</c>"}
{"t34-85_ser"						"<c(FFFFFF)e(shadow)>T-34-85</c>"}

{"hj8_stan_2"						"<c(FFFFFF)e(shadow)>HJ-8</c>"}
{"ptur_konkurs_2"						"<c(FFFFFF)e(shadow)>Конкурс</c>"}
{"mig-21bis_support_b8"						"<c(FFFFFF)e(shadow)>Миг-21 поддержки</c>"}

{"mt12_with_mtlb"						"<c(FFFFFF)e(shadow)>МТЛБ с МТ-12 Рапира</c>"}
{"2c4_tulpan"						"<c(FFFFFF)e(shadow)>2с4 Тюльпан</c>"}
{"maz-537"						"<c(FFFFFF)e(shadow)>МАЗ-537</c>"}
{"gaz_tigr_dz"							"<c(FFFFFF)e(shadow)>ГАЗ-233014 Тигр</c>"}

{"mtlb_c60"								"<c(FFFFFF)e(shadow)>МТ-ЛБ с С-60</c>"}
{"mtlb_vmk_ogon"						"<c(FFFFFF)e(shadow)>МТ-ЛБ с РСЗО А-22 Огонь</c>"}
{"mtlb_c5_vasilek"						"<c(FFFFFF)e(shadow)>МТ-ЛБ с блоком С-5 и минометом Василек</c>"}
{"yaz_patrior"						"<c(FFFFFF)e(shadow)>УАЗ Патриот снабжения</c>"}
{"ural-4320_long_tent_h"						"<c(FFFFFF)e(shadow)>Урал снабжения</c>"}
{"ural-4320_long_zu23-2_h"						"<c(FFFFFF)e(shadow)>Урал 4320 с ЗУ-23-2 и доп.броней</c>"}
{"yaz_patrior_rapira"						"<c(FFFFFF)e(shadow)>УАЗ Патриот с МТ-12 Рапира</c>"}
{"yaz_patrior_kornet"						"<c(FFFFFF)e(shadow)>УАЗ Патриот с ПТРК Корнет</c>"}
{"yaz_patrior_zu23_2"						"<c(FFFFFF)e(shadow)>УАЗ Патриот с ЗУ-23-2</c>"}
{"2121_atgm"						"<c(FFFFFF)e(shadow)>Нива с ПТРК Корнет</c>"}
{"t-55_ser"						"<c(FFFFFF)e(shadow)>Т-55А</c>"}
{"t62m_v2_ser"						"<c(FFFFFF)e(shadow)>Т-62М</c>"}
{"m113a_ser"						"<c(FFFFFF)e(shadow)>М-113</c>"}







;-vehicle
	;-modern
		;air_modern
			;cn
				;j-10c
					{"j-10c_aa"							"<c(FFFFFF)e(shadow)>J-10C УРВВ</c>"}
					{"j-10c_ab"							"<c(FFFFFF)e(shadow)>J-10C УРВВ+КАБ</c>"}
					{"j-10c_patrol"						"<c(FFFFFF)e(shadow)>J-10C УРВВ+ПТБ</c>"}
				;jh-7a
					{"jh-7a_antirad"					"<c(FFFFFF)e(shadow)>JH-7A Противорадиолокационный</c>"}
					{"jh-7a_at"							"<c(FFFFFF)e(shadow)>JH-7A противотанковый</c>"}
					{"jh-7a_bomber"						"<c(FFFFFF)e(shadow)>JH-7A бомбардировочный</c>"}
					{"jh-7a_kab"						"<c(FFFFFF)e(shadow)>JH-7A высокоточный</c>"}
					{"jh-7a_light"						"<c(FFFFFF)e(shadow)>JH-7A поддержки легкий</c>"}
					{"jh-7a_strike"						"<c(FFFFFF)e(shadow)>JH-7A ударный</c>"}
				{"ch802"								"<c(FFFFFF)e(shadow)>CH-802 Rainbow</c>"}
				{"mi171_china"							"<c(FFFFFF)e(shadow)>Ми-171Ш</c>"}
				{"su-35_aa_china"						"<c(FFFFFF)e(shadow)>Су-35С УРВВ</c>"}
				{"z-10_support"							"<c(FFFFFF)e(shadow)>Z-10W</c>"}
			;fr
				;nh90
					{"nh90"								"<c(FFFFFF)e(shadow)>NHI NH90</c>"}
					{"nh90_sas"							"<c(FFFFFF)e(shadow)>NHI NH90</c>"}
				;tiger_hap
					{"tiger_hap_at"						"<c(FFFFFF)e(shadow)>EC-665 Tiger HAP противотанковый</c>"}
					{"tiger_hap_escort"					"<c(FFFFFF)e(shadow)>EC-665 Tiger HAP эскортный</c>"}
					{"tiger_hap_support"				"<c(FFFFFF)e(shadow)>EC-665 Tiger HAP поддержки</c>"}
			;gb
				;eurofighter
					{"eurofighter_aa"					"<c(FFFFFF)e(shadow)>Typhoon УРВВ</c>"}
					{"eurofighter_ab"					"<c(FFFFFF)e(shadow)>Typhoon УРВВ+КАБ</c>"}
					{"eurofighter_antirad"				"<c(FFFFFF)e(shadow)>Typhoon противорадиолокационный</c>"}
					{"eurofighter_strike"				"<c(FFFFFF)e(shadow)>Typhoon ударный</c>"}
					{"eurofighter_support"				"<c(FFFFFF)e(shadow)>Typhoon поддержки</c>"}
				;tornado
					{"tornado_gr1_bomber"				"<c(FFFFFF)e(shadow)>Tornado GR1 бомбардировочный</c>"}
					{"tornado_gr1_carpet"				"<c(FFFFFF)e(shadow)>Tornado GR1 кассетный</c>"}
					{"tornado_gr4_antirad"				"<c(FFFFFF)e(shadow)>Tornado GR4 противорадиолокационный</c>"}
					{"tornado_gr4_at"					"<c(FFFFFF)e(shadow)>Tornado GR4 противотанковый</c>"}
					{"tornado_gr4_bomber1"				"<c(FFFFFF)e(shadow)>Tornado GR4 бомбардировочный</c>"}
					{"tornado_gr4_strike"				"<c(FFFFFF)e(shadow)>Tornado GR4 ударный</c>"}
					{"tornado_gr4_support"				"<c(FFFFFF)e(shadow)>Tornado GR4 поддержки</c>"}
					{"tornado_gr4_support_light"		"<c(FFFFFF)e(shadow)>Tornado GR4 поддержки легкий</c>"}
				{"f-35b_stealthaa_british"				"<c(FFFFFF)e(shadow)>F-35B УРВВ cтелс</c>"}
			;ger
				{"aladin"								"<c(00FF00)e(shadow)>EMT Aladin<c(FFFFFF)e(shadow)></c>"}
			;ir
				{"shahed136_base"						"<c(00FF00)e(shadow)>Shahed-136<c(FFFFFF)e(shadow)></c>"}
			;rus
				;an-12
					{"an-12"							"<c(FFFFFF)e(shadow)>Ан-12</c>"}
					{"an-12bk"							"<c(FFFFFF)e(shadow)>Ан-12БК</c>"}
				;eleron
					{"eleron3sv"						"<c(00FF00)e(shadow)>Комплекс дистанционного наблюдения Элерон-3СВ<c(FFFFFF)e(shadow)></c>"}
					{"eleron_catapult"					"<c(00FF00)e(shadow)>Комплекс дистанционного наблюдения Элерон-3СВ<c(FFFFFF)e(shadow)></c>"}
					{"eleron_control"					"<c(00FF00)e(shadow)>Комплекс дистанционного наблюдения Элерон-3СВ<c(FFFFFF)e(shadow)></c>"}
				;ka52
					{"ka52"								"<c(FFFFFF)e(shadow)>Ка-52 Аллигатор</c>"}
					{"ka52_germes"						"<c(FFFFFF)e(shadow)>Ка-52 Аллигатор - Гермес-А</c>"}
					{"ka52k"							"<c(FFFFFF)e(shadow)>Ка-52К Катран</c>"}
				;lancet3m
					{"lancet3m_catapult"				"<c(FFFFFF)e(shadow)>Ланцет-3М</c>"}
					{"lancet3m_cm"						"<c(FFFFFF)e(shadow)>Ланцет-3М - Кум.</c>"}
					{"lancet3m_fg"						"<c(FFFFFF)e(shadow)>Ланцет-3М - ОФ</c>"}
				;mi-24v
					{"mi-24v"							"<c(FFFFFF)e(shadow)>Ми-24В</c>"}
					{"mi-24v_2"							"<c(FFFFFF)e(shadow)>Ми-24В</c>"}
				;mi17
					{"mi17"								"<c(FFFFFF)e(shadow)>Mи-8МТВ</c>"}
					{"mi17_b8"							"<c(FFFFFF)e(shadow)>Mи-8МТВ</c>"}
					{"mi17_china"						"<c(FFFFFF)e(shadow)>Ми-171Ш</c>"}
					{"mi17_unarmed"						"<c(FFFFFF)e(shadow)>Mи-8МТВ</c>"}
				;mi8amtsh
					{"mi8amtsh"							"<c(FFFFFF)e(shadow)>Mи-8АМТШ</c>"}
					{"mi8amtsh1"						"<c(FFFFFF)e(shadow)>Mи-8АМТШ-1</c>"}
					{"mi8amtsh1_mgnar"					"<c(FFFFFF)e(shadow)>Mи-8АМТШ-1</c>"}
					{"mi8amtsh1_mgun"					"<c(FFFFFF)e(shadow)>Mи-8АМТШ-1</c>"}
				;mig-21bis
					{"mig-21bis_aa"						"<c(FFFFFF)e(shadow)>МиГ-21бис УРВВ</c>"}
					{"mig-21bis_bomber"					"<c(FFFFFF)e(shadow)>МиГ-21бис бомбардировочный</c>"}
					{"mig-21bis_support"				"<c(FFFFFF)e(shadow)>МиГ-21бис поддержки</c>"}
				;mig-29k
					{"mig-29k_aa"						"<c(FFFFFF)e(shadow)>Миг-29К УРВВ</c>"}
					{"mig-29k_ab"						"<c(FFFFFF)e(shadow)>Миг-29К УРВВ+КАБ</c>"}
					{"mig-29k_antiship"					"<c(FFFFFF)e(shadow)>Миг-29К противокорабельный</c>"}
				;mig-29s
					{"mig-29s_aa"						"<c(FFFFFF)e(shadow)>МиГ-29С УРВВ</c>"}
					{"mig-29s_aa_r77"					"<c(FFFFFF)e(shadow)>МиГ-29С УРВВ</c>"}
					{"mig-29s_aa_vks"					"<c(FFFFFF)e(shadow)>МиГ-29С УРВВ</c>"}
					{"mig-29s_ab"						"<c(FFFFFF)e(shadow)>МиГ-29С поддержки</c>"}
				;su-25sm_part1
					{"su-25sm_accurate"					"<c(FFFFFF)e(shadow)>Су-25СМ высокоточный</c>"}
					{"su-25sm_miner"					"<c(FFFFFF)e(shadow)>Су-25СМ минирования</c>"}
					{"su-25sm_support"					"<c(FFFFFF)e(shadow)>Су-25СМ поддержки</c>"}
					{"su-25sm_support_light"			"<c(FFFFFF)e(shadow)>Су-25СМ поддержки легкий</c>"}
				;su-25sm_part2
					{"su-25sm_at"						"<c(FFFFFF)e(shadow)>Су-25СМ противотанковый</c>"}
					{"su-25sm_strike"					"<c(FFFFFF)e(shadow)>Су-25СМ ударный</c>"}
				;su-34
					{"su-34_accurate_2"					"<c(FFFFFF)e(shadow)>Су-34 высокоточный</c>"}
					{"su-34_antiair"					"<c(FFFFFF)e(shadow)>Су-34 УРВВ</c>"}
					{"su-34_antirad"					"<c(FFFFFF)e(shadow)>Су-34 Противорадиолокационный</c>"}
					{"su-34_antisam"					"<c(FFFFFF)e(shadow)>Су-34 прорыв ПВО</c>"}
					{"su-34_antitank"					"<c(FFFFFF)e(shadow)>Су-34 противотанковый</c>"}
					{"su-34_bomber"						"<c(FFFFFF)e(shadow)>Су-34 высокоточный</c>"}
					{"su-34_kab"						"<c(FFFFFF)e(shadow)>Су-34 КАБ</c>"}
					{"su-34_medbomber"					"<c(FFFFFF)e(shadow)>Су-34 бомбардировочный</c>"}
					{"su-34_medbomber_light"			"<c(FFFFFF)e(shadow)>Су-34 бомбардировочный легкий</c>"}
					{"su-34_strike"						"<c(FFFFFF)e(shadow)>Су-34 ударный</c>"}
					{"su-34_support"					"<c(FFFFFF)e(shadow)>Су-34 поддержки</c>"}
				;su-35
					{"su-35_aa"							"<c(FFFFFF)e(shadow)>Су-35C УРВВ</c>"}
					{"su-35_at"							"<c(FFFFFF)e(shadow)>Су-35C противотанковый</c>"}
					{"su-35_strike"						"<c(FFFFFF)e(shadow)>Су-35C ударный</c>"}
				;su-50
					{"su-50_aa"							"<c(FFFFFF)e(shadow)>Су-57 УРВВ</c>"}
					{"su-50_ab"							"<c(FFFFFF)e(shadow)>Су-57 УРВВ+КАБ</c>"}
					{"su-50_at"							"<c(FFFFFF)e(shadow)>Су-57 противотанковый</c>"}
				{"il-76td"								"<c(FFFFFF)e(shadow)>Ил-76ТД</c>"}
				{"Ka50"									"<c(FFFFFF)e(shadow)>Ка-50 Черная Акула</c>"}
				{"Ka50sh"								"<c(FFFFFF)e(shadow)>Ка-50Ш Черная Акула</c>"}
				{"mi-24vm"								"<c(FFFFFF)e(shadow)>Ми-35М3</c>"}
				{"mi28n"								"<c(FFFFFF)e(shadow)>Ми-28Н</c>"}
				{"mi28ub"								"<c(FFFFFF)e(shadow)>Ми-28УБ</c>"}
			;usa
				;a-10_csupport
					{"a-10c_AT"							"<c(FFFFFF)e(shadow)>A-10C противотанковый</c>"}
					{"a-10c_support"					"<c(FFFFFF)e(shadow)>A-10C поддержки</c>"}
					{"a-10c_support_light"				"<c(FFFFFF)e(shadow)>A-10C поддержки легкий</c>"}
				;apache
					{"apache"							"<c(FFFFFF)e(shadow)>AH-64D Longbow</c>"}
					{"apache_brit"						"<c(FFFFFF)e(shadow)>WAH-64D Longbow</c>"}
					{"apache_spike"						"<c(FFFFFF)e(shadow)>AH-64D Longbow с Spike</c>"}
				;e-2c_hawkeye
					{"e-2c_hawkeye"						"<c(FFFFFF)e(shadow)>E-2C Hawkeye</c>"}
					{"e-2c_hawkeye_france"				"<c(FFFFFF)e(shadow)>E-2C Hawkeye</c>"}
				;f-16c
					{"f-16c_aa"							"<c(FFFFFF)e(shadow)><c(FFFFFF)e(shadow)>F-16C УРВВ</c>"}
					{"f-16c_antirad"					"<c(FFFFFF)e(shadow)><c(FFFFFF)e(shadow)>F-16C противорадиолокационный</c>"}
					{"f-16c_antirad_2"					"<c(FFFFFF)e(shadow)><c(FFFFFF)e(shadow)>F-16C противорадиолокационный</c>"}
					{"f-16c_antiship"					"<c(FFFFFF)e(shadow)>F-16C противокорабельный</c>"}
					{"f-16c_strike"						"<c(FFFFFF)e(shadow)>F-16C ударный</c>"}
					{"f-16c_support"					"<c(FFFFFF)e(shadow)>F-16C поддержки</c>"}
					{"f-16c_support_pol"				"<c(FFFFFF)e(shadow)>F-16C поддержки</c>"}
				;f-22
					{"f-22_antiair"						"<c(FFFFFF)e(shadow)>F-22 УРВВ</c>"}
					{"f-22_fighter-bomber"				"<c(FFFFFF)e(shadow)>F-22 УРВВ+КАБ</c>"}
				;f-35b
					{"f-35b_aa"							"<c(FFFFFF)e(shadow)>F-35B УРВВ</c>"}
					{"f-35b_stealthaa"					"<c(FFFFFF)e(shadow)>F-35B УРВВ cтелс</c>"}
					{"f-35b_stealthab"					"<c(FFFFFF)e(shadow)>F-35B поддержки cтелс</c>"}
					{"f-35b_strike"						"<c(FFFFFF)e(shadow)>F-35B ударный</c>"}
					{"f-35b_support"					"<c(FFFFFF)e(shadow)>F-35B поддержки</c>"}
				;f-35c
					{"f-35c_aa"							"<c(FFFFFF)e(shadow)>F-35C УРВВ</c>"}
					{"f-35c_stealthaa"					"<c(FFFFFF)e(shadow)>F-35C УРВВ cтелс</c>"}
					{"f-35c_stealthab"					"<c(FFFFFF)e(shadow)>F-35C УРВВ+КАБ стелс</c>"}
					{"f-35c_strike"						"<c(FFFFFF)e(shadow)>F-35C противокорабельный</c>"}
					{"f-35c_support"					"<c(FFFFFF)e(shadow)>F-35C поддержки</c>"}
				;switchblade300
					{"switchblade300"					"<c(FFFFFF)e(shadow)>Switchblade-300</c>"}
					{"switchblade300_catapult"			"<c(FFFFFF)e(shadow)>Switchblade-300</c>"}
				;uh60
					{"sikorsky s-70c2"					"<c(FFFFFF)e(shadow)>S-70c2</c>"}
					{"uh60"								"<c(FFFFFF)e(shadow)>UH-60 Black Hawk</c>"}
				{"a-10c_bomber"							"<c(FFFFFF)e(shadow)>A-10C бомбардировочный</c>"}
				{"ah1z"									"<c(FFFFFF)e(shadow)>AH-1Z Viper</c>"}
				{"mh-6"									"<c(FFFFFF)e(shadow)>MH-6 Little Bird</c>"}
				{"mq9"									"<c(FFFFFF)e(shadow)>MQ-9A Block 1</c>"}
				{"mq9_recon"							"<c(FFFFFF)e(shadow)>MQ-9A Block 1 (разв.)</c>"}
				{"rq11raven"							"<c(00FF00)e(shadow)>RQ-11 Raven</c>"}
				{"uh1y"									"<c(FFFFFF)e(shadow)>UH-1Y Venom</c>"}
		;art_modern
			;cn
				{"dong_feng_15b"						"<c(FFFFFF)e(shadow)>DF-15B</c>"}
				{"pll-05"								"<c(FFFFFF)e(shadow)>PLL-05</c>"}
				{"plz-05"								"<c(FFFFFF)e(shadow)>PLZ-05</c>"}
				{"plz-07a"								"<c(FFFFFF)e(shadow)>PLZ-07A</c>"}
				{"phl-03"								"<c(FFFFFF)e(shadow)>PHL-03</c>"}
				{"phl_81"								"<c(FFFFFF)e(shadow)>PHL-81</c>"}
			;gb
				{"as_90"								"<c(FFFFFF)e(shadow)>AS-90</c>"}
			;ger
				{"lars2"								"<c(FFFFFF)e(shadow)>LARS 2</c>"}
				{"pzh2000"								"<c(FFFFFF)e(shadow)>PzH 2000 A1</c>"}
			;rus
				;9k72
					{"9k72"								"<c(FFFFFF)e(shadow)>9К72 Эльбрус</c>"}
					{"9k72_for_single"					"<c(FFFFFF)e(shadow)>9К72 Эльбрус</c>"}
				;bm-30_tornado_s
					{"bm-30_smerch"						"<c(FFFFFF)e(shadow)>БМ-30 Смерч</c>"}
					{"bm-30_tornado_s"					"<c(FFFFFF)e(shadow)>9К515 Торнадо-С</c>"}
				{"2c3_akaciya"							"<c(FFFFFF)e(shadow)>2С3М Акация</c>"}
				{"2c9"									"<c(FFFFFF)e(shadow)>2С9 Нона-C</c>"}
				{"iskander"								"<c(FFFFFF)e(shadow)>9К720 Искандер-М</c>"}
				{"Koalition"							"<c(FFFFFF)e(shadow)>2С35 Коалиция-СВ</c>"}
				{"Msta"									"<c(FFFFFF)e(shadow)>2С19 Мста-С</c>"}
				{"Mstasm2"								"<c(FFFFFF)e(shadow)>2С19М2 Мста-СМ2</c>"}
				{"tos-1a_solntsepek"					"<c(FFFFFF)e(shadow)>ТОС-1А Солнцепек</c>"}
			;usa
				;m142_himars
					{"m142_himars"						"<c(FFFFFF)e(shadow)>M142 Himars</c>"}
					{"m142_himarser"					"<c(FFFFFF)e(shadow)>M142 Himars ER</c>"}
				;mlrs_new
					{"mrls"								"<c(FFFFFF)e(shadow)>M270A1</c>"}
					{"mrls_2"							"<c(FFFFFF)e(shadow)>M270A1</c>"}
					{"mrls_atacms"						"<c(FFFFFF)e(shadow)>MGM-140 ATACMS</c>"}
					{"mrls_atacms_2"					"<c(FFFFFF)e(shadow)>MGM-140 ATACMS кассетный</c>"}
					{"mrls_atacms_nato"					"<c(FFFFFF)e(shadow)>MGM-140 ATACMS</c>"}
				{"dana_152mm"							"<c(FFFFFF)e(shadow)>vz.77 ДANA</c>"}
				{"paladin"								"<c(FFFFFF)e(shadow)>M109A6 Paladin</c>"}
		;btr_modern
			;cn
				;zbl_08
					{"zbl_08"							"<c(FFFFFF)e(shadow)>ZBL-08</c>"}
					{"zbl_08_atgm"						"<c(FFFFFF)e(shadow)>ZBL-08 ПТРК</c>"}
				;zsl_92
					{"zsl-92a"							"<c(FFFFFF)e(shadow)>ZSL-92</c>"}
					{"zsl-92b"							"<c(FFFFFF)e(shadow)>ZSL-92B</c>"}
				{"aft-10"								"<c(FFFFFF)e(shadow)>AFT-10</c>"}
				{"aft-9"								"<c(FFFFFF)e(shadow)>AFT-9</c>"}
				{"hq_7b"								"<c(FFFFFF)e(shadow)>HQ-7B</c>"}
				{"ptl-02"								"<c(FFFFFF)e(shadow)>PTL-02</c>"}
				{"pgz-04"								"<c(FFFFFF)e(shadow)>PGZ-04</c>"}
				{"pgz-09"								"<c(FFFFFF)e(shadow)>PGZ-09</c>"}
				{"zbd-86"								"<c(FFFFFF)e(shadow)>ZBD-86</c>"}
				{"zbd04a"								"<c(FFFFFF)e(shadow)>ZBD-04A</c>"}
				{"zbd86a"								"<c(FFFFFF)e(shadow)>ZBD-86A</c>"}
				{"zlt_11"								"<c(FFFFFF)e(shadow)>ZLT-11</c>"}
			;fr
				;amx10rcr
					{"amx10rc"							"<c(FFFFFF)e(shadow)>AMX-10RC</c>"}
					{"amx10rcr"							"<c(FFFFFF)e(shadow)>AMX-10RCR</c>"}
				;vbi_reco
					{"vbl_anf"							"<c(FFFFFF)e(shadow)>VBL - AN-F1 7.62</c>"}
					{"vbl_milan"						"<c(FFFFFF)e(shadow)>VBL Milan</c>"}
					{"vbl_mistral"						"<c(FFFFFF)e(shadow)>VBL Mistral</c>"}
					{"vbl_reco"							"<c(FFFFFF)e(shadow)>VBL Reco 12.7</c>"}
				{"vab_mephisto"							"<c(FFFFFF)e(shadow)>VAB HOT</c>"}
				{"vab_reco"								"<c(FFFFFF)e(shadow)>VAB Reco</c>"}
				{"vab_t20"								"<c(FFFFFF)e(shadow)>VAB T20-13</c>"}
				{"vbci"									"<c(FFFFFF)e(shadow)>VBCI</c>"}
				{"vbci_2"								"<c(FFFFFF)e(shadow)>VBCI-2</c>"}
				{"vbci_vpc"								"<c(FFFFFF)e(shadow)>VBCI VPC</c>"}
			;gb
				;warrior
					{"warrior"							"<c(FFFFFF)e(shadow)>MCV-80 Warrior</c>"}
					{"warrior_wrap2"					"<c(FFFFFF)e(shadow)>MCV-80 Warrior WRAP-2</c>"}
				{"ajax"									"<c(FFFFFF)e(shadow)>AJAX(Scout SV)</c>"}
				{"boxer_artec_mgun"						"<c(FFFFFF)e(shadow)>Boxer MIV</c>"}
				{"boxer_gun_noptur_gb"					"<c(FFFFFF)e(shadow)>ARTEC Boxer Block 1</c>"}
				{"fv103_spartan"						"<c(FFFFFF)e(shadow)>Fv103 Spartan</c>"}
				{"fv432_mk2"							"<c(FFFFFF)e(shadow)>Fv432 Mk2</c>"}
				{"fv107scimitar_mk2"					"<c(FFFFFF)e(shadow)>FV107 Scimitar</c>"}
			;ger
				;boxer_apc
					{"boxer_gmg"						"<c(FFFFFF)e(shadow)>Boxer A2</c>"}
					{"boxer_mgun"						"<c(FFFFFF)e(shadow)>Boxer A1</c>"}
				;boxer_gun
					{"boxer_gun"						"<c(FFFFFF)e(shadow)>Boxer Block 1</c>"}				
					{"boxer_gun_noptur"					"<c(FFFFFF)e(shadow)>Boxer Block 1</c>"}
				;fennek
					{"fennek"							"<c(FFFFFF)e(shadow)>KWM Fennek ККП</c>"}
					{"fennek_gmg"						"<c(FFFFFF)e(shadow)>KWM Fennek АГС</c>"}
				;tpz1a6
					{"tpz1a6"							"<c(FFFFFF)e(shadow)>TpZ 1A6 Fuchs</c>"}
					{"tpz1a6_uk"						"<c(FFFFFF)e(shadow)>Tpz-1 Fuchs NBC</c>"}
				{"marder_1a3"							"<c(FFFFFF)e(shadow)>Marder 1A3</c>"}
				{"puma"									"<c(FFFFFF)e(shadow)>SPz Puma VJTF</c>"}
				{"puma_noptur"							"<c(FFFFFF)e(shadow)>SPz Puma</c>"}
				{"wiesel1_gun"							"<c(FFFFFF)e(shadow)>Wiesel 1 Mk20</c>"}
				{"wiesel1_tow"							"<c(FFFFFF)e(shadow)>Wiesel 1 TOW</c>"}
			;pol
				{"kto_rosomak"							"<c(FFFFFF)e(shadow)>KTO Rosomak</c>"}
			;rus
				;-mtlb_new
					{"mtlb"								"<c(FFFFFF)e(shadow)>МТ-ЛБ</c>"}
					{"mtlb_new"							"<c(FFFFFF)e(shadow)>МТ-ЛБ</c>"}
					{"mtlb_vmk"							"<c(FFFFFF)e(shadow)>МТ-ЛБ ВМК</c>"}
					{"mtlb_vmk_no_ammobox"				"<c(FFFFFF)e(shadow)>МТ-ЛБ ВМК</c>"}
				;9k35_sterla-10
					{"9k35_strela-10"					"<c(FFFFFF)e(shadow)>9К35 Стрела-10</c>"}
					{"9k35_strela-10m3"					"<c(FFFFFF)e(shadow)>9К35 Стрела-10М3</c>"}
					{"9k35_strela-10mn"					"<c(FFFFFF)e(shadow)>9К35 Стрела-10МН</c>"}
				;bmd1
					{"bmd1"								"<c(FFFFFF)e(shadow)>БМД-1 обр.1974</c>"}
					{"bmd1p"							"<c(FFFFFF)e(shadow)>БМД-1П</c>"}
				;bmd4m
					{"bmd4m"							"<c(FFFFFF)e(shadow)>БМД-4М</c>"}
					{"bmd4m_sadovnitsa"					"<c(FFFFFF)e(shadow)>БМД-4М с навесной броней</c>"}
				;bmp2_new
					{"bmp2_new"							"<c(FFFFFF)e(shadow)>БМП-2</c>"}
					{"bmp2_new2"						"<c(FFFFFF)e(shadow)>БМП-2</c>"}
					{"bmp2_new_without_ptyr"			"<c(FFFFFF)e(shadow)>БМП-2</c>"}
				;bmp3
					{"bmp3"								"<c(FFFFFF)e(shadow)>БМП-3 обр.1987</c>"}
					{"bmp3_2"							"<c(FFFFFF)e(shadow)>БМП-3 обр.1998</c>"}
					{"bmp3_3"							"<c(FFFFFF)e(shadow)>БМП-3 обр.2017</c>"}
					{"bmp3_derivation"					"<c(FFFFFF)e(shadow)>БМП-3 Деривация</c>"}
					{"bmp3_dz"							"<c(FFFFFF)e(shadow)>БМП-3 ДЗ</c>"}
					{"bmp3m"							"<c(FFFFFF)e(shadow)>БМП-3M</c>"}
				;btr-d
					{"btr-d"							"<c(FFFFFF)e(shadow)>БТР-Д</c>"}
					{"btr-d_zu"							"<c(FFFFFF)e(shadow)>БТР-ЗД Скрежет</c>"}
					{"btr-rd"							"<c(FFFFFF)e(shadow)>БТР-РД Робот</c>"}
				;btr80_new
					{"btr80_2_new"						"<c(FFFFFF)e(shadow)>БТР-80 обр.1984</c>"}
					{"btr80_new"						"<c(FFFFFF)e(shadow)>БТР-80 обр.2008</c>"}
				;btr80a.82a
					{"btr80a"							"<c(FFFFFF)e(shadow)>БТР-80A обр.1994</c>"}
					{"btr82a"							"<c(FFFFFF)e(shadow)>БТР-82А</c>"}
					{"btr82a_mgun"						"<c(FFFFFF)e(shadow)>БТР-82</c>"}
				;btr90_kom
					{"armbr_hqcar"						"<c(FFFFFF)e(shadow)>Танковая бригада</c>"}
					{"artbr_hqcar"						"<c(FFFFFF)e(shadow)>Артбригада</c>"}
					{"btr90_kom"						"<c(FFFFFF)e(shadow)>БТР-90К</c>"}
					{"mot_hqcar"						"<c(FFFFFF)e(shadow)>Мотострелковая бригада</c>"}
					{"specbr_hqcar"						"<c(FFFFFF)e(shadow)>Бригада морской пехоты</c>"}
					{"vdv_hqcar"						"<c(FFFFFF)e(shadow)>ВДВ</c>"}
					{"vvs_hqcar"						"<c(FFFFFF)e(shadow)>Бригада ВКС и ПВО</c>"}
				;mtlb_6mx
					{"mtlb_6ma"							"<c(FFFFFF)e(shadow)>МТ-ЛБМ 6МА</c>"}
					{"mtlb_6mb"							"<c(FFFFFF)e(shadow)>МТ-ЛБМ 6МБ</c>"}
				;uran9
					{"Uran9_assault"					"<c(FFFFFF)e(shadow)>Уран-9</c>"}
					{"Uran9_assault2"					"<c(FFFFFF)e(shadow)>Уран-9</c>"}
					{"Uran9_support"					"<c(FFFFFF)e(shadow)>Уран-9</c>"}
				{"9p149_shturm-s"						"<c(FFFFFF)e(shadow)>9П149 Штурм-С</c>"}
				{"bmd2"									"<c(FFFFFF)e(shadow)>БМД-2 Будка</c>"}
				{"bmp1_new"								"<c(FFFFFF)e(shadow)>БМП-1</c>"}
				{"bmp1_kliver"							"<c(FFFFFF)e(shadow)>БМП-1М Кливер</c>"}
				{"bmp1_new_zbd-86"						"<c(FFFFFF)e(shadow)>ZBD86</c>"}
				{"bmp2m_new"							"<c(FFFFFF)e(shadow)>БМП-2М Бережок</c>"}
				{"brdm2"								"<c(FFFFFF)e(shadow)>БРДМ-2</c>"}
				{"brdm2_atgm"							"<c(FFFFFF)e(shadow)>9П148 Конкурс</c>"}
				{"brdm2_strela"							"<c(FFFFFF)e(shadow)>9К31 Стрела-1</c>"}
				{"btr60"								"<c(FFFFFF)e(shadow)>БТР-60ПБ</c>"}
				{"btr70"								"<c(FFFFFF)e(shadow)>БТР-70 Обр.1972</c>"}
				{"btr90"								"<c(FFFFFF)e(shadow)>БТР-90 Росток</c>"}
				{"bumerang_k-16"						"<c(FFFFFF)e(shadow)>K-16 Бумеранг</c>"}
				{"bumerang_k-17"						"<c(FFFFFF)e(shadow)>K-17 Бумеранг</c>"}
				{"kamaz_43269"							"<c(FFFFFF)e(shadow)>БПМ-97 (Камаз-43269 Выстрел)</c>"}
				{"kurganec_b-10"						"<c(FFFFFF)e(shadow)>Б-10 Курганец-25</c>"}
				{"kurganec_b-11"						"<c(FFFFFF)e(shadow)>Б-11 Курганец-25</c>"}
				{"sprutsd"								"<c(FFFFFF)e(shadow)>2С25 Спрут-СД</c>"}
			;usa
				;bredly
					{"bredly"							"<c(FFFFFF)e(shadow)>M2A2 Bradley</c>"}
					{"m2a3"								"<c(FFFFFF)e(shadow)>M2A3 Bradley</c>"}
					{"m2a3_brat"						"<c(FFFFFF)e(shadow)>M2A3 Bradley Busk II</c>"}
				;lav25_2
					{"bund_hqcar"						"<c(FFFFFF)e(shadow)>Bundeswehr</c>"}
					{"lav25_2"							"<c(FFFFFF)e(shadow)>LAV-25 C2</c>"}
					{"ngrd_hqcar"						"<c(FFFFFF)e(shadow)>Национальная гвардия США</c>"}
					{"usaf_hqcar"						"<c(FFFFFF)e(shadow)>ВВС США</c>"}
					{"usarmy_hqcar"						"<c(FFFFFF)e(shadow)>Армия США</c>"}
					{"usart_hqcar"						"<c(FFFFFF)e(shadow)>Отделение полевой артиллерии армии США</c>"}
					{"usmc_hqcar"						"<c(FFFFFF)e(shadow)>Корпус морской пехоты США</c>"}
				;m1126
					{"m1126"							"<c(FFFFFF)e(shadow)>M1126 Stryker ICV</c>"}
					{"m1126_jav"						"<c(FFFFFF)e(shadow)>M1256 Stryker ICVVA1-J</c>"}
					{"m1126_mk19"						"<c(FFFFFF)e(shadow)>M1126 Stryker ICV (Mk19)</c>"}
				;m113
					{"m113a"							"<c(FFFFFF)e(shadow)>M113</c>"}
					{"m113a_israel"						"<c(FFFFFF)e(shadow)>M113</c>"}
				{"aavp7"								"<c(FFFFFF)e(shadow)>AAVP-7A1 EAKK</c>"}
				{"lav-ad"								"<c(FFFFFF)e(shadow)>LAV-AD</c>"}
				{"lav-atws"								"<c(FFFFFF)e(shadow)>LAV-ATWS</c>"}
				{"lav25"								"<c(FFFFFF)e(shadow)>LAV-25</c>"}
				{"m-1129"								"<c(FFFFFF)e(shadow)>M1129 Stryker MC</c>"}
				{"m1128"								"<c(FFFFFF)e(shadow)>M1128 Stryker MGS</c>"}
				{"m1296"								"<c(FFFFFF)e(shadow)>M1296 Stryker Dragoon</c>"}
				{"m1134"								"<c(FFFFFF)e(shadow)>M1134 Stryker ATGM</c>"}
				{"M163"									"<c(FFFFFF)e(shadow)>M163 VADS</c>"}
				{"m163machbet"							"<c(FFFFFF)e(shadow)>Machbet</c>"}
				{"m2_adats"								"<c(FFFFFF)e(shadow)>ADATS</c>"}
				{"nasams_ii_launcher"					"<c(FFFFFF)e(shadow)>NASAMS 2</c>"}
				{"shorad"								"<c(FFFFFF)e(shadow)>M-SHORAD</c>"}
		;cannon_modern
			;bel
				{"shershen_d_stan"						"<c(FFFFFF)e(shadow)>Шершень-Д</c>"}
			;cn
				{"hj73_stan"							"<c(FFFFFF)e(shadow)>HJ-73</c>"}
				{"hj8_stan"								"<c(FFFFFF)e(shadow)>HJ-8</c>"}
				{"pbp-172"								"<c(FFFFFF)e(shadow)>PBP-172</c>"}
				{"pl-66"								"<c(FFFFFF)e(shadow)>PL-66</c>"}
				{"qjz-89_stan"							"<c(FFFFFF)e(shadow)>QJZ-89</c>"}
				{"qlz04"								"<c(FFFFFF)e(shadow)>QLZ-04</c>"}
				{"radar_bs903"							"<c(FFFFFF)e(shadow)>BS-903</c>"}
				{"tl-4_stan"							"<c(FFFFFF)e(shadow)>TL-4</c>"}
				{"type63_rocket2"						"<c(FFFFFF)e(shadow)>Type 63</c>"}
				{"type_pp87"							"<c(FFFFFF)e(shadow)>Type 87</c>"}
			;fr
				{"mistral_stan"							"<c(FFFFFF)e(shadow)>Mistral</c>"}
				{"mmp_stan"								"<c(FFFFFF)e(shadow)>MMP</c>"}
				{"mo_81_llr_f1"							"<c(FFFFFF)e(shadow)>MO-81 LLR F1</c>"}
				{"mortarfr"								"<c(FFFFFF)e(shadow)>MO-120 RT61</c>"}
			;gb
				;mstar_v6
					{"mstar_v6"							"<c(FFFFFF)e(shadow)>MSTAR v6</c>"}
					{"mstar_v6usa"						"<c(FFFFFF)e(shadow)>MSTAR v6</c>"}
				{"exactor_mk2"							"<c(FFFFFF)e(shadow)>Exactor Mk2</c>"}
				{"l118"									"<c(FFFFFF)e(shadow)>L118</c>"}
				{"l16_mortar"							"<c(FFFFFF)e(shadow)>L16</c>"}
				{"m2_stan"								"<c(FFFFFF)e(shadow)>Станковый M2HB</c>"}
			;ger
				;gmg_stan
					{"gmg_stan"							"<c(FFFFFF)e(shadow)>GMG</c>"}
					{"mg3_stan"							"<c(FFFFFF)e(shadow)>MG3</c>"}
				;spike_stan
					{"spike_stan"						"<c(FFFFFF)e(shadow)>SPIKE-ER</c>"}
					{"spike_stan_idf"					"<c(FFFFFF)e(shadow)>SPIKE-ER</c>"}
				{"fh-70"								"<c(FFFFFF)e(shadow)>FH-70</c>"}
				{"milan_stan"							"<c(FFFFFF)e(shadow)>MILAN</c>"}
				{"ptur_tow_nato"						"<c(FFFFFF)e(shadow)>BMG-71 TOW</c>"}
				{"tampella_120mm"						"<c(FFFFFF)e(shadow)>Krh-40 Tampella</c>"}
			;rus
				;d30
					{"d30"								"<c(FFFFFF)e(shadow)>Д-30А</c>"}
					{"pl-96"							"<c(FFFFFF)e(shadow)>PL-96</c>"}
				;psnr5
					{"psnr5"							"<c(FFFFFF)e(shadow)>ПНСР-5</c>"}
					{"psnr5m"							"<c(FFFFFF)e(shadow)>ПНСР-5М</c>"}
				;ur83p
					{"ur_83p"							"<c(FFFFFF)e(shadow)>УР-83П</c>"}
				{"2a65_msta_b"							"<c(FFFFFF)e(shadow)>2А65 Мста-Б</c>"}
				{"2b11"									"<c(FFFFFF)e(shadow)>2Б11 Сани</c>"}
				{"2b14_podnos"							"<c(FFFFFF)e(shadow)>2Б14 Поднос</c>"}
				{"ags17"								"<c(FFFFFF)e(shadow)>АГС-17</c>"}
				{"ags30_stan"							"<c(FFFFFF)e(shadow)>АГС-30</c>"}
				{"kord_stan"							"<c(FFFFFF)e(shadow)>КОРД</c>"}
				{"kornet_base_stan"						"<c(FFFFFF)e(shadow)>9П163М-1 Корнет-П</c>"}
				{"kornet_stan"							"<c(FFFFFF)e(shadow)>9П163М-2 Корнет-Д</c>"}
				{"malytka_stan"							"<c(FFFFFF)e(shadow)>9К14М Малютка-М</c>"}
				{"metis_m"								"<c(FFFFFF)e(shadow)>9К115-1 Метис-М</c>"}
				{"mt12_rapira"							"<c(FFFFFF)e(shadow)>МТ-12 Рапира</c>"}
				{"p-37"									"<c(FFFFFF)e(shadow)>П-37</c>"}
				{"pkm_stan"								"<c(FFFFFF)e(shadow)>ПКМ</c>"}
				{"ptur_konkurs"							"<c(FFFFFF)e(shadow)>9М113 Конкурс</c>"}
				{"spg_9"								"<c(FFFFFF)e(shadow)>СПГ-9М</c>"}
				{"vant_vm_shield"						"<c(FFFFFF)e(shadow)>Вант-ВМ</c>"}
				{"vasilek"								"<c(FFFFFF)e(shadow)>2Б9 Василек</c>"}
				{"ZU23-2"								"<c(FFFFFF)e(shadow)>ЗУ-23-2</c>"}
			;usa
				;patriot
					{"patriot_launcher"					"<c(FFFFFF)e(shadow)>MIM-104 Patriot M901</c>"}
					{"patriot_radar"					"<c(FFFFFF)e(shadow)>MIM-104 Patriot AN/MPQ-53</c>"}
				{"hawk_rls"								"<c(FFFFFF)e(shadow)>MIM-23 Hawk AN/MPQ-50 IPAR</c>"}
				{"hawk_cwar"							"<c(FFFFFF)e(shadow)>MIM-23 Hawk AN/MPQ-55 ICWAR</c>"}
				{"m119"									"<c(FFFFFF)e(shadow)>M119A1</c>"}
				{"m120"									"<c(FFFFFF)e(shadow)>M120</c>"}
				{"m252"									"<c(FFFFFF)e(shadow)>M252</c>"}
				{"mk19"									"<c(FFFFFF)e(shadow)>Mk19</c>"}
				{"ptur_tow"								"<c(FFFFFF)e(shadow)>BMG-71 TOW</c>"}
		;car_modern
			;cn
				;shaanxi_sx2190_ammo
					{"shaanxi_sx2190_ammo"				"<c(FFFFFF)e(shadow)>Боеприпасы общ. Shaanxi SX2190</c>"}
					{"shaanxi_sx2190_ammo_track"		"<c(FFFFFF)e(shadow)>Боеприпасы общ. Shaanxi SX2190</c>"}	;Only Single player
					{"shaanxi_sx2190_art_pvo"			"<c(FFFFFF)e(shadow)>Арт/ПВО боеприпасы Shaanxi SX2190</c>"}
					{"shaanxi_sx2190_avia"				"<c(FFFFFF)e(shadow)>Авиабоеприпасы Shaanxi SX2190</c>"}
				{"beijing_bj2022"						"<c(FFFFFF)e(shadow)>Beijing BJ2022</c>"}
				{"dongfeng__mengshi_sk131"				"<c(FFFFFF)e(shadow)>Dongfeng Mengshi CSK-131 ККП</c>"}
				{"dongfeng_mengshi_hj8"					"<c(FFFFFF)e(shadow)>Dongfeng Mengshi HJ-8 ПТУР</c>"} 
				{"hq-16b_launcher"						"<c(FFFFFF)e(shadow)>HQ-16B</c>"}
				{"hq-16b_radar"							"<c(FFFFFF)e(shadow)>HQ-16B IBIS 150</c>"}
				{"llq305_radar"							"<c(FFFFFF)e(shadow)>LLQ-305A</c>"}
				{"lyt2021"								"<c(FFFFFF)e(shadow)>LYT-2021</c>"}
				{"pcp001_cs_sm1"						"<c(FFFFFF)e(shadow)>PCP-001</c>"}
				{"shaanxi_sx2190_passenger"				"<c(FFFFFF)e(shadow)>Shaanxi SX2190</c>"}
				{"shaanxi_sx2190_repair"				"<c(FFFFFF)e(shadow)>Инженерный Shaanxi SX2190</c>"}
				{"shaanxi_sx2190_tanker"				"<c(FFFFFF)e(shadow)>Топливозаправщик Shaanxi SX2190</c>"}
			;ir
				{"shahed136_truck"						"<c(FFFFFF)e(shadow)>ПУ Shahed-136</c>"}					 
			;cz
				{"tatra_t810"							"<c(FFFFFF)e(shadow)>Tatra T810</c>"}
			;fr
				{"peugeot_p4"							"<c(FFFFFF)e(shadow)>Peugeot P4</c>"}
				{"renault_gbc_180"						"<c(FFFFFF)e(shadow)>Renault GBC 180</c>"}
				{"sampt_arabel"							"<c(FFFFFF)e(shadow)>SAMPT Arabel</c>"}
				{"sampt_mamba"							"<c(FFFFFF)e(shadow)>SAMPT Mamba</c>"}
			;gb
				;land_rover_truck
					{"land_rover_exactor"				"<c(FFFFFF)e(shadow)>Land Rover-Exactor</c>"}
					{"land_rover_snatch"				"<c(FFFFFF)e(shadow)>Land Rover Wolf</c>"}
				;land_rover_turret
					{"land_rover_atgm"					"<c(FFFFFF)e(shadow)>Land Rover MWIM ATGM</c>"}
					{"land_rover_mgun"					"<c(FFFFFF)e(shadow)>Land Rover MWIM HMG</c>"}
				;mwwmik_jackal2
					{"mwwik_jackal2_gmg"				"<c(FFFFFF)e(shadow)>Jackal 2 AGL</c>"}
					{"mwwik_jackal2_mgun"				"<c(FFFFFF)e(shadow)>Jackal 2 HMG</c>"}
				{"husky_tsv"							"<c(FFFFFF)e(shadow)>Husky TSV</c>"}
				{"man_sx44"								"<c(FFFFFF)e(shadow)>MAN SX44</c>"}
				{"pinzgauer_710m"						"<c(FFFFFF)e(shadow)>Pinzgauer 710m</c>"}
			;ger
				;dingo2a2
					{"dingo2a1"							"<c(FFFFFF)e(shadow)>ATF Dingo 2</c>"}
					{"dingo2a2"							"<c(FFFFFF)e(shadow)>ATF Dingo 2 FLW 200</c>"}
				{"dingo2a2_gun"							"<c(FFFFFF)e(shadow)>ATF Dingo 2A2</c>"}
				;man
					{"man_ammo"							"<c(FFFFFF)e(shadow)>Боеприпасы общ. MAN KAT1</c>"}
					{"man_art"							"<c(FFFFFF)e(shadow)>Арт/ПВО боеприпасы MAN KAT1</c>"}
					{"man_avia"							"<c(FFFFFF)e(shadow)>Авиабоеприпасы MAN KAT1</c>"}
					{"man_passenjer"					"<c(FFFFFF)e(shadow)>MAN KAT1</c>"}
					{"man_repair"						"<c(FFFFFF)e(shadow)>Инженерный MAN KAT1</c>"}
				{"kwm_ampv"								"<c(FFFFFF)e(shadow)>KWM AMPV</c>"}
				{"man_kat_10t"							"<c(FFFFFF)e(shadow)>MAN KAT 10T 8x8</c>"}
				{"man_tanker"							"<c(FFFFFF)e(shadow)>тТопливозаправщик MAN KAT1</c>"}
				{"roland"								"<c(FFFFFF)e(shadow)>Roland 3</c>"}
				{"wolf"									"<c(FFFFFF)e(shadow)>Mercedes-Benz G250D</c>"}
			;rus
				;gas66
					{"gaz66"							"<c(FFFFFF)e(shadow)>ГАЗ-66</c>"}
					{"gaz66_inf"						"<c(FFFFFF)e(shadow)>ГАЗ-66</c>"}
				;gaz_tiger
					{"gaz_tigr"							"<c(FFFFFF)e(shadow)>ГАЗ-233014 Тигр</c>"}
					{"gaz_tigr_mgun"					"<c(FFFFFF)e(shadow)>ГАЗ-233014 Тигр</c>"}
					{"gaz_tigr_mgun2"					"<c(FFFFFF)e(shadow)>ГАЗ-233014 Тигр</c>"}
				;pantsir
					{"pantsir_s"						"<c(FFFFFF)e(shadow)>Панцирь-С</c>"}
					{"pantsir_s1"						"<c(FFFFFF)e(shadow)>Панцирь-С1</c>"}
				;ural-4320_all
					{"ural-4320_fuel"					"<c(FFFFFF)e(shadow)>Топливозаправщик Урал-4320</c>"}
					{"ural-4320_kamaz_tent"				"<c(FFFFFF)e(shadow)>Урал-4320</c>"}
					{"ural-4320_kung"					"<c(FFFFFF)e(shadow)>Урал-4320 кунг</c>"}
					{"ural-4320_long_tent"				"<c(FFFFFF)e(shadow)>Урал-4320-31</c>"}
					{"ural-4320_long_tent2"				"<c(FFFFFF)e(shadow)>Урал-4320-31</c>"}
					{"ural-4320_long_zu23-2"			"<c(FFFFFF)e(shadow)>Урал-4320-31 Зу-23-2</c>"}
					{"ural-4320_tent2"					"<c(FFFFFF)e(shadow)>Урал-4320</c>"}
					{"ural-4320_tornado_g"				"<c(FFFFFF)e(shadow)>9К51М «Торнадо-Г»</c>"}
					{"ural-4320_tractor"				"<c(FFFFFF)e(shadow)>Урал-44202</c>"}
					{"ural375"							"<c(FFFFFF)e(shadow)>Урал-4320</c>"}
					{"ural375_inf"						"<c(FFFFFF)e(shadow)>Урал-4320</c>"}
					{"ural375_zu"						"<c(FFFFFF)e(shadow)>Урал-4320 Зу-23-2</c>"}
					{"ural_art"							"<c(FFFFFF)e(shadow)>Боеприпасы общ. Урал-4320</c>"}
					{"ural_art_pvo"						"<c(FFFFFF)e(shadow)>Арт/ПВО боеприпасы Урал-4320</c>"}
					{"ural_avia"						"<c(FFFFFF)e(shadow)>Авиабоеприпасы Урал-4320</c>"}
					{"ural_eng"							"<c(FFFFFF)e(shadow)>Инженерный Урал-4320</c>"}
					{"ural_grad"						"<c(FFFFFF)e(shadow)>9К51 «Град»</c>"}
					{"ural_umz"							"<c(FFFFFF)e(shadow)>Урал-4320 УМЗ</c>"}
				{"gaz66_zu"								"<c(FFFFFF)e(shadow)>ГАЗ-66 Зу-23-2</c>"}
				{"kamaz"								"<c(FFFFFF)e(shadow)>КамАЗ-43114</c>"}
				{"kamaz-4326"							"<c(FFFFFF)e(shadow)>КамАЗ-4326</c>"}
				{"kamaz-6350"							"<c(FFFFFF)e(shadow)>КамАЗ-6350</c>"}
				{"kamaz-r142nm"							"<c(FFFFFF)e(shadow)>Р-142НМ Деймос</c>"}
				{"kamaz_taifun"							"<c(FFFFFF)e(shadow)>КамАЗ-63968 Тайфун-К</c>"}
				{"kornet-d"								"<c(FFFFFF)e(shadow)>Корнет-Д</c>"}
				{"kraz255b1_pmp"						"<c(FFFFFF)e(shadow)>КрАЗ-255Б1 ПМП</c>"}
				{"maz7410"								"<c(FFFFFF)e(shadow)>МАЗ-7410</c>"}
				{"maz7410_pricep"						"<c(FFFFFF)e(shadow)>ЧМЗАП-5247Г</c>"}
				{"uaz2"									"<c(FFFFFF)e(shadow)>УАЗ-469 ПКМ</c>"}
				{"ural5323_pmp"							"<c(FFFFFF)e(shadow)>Урал-5323 ПМП</c>"}
			;usa
				;hemtt
					{"hemtt_refueller"					"<c(FFFFFF)e(shadow)>Топливозаправщик HEMTT M978A4</c>"}
					{"hemtt_tent"						"<c(FFFFFF)e(shadow)>HEMTT M977A4</c>"}
				;hmmwv_m998_tent
					{"hmmwv_m998"						"<c(FFFFFF)e(shadow)>HMMWV M998</c>"}
					{"hmmwv_m998_tent"					"<c(FFFFFF)e(shadow)>HMMWV M998</c>"}
				;hmmwv_turret
					{"hmmwv_for_single"					"<c(FFFFFF)e(shadow)>HMMWV M240B Пулем.</c>"}
					{"hmmwv_for_single_turret"			"<c(FFFFFF)e(shadow)>HMMWV M240B Пулем.</c>"}
					{"hmmwv_turret"						"<c(FFFFFF)e(shadow)>HMMWV M2HB ККП</c>"}
				;m939
					{"m939"								"<c(FFFFFF)e(shadow)>M939</c>"}
					{"m939_inf"							"<c(FFFFFF)e(shadow)>M939</c>"}
				;m939_art
					{"m939_art"							"<c(FFFFFF)e(shadow)>Боеприпасы общ. M939 </c>"}
					{"m939_art_pvo"						"<c(FFFFFF)e(shadow)>Арт/ПВО боеприпасы M939</c>"}
					{"m939_avia"						"<c(FFFFFF)e(shadow)>Авиабоеприпасы M939</c>"}
				;oshkosh_m-atv
					{"oshkosh_m-atv_m2"					"<c(FFFFFF)e(shadow)>Oshkosh M-ATV SF M2HB ККП</c>"}
					{"oshkosh_m-atv_m240"				"<c(FFFFFF)e(shadow)>Oshkosh M-ATV SF M240 Пулем.</c>"}
					{"oshkosh_m-atv_mk19"				"<c(FFFFFF)e(shadow)>Oshkosh M-ATV SF MK19 АГС</c>"}
				{"Hmmwv"								"<c(FFFFFF)e(shadow)>HMMWV M2HB ККП</c>"}
				{"hmmwv_m1035"							"<c(FFFFFF)e(shadow)>HMMWV M1035</c>"}
				{"Hmmwv_TOW"							"<c(FFFFFF)e(shadow)>Hummer M966 TOW</c>"}
				{"m939_eng"								"<c(FFFFFF)e(shadow)>Инженерный M939</c>"}
				{"m1097_avenger"						"<c(FFFFFF)e(shadow)>M1097 Avenger</c>"}
				{"mtvr_m2"								"<c(FFFFFF)e(shadow)>Oshkosh MTVR Mk27</c>"}
				{"oshkosh_m-atv"						"<c(FFFFFF)e(shadow)>Oshkosh M-ATV</c>"}
				{"oshkosh_mtvr_ammo_mk25"				"<c(FFFFFF)e(shadow)>Oshkosh MTVR MK.25</c>"}
				{"oshkosh_mtvr_cargo_mk25"				"<c(FFFFFF)e(shadow)>Oshkosh MTVR MK.25</c>"}
				{"oshkosh_mtvr_tanker_mk25"				"<c(FFFFFF)e(shadow)>Oshkosh MTVR MK.25 CST</c>"}
				{"patriot_truck"						"<c(FFFFFF)e(shadow)>MAN KAT1</c>"}
		;car_other
			;uaz_car
				{"UAZ_car"								"<c(FFFFFF)e(shadow)>УАЗ-469</c>"}
				{"UAZ_car_konkurs"						"<c(FFFFFF)e(shadow)>УАЗ-469</c>"}
			{"chevrolet_bel_air"						"<c(FFFFFF)e(shadow)>Plymouth Savoy 1957</c>"}
			{"chevy_s10"								"<c(FFFFFF)e(shadow)>Chevrolet C10</c>"}
			{"dodje"									"<c(FFFFFF)e(shadow)>Dodge Charger 2010</c>"}
			{"dodje_police"								"<c(FFFFFF)e(shadow)>Dodge Charger 2010</c>"}
			{"fire_department"							"<c(FFFFFF)e(shadow)>2011 Pierce Impel</c>"}
			{"ford_f150"								"<c(FFFFFF)e(shadow)>Ford F-350 2008"}
			{"furgon"									"<c(FFFFFF)e(shadow)>GMC Dura 1995"}
			{"furgon_swat"								"<c(FFFFFF)e(shadow)>GMC Dura 1995"}
			{"gaz_24"									"<c(FFFFFF)e(shadow)>ГАЗ-24</c>"}
			{"labolatory_pricep"						"<c(FFFFFF)e(shadow)>Трейлер"}
			{"motorcycle"								"<c(FFFFFF)e(shadow)>Honda XLX 250"}
			{"mtz_80"									"<c(FFFFFF)e(shadow)>МТЗ-80</c>"}
			{"prado"									"<c(FFFFFF)e(shadow)>Toyota Land Cruiser Prado 150</c>"}
			{"toyota_hilux"								"<c(FFFFFF)e(shadow)>Toyota Hilux</c>"}
			{"toyota_hilux_ammo"						"<c(FFFFFF)e(shadow)>Toyota Hilux боеприпасы</c>"}
			{"toyota_hilux_dshkm"						"<c(FFFFFF)e(shadow)>Toyota Hilux с ДШКМ</c>"}
			{"toyota_hilux_spg9"						"<c(FFFFFF)e(shadow)>Toyota Hilux с СПГ-9</c>"}
			{"toyota_hilux_transport"					"<c(FFFFFF)e(shadow)>Toyota Hilux</c>"}
			{"tractor_fiat25"							"<c(FFFFFF)e(shadow)>FIAT 25</c>"}
			{"uaz_van"									"<c(FFFFFF)e(shadow)>УАЗ-452</c>"}
			{"vaz_2106"									"<c(FFFFFF)e(shadow)>ВАЗ-2106</c>"}
			{"volkswagen_beetle"						"<c(FFFFFF)e(shadow)>VW Beetle</c>"}
		;marine_modern
			;rus
				;bpk1155
					{"bpk1155_harlamov"					"<c(FFFFFF)e(shadow)>Адмирал Харламов - 678</c>"}
					{"bpk1155_levchenko"				"<c(FFFFFF)e(shadow)>Адмирал Левченко  - 605</c>"}
					{"bpk1155_panteleev"				"<c(FFFFFF)e(shadow)>Адмирал Пантелеев  - 548</c>"}
					{"bpk1155_severomorsk"				"<c(FFFFFF)e(shadow)>Североморск - 619</c>"}
					{"bpk1155_tribuc"					"<c(FFFFFF)e(shadow)>Адмирал Трибуц - 564</c>"}
					{"bpk1155_vinogradov"				"<c(FFFFFF)e(shadow)>Алмирал Виноградов - 572</c>"}
				;linked_entities
					;ak630
						{"ak630"						"<c(FFFFFF)e(shadow)>АК-630</c>"}
						{"ak630_side"					"<c(FFFFFF)e(shadow)>АК-630</c>"}
					;torpedotube_rus_x2
						{"torpedotube_rus_x2_left"		"<c(FFFFFF)e(shadow)>ДТА-53-956</c>"}
						{"torpedotube_rus_x2_right"		"<c(FFFFFF)e(shadow)>ДТА-53-956</c>"}
					;torpedotube_rus_x4
						{"torpedotube_rus_x4_left"		"<c(FFFFFF)e(shadow)>ЧТА-53-1155</c>"}
						{"torpedotube_rus_x4_right"		"<c(FFFFFF)e(shadow)>ЧТА-53-1155</c>"}
					;torpedotube_rus_x5
						{"torpedotube_rus_x5_left"		"<c(FFFFFF)e(shadow)>ПТА-53-1134</c>"}
						{"torpedotube_rus_x5_right"		"<c(FFFFFF)e(shadow)>ПТА-53-1134</c>"}
					{"a22_ogon"							"<c(FFFFFF)e(shadow)>А-22 Огонь</c>"}
					{"ak100_maingun"					"<c(FFFFFF)e(shadow)>АК-100</c>"}
					{"ak130_maingun"					"<c(FFFFFF)e(shadow)>АК-130</c>"}
					{"ak176"							"<c(FFFFFF)e(shadow)>АК-176</c>"}
					{"ak630_rls"						"<c(FFFFFF)e(shadow)>МР-123/176 Вымпел</c>"}
					{"ak630_rls_1"						"<c(FFFFFF)e(shadow)>МР-123-02/МР-123-03 Вымпел-АМ</c>"}
					{"basalt_pu"						"<c(FFFFFF)e(shadow)>П-500 Базальт</c>"}
					{"flag_rls"							"<c(FFFFFF)e(shadow)>МР-800 Флаг</c>"}
					{"fort_m_rls"						"<c(FFFFFF)e(shadow)>30N6E2</c>"}
					{"fort_rls"							"<c(FFFFFF)e(shadow)>Волна 3Р41</c>"}
					{"fregat710"						"<c(FFFFFF)e(shadow)>МР-710М Фрегат</c>"}
					{"fregat710m1"						"<c(FFFFFF)e(shadow)>МР-710М1 Фрегат</c>"}
					{"fregat750"						"<c(FFFFFF)e(shadow)>МР-750 Фрегат-М</c>"}
					{"granit1144_pu"					"<c(FFFFFF)e(shadow)>П-700 Гранит</c>"}
					{"kinjal_1144"						"<c(FFFFFF)e(shadow)>3К95 Кинжал</c>"}
					{"kinjal_1155back"					"<c(FFFFFF)e(shadow)>3К95 Кинжал</c>"}
					{"kinjal_1155front"					"<c(FFFFFF)e(shadow)>3К95 Кинжал</c>"}
					{"kinjal_rls"						"<c(FFFFFF)e(shadow)>3Р95 Кинжал</c>"}
					{"kortik"							"<c(FFFFFF)e(shadow)>3М87 Кортик</c>"}
					{"lev_rls"							"<c(FFFFFF)e(shadow)>МР-184 Лев</c>"}
					{"malahit_pu"						"<c(FFFFFF)e(shadow)>П-120 Малахит</c>"}
					{"moskit_pu"						"<c(FFFFFF)e(shadow)>П-270 Москит</c>"}
					{"osa_ma_pu"						"<c(FFFFFF)e(shadow)>ЗИФ-122 Оса-М</c>"}
					{"osa_am_rls"						"<c(FFFFFF)e(shadow)>М-4 Оса-МА</c>"}
					{"podberezovik_rls"					"<c(FFFFFF)e(shadow)>Подберезовик-ЭТ1</c>"}
					{"podkat_rls"						"<c(FFFFFF)e(shadow)>МР-350 Подкат</c>"}
					{"rastrub_pu"						"<c(FFFFFF)e(shadow)>УРК-5 Раструб-Б</c>"}
					{"rbu1000"							"<c(FFFFFF)e(shadow)>РБУ-1000 Смерч-3</c>"}
					{"rbu12000"							"<c(FFFFFF)e(shadow)>РБУ-12000 Удав-1</c>"}
					{"rbu6000"							"<c(FFFFFF)e(shadow)>РБУ-6000 Смерч-2</c>"}
					{"s300f_1144"						"<c(FFFFFF)e(shadow)>ЗС-97.2ФЕ</c>"}
					{"s300f_1164"						"<c(FFFFFF)e(shadow)>3С-48Е</c>"}
					{"uragan_pu"						"<c(FFFFFF)e(shadow)>3С90 Ураган</c>"}
					{"uragan_rls"						"<c(FFFFFF)e(shadow)>3Р90/МР-90 Орех</c>"}
				;orlan
					{"orlan_body1"						"<c(FFFFFF)e(shadow)>Петр Великий - 099</c>"}
					{"orlan_body2"						"<c(FFFFFF)e(shadow)>Петр Великий - 99</c>"}
					{"orlan_body3"						"<c(FFFFFF)e(shadow)>Петр Великий - 99</c>"}
					{"orlan_body4"						"<c(FFFFFF)e(shadow)>Петр Великий - 99</c>"}
					{"orlan_main"						"<c(FFFFFF)e(shadow)>Петр Великий - 99</c>"}
				;pr1164
					{"pr1164_moskva"					"<c(FFFFFF)e(shadow)>Москва - 121</c>"}
					{"pr1164_ustinov"					"<c(FFFFFF)e(shadow)>Устинов - 055</c>"}
					{"pr1164_varyag"					"<c(FFFFFF)e(shadow)>Варяг - 011</c>"}
				;pr1234_ovod
					{"pr1234_ovod"						"<c(FFFFFF)e(shadow)>Малый ракетный корабль проекта 1234.1 Овод</c>"}
				;zubr
					{"zubr"								"<c(FFFFFF)e(shadow)>Зубр</c>"}
				{"636_3varshavyanka"					"<c(FFFFFF)e(shadow)>Варшавянка</c>"}
				{"boat338m"								"<c(FFFFFF)e(shadow)>Бычок</c>"}
				{"boat1390"								"<c(FFFFFF)e(shadow)>Стриж</c>"}
				{"boat1402"								"<c(FFFFFF)e(shadow)>Бекас</c>"}
				{"boat1404"								"<c(FFFFFF)e(shadow)>Соколёнок</c>"}
				{"pr949a"								"<c(FFFFFF)e(shadow)>Антей</c>"}
				{"pr956"								"<c(FFFFFF)e(shadow)>Сарыч</c>"}
			;usa
				;arly_burke
					;arly_burke
						{"arley_burke"					"<c(FFFFFF)e(shadow)>Arleigh Burke</c>"}
						{"arley_burke_a2"				"<c(FFFFFF)e(shadow)>Arleigh Burke</c>"}
						{"arley_burke_laser"			"<c(FFFFFF)e(shadow)>Arleigh Burke</c>"}
						{"arley_burke_with_land"		"<c(FFFFFF)e(shadow)>Arleigh Burke</c>"}
					;weaponry
						{"laws"							"<c(FFFFFF)e(shadow)>AN/SEQ-3 LaWS</c>"}
						{"mk32_left"					"<c(FFFFFF)e(shadow)>Mark 32</c>"}
						{"mk32_right"					"<c(FFFFFF)e(shadow)>Mark 32</c>"}
						{"mk38_mod2"					"<c(FFFFFF)e(shadow)>Mk 38 Mod 2</c>"}
						{"mk41_32"						"<c(FFFFFF)e(shadow)>Mk41 VLS</c>"}
						{"mk41_64"						"<c(FFFFFF)e(shadow)>Mk41 VLS</c>"}
						{"mk45"							"<c(FFFFFF)e(shadow)>Mark 45 mod 4</c>"}
						{"naval_browning"				"<c(FFFFFF)e(shadow)>Спаренный М2НВ</c>"}
						{"spg62_radar"					"<c(FFFFFF)e(shadow)>AN/SPG-62</c>"}
				;linked_entities
					{"carrier_cst"						"<c(FFFFFF)e(shadow)>A/S-32-31A Mule</c>"}
					{"carrier_lifter"					"<c(FFFFFF)e(shadow)>HYSTER 3.0</c>"}
				;nimitz
					;nimitz_body3
						{"nimitz_body3"					"<c(FFFFFF)e(shadow)>USS Nimitz-class</c>"}
						{"nimitz_body3_cvn68"			"<c(FFFFFF)e(shadow)>USS Nimitz (CVN-68)</c>"}
						{"nimitz_body3_cvn69"			"<c(FFFFFF)e(shadow)>USS Dwight D. Eisenhower (CVN-69)</c>"}
						{"nimitz_body3_cvn73"			"<c(FFFFFF)e(shadow)>USS George Washington (CVN-73)</c>"}
						{"nimitz_body3_cvn75"			"<c(FFFFFF)e(shadow)>USS Harry S. Truman (CVN-75)</c>"}
					;nimitz_body4
						{"nimitz_body4"					"<c(FFFFFF)e(shadow)>USS Nimitz-class</c>"}
						{"nimitz_body4_cvn68"			"<c(FFFFFF)e(shadow)>USS Nimitz (CVN-68)</c>"}
						{"nimitz_body4_cvn69"			"<c(FFFFFF)e(shadow)>USS Dwight D. Eisenhower (CVN-69)</c>"}
						{"nimitz_body4_cvn73"			"<c(FFFFFF)e(shadow)>USS George Washington (CVN-73)</c>"}
						{"nimitz_body4_cvn75"			"<c(FFFFFF)e(shadow)>USS Harry S. Truman (CVN-75)</c>"}
					;nimitz_main
						{"nimitz_main"					"<c(FFFFFF)e(shadow)>USS Nimitz-class</c>"}
						{"nimitz_main_cvn68"			"<c(FFFFFF)e(shadow)>USS Nimitz (CVN-68)</c>"}
						{"nimitz_main_cvn69"			"<c(FFFFFF)e(shadow)>USS Dwight D. Eisenhower (CVN-69)</c>"}
						{"nimitz_main_cvn73"			"<c(FFFFFF)e(shadow)>USS George Washington (CVN-73)</c>"}
						{"nimitz_main_cvn75"			"<c(FFFFFF)e(shadow)>USS Harry S. Truman (CVN-75)</c>"}
					{"nimitz_body"						"<c(FFFFFF)e(shadow)>USS Nimitz-class</c>"}
					{"nimitz_body1"						"<c(FFFFFF)e(shadow)>USS Nimitz-class</c>"}
					;weaponry
						{"mk95_radar"					"<c(FFFFFF)e(shadow)>Mk95 НВ-радар</c>"}
						{"phalanx"						"<c(FFFFFF)e(shadow)>Mk15 Phalanx CIWS</c>"}
						{"sea_sparrow"					"<c(FFFFFF)e(shadow)>RIM-7 Sea Sparrow</c>"}
						{"searam"						"<c(FFFFFF)e(shadow)>SeaRAM</c>"}
				{"boat_rhib"							"<c(FFFFFF)e(shadow)>RHIB «Morena»</c>"}
				{"lcac"									"<c(FFFFFF)e(shadow)>LCAC</c>"}
				{"los_angeles"							"<c(FFFFFF)e(shadow)>USS Cheyenne (SSN-773)</c>"}
		;missile_modern
			;aim-9l
				{"aim-9l"								"<c(FFFFFF)e(shadow)>AIM-9L Sidewinder</c>"}
				{"aim-9l_ammo"							"<c(FFFFFF)e(shadow)>AIM-9L Sidewinder</c>"}
				{"aim-9l_impactor"						"<c(FFFFFF)e(shadow)>AIM-9L Sidewinder</c>"}
			;service_stuff
				{"rus_las_designator"					"<c(FFFFFF)e(shadow)>1Д26 Атолл</c>"}
			{"48n6e2"									"<c(FFFFFF)e(shadow)>48Н6Е2</c>"}
			{"maverick"									"<c(FFFFFF)e(shadow)>AGM-65 Maverick</c>"}
			{"x-25ml"									"<c(FFFFFF)e(shadow)>Х-25МЛ изд. 713</c>"}
		;proj_2
			;atgm_carrier
				{"lancet3m_cm_carrier"					"<c(FFFFFF)e(shadow)>Ланцет-3М - Кум.</c>"}
				{"lancet3m_fg_carrier"					"<c(FFFFFF)e(shadow)>Ланцет-3М - ОФ</c>"}
				{"mmp_missile_carrier"					"<c(FFFFFF)e(shadow)>MMP</c>"}
				{"red_arrow_10b_carrier"				"<c(FFFFFF)e(shadow)>HJ-10</c>"}
				{"Spike-er2_carrier"					"<c(FFFFFF)e(shadow)>Spike ER2</c>"}
				{"spike-er_carrier"						"<c(FFFFFF)e(shadow)>Spike ER</c>"}
				{"spike-lr_carrier"						"<c(FFFFFF)e(shadow)>Spike LR</c>"}
				{"spike_nlos_carrier"					"<c(FFFFFF)e(shadow)>Spike NLOS - Кум.</c>"}
				{"spike_nlos_fg_carrier"				"<c(FFFFFF)e(shadow)>Spike NLOS - ОФ</c>"}
				{"switchblade300_carrier"				"<c(FFFFFF)e(shadow)>Switchblade 300</c>"}
				{"shahed136_base_carrier"				"<c(FFFFFF)e(shadow)>Shahed-136</c>"}
			;sam_carrier
				{"x59m_carrier"							"<c(FFFFFF)e(shadow)>Х-59М Овод-М  изд. Д-9М</c>"}
		;tank_modern
			;cn
				{"ztz-96a"								"<c(FFFFFF)e(shadow)>ZTZ-96A</c>"}
				{"ztz-99a"								"<c(FFFFFF)e(shadow)>ZTZ-99A</c>"}
				{"ztz_99_phase_2"						"<c(FFFFFF)e(shadow)>ZTZ-99 Phase-II</c>"}
			;fr
				;lecrerc
					{"leclerc"							"<c(FFFFFF)e(shadow)>Leclerc</c>"}
					{"leclerc_azur"						"<c(FFFFFF)e(shadow)>Leclerc Renove XLR</c>"}
			;gb
				;challenger_2
					{"challenger_2"						"<c(FFFFFF)e(shadow)>Challenger 2</c>"}
					{"challenger_2_applique"			"<c(FFFFFF)e(shadow)>Challenger 2 TES Megatron</c>"}
			;gr
				;leopard_1a4_c1
					{"leopard_1a4"						"<c(FFFFFF)e(shadow)>Leopard 1A4</c>"}
					{"leopard_1a5"						"<c(FFFFFF)e(shadow)>Leopard 1A5</c>"}
					{"leopard_c1"						"<c(FFFFFF)e(shadow)>Leopard C1</c>"}
				;leopard_2a0_2a4
					{"leopard_2a0"						"<c(FFFFFF)e(shadow)>Leopard 2</c>"}
					{"leopard_2a4"						"<c(FFFFFF)e(shadow)>Leopard 2A4</c>"}
				;leopard_2a5_2a6
					{"leopard_2a5"						"<c(FFFFFF)e(shadow)>Leopard 2A5</c>"}
					{"leopard_2a6"						"<c(FFFFFF)e(shadow)>Leopard 2A6M</c>"}
				;leopard_2a7plus
					{"leopard_2a7plus"					"<c(FFFFFF)e(shadow)>Leopard 2A7+</c>"}
					{"leopard_2a7plus_gmg"				"<c(FFFFFF)e(shadow)>Leopard 2A7+</c>"}
				{"gepard"								"<c(FFFFFF)e(shadow)>Flakpanzer Gepard</c>"}
			;idf
				;merkava_mk4
					{"merkava_mk4"						"<c(FFFFFF)e(shadow)>Merkava Mk4</c>"}
					{"merkava_trophy"					"<c(FFFFFF)e(shadow)>Merkava Mk4M Windbreaker</c>"}	
				{"magach7"								"<c(FFFFFF)e(shadow)>Magach 7C</c>"}
				{"namer"								"<c(FFFFFF)e(shadow)>Namer</c>"}
			;nato
				{"pt-91"								"<c(FFFFFF)e(shadow)>PT-91 Twardy</c>"}
				{"t72m4cz"								"<c(FFFFFF)e(shadow)>T-72M4CZ</c>"}
		;tank_modern
			;rus
				;buk_m1
					{"buk_m1"							"<c(FFFFFF)e(shadow)>9К7М1-2 Бук-М1-2</c>"}
					{"buk_m2"							"<c(FFFFFF)e(shadow)>9К317 Бук-М2</c>"}
				;pak_t72_new
					;t72(era_k5)_all
						{"t72b3"						"<c(FFFFFF)e(shadow)>T-72Б3 обр.2011</c>"}
						{"t72b3_single"					"<c(FFFFFF)e(shadow)>T-72Б3 обр.2011</c>"}
						{"t72b_1989year"				"<c(FFFFFF)e(shadow)>T-72Б обр.1989</c>"}
						{"t72ba"						"<c(FFFFFF)e(shadow)>T-72БА обр.2003</c>"}
					;t72a_all
						{"t72_yral"						"<c(FFFFFF)e(shadow)>T-72 Урал</c>"}
						{"t72a"							"<c(FFFFFF)e(shadow)>T-72A обр.1982</c>"}
						{"t72m1"						"<c(FFFFFF)e(shadow)>T-72M1 обр.1982</c>"}
						{"t72m_siriya"					"<c(FFFFFF)e(shadow)>T-72M обр.1980</c>"}
					;t72b3_2017
						{"t72b3_2017"					"<c(FFFFFF)e(shadow)>T-72Б3 обр.2016</c>"}
						{"t72b3_2017_2"					"<c(FFFFFF)e(shadow)>T-72Б3 обр.2016</c>"}
					;t72b_all
						{"t72a_1984year"				"<c(FFFFFF)e(shadow)>T-72A обр.1984</c>"}
						{"t72b"							"<c(FFFFFF)e(shadow)>T-72Б обр.1985</c>"}
						{"t72b1"						"<c(FFFFFF)e(shadow)>T-72Б1 обр.1985</c>"}
						{"t72b_single"					"<c(FFFFFF)e(shadow)>T-72Б обр.1985</c>"}
					{"t72av"							"<c(FFFFFF)e(shadow)>T-72AВ обр.1985</c>"}
					{"t72b3_gorod_komplect"				"<c(FFFFFF)e(shadow)>T-72Б3 Город</c>"}
				;pak_t80
					;t80b_all
						{"t80b"							"<c(FFFFFF)e(shadow)>Т-80Б обр. 1982</c>"}
						{"t80b_2"						"<c(FFFFFF)e(shadow)>Т-80Б обр. 1984</c>"}
						{"t80bv"						"<c(FFFFFF)e(shadow)>Т-80БВ обр. 1984</c>"}
						{"t80bv_2"						"<c(FFFFFF)e(shadow)>Т-80БВ обр. 1985</c>"}
						{"t80bvm"						"<c(FFFFFF)e(shadow)>Т-80БВМ</c>"}
						{"t80bvm_2"						"<c(FFFFFF)e(shadow)>Т-80БВМ</c>"}
					;t80y_all
						{"t80y"							"<c(FFFFFF)e(shadow)>Т-80У обр.1986</c>"}
						{"t80y_2"						"<c(FFFFFF)e(shadow)>Т-80У обр.1990</c>"}
						{"t80ye-1"						"<c(FFFFFF)e(shadow)>Т-80УЕ-1</c>"}
						{"t80yk"						"<c(FFFFFF)e(shadow)>Т-80УК</c>"}
						{"t80ym1"						"<c(FFFFFF)e(shadow)>Т-80УМ1 Барс</c>"}
				;shilka
					{"Shilka"							"<c(FFFFFF)e(shadow)>ЗСУ-23-4М3</c>"}
					{"Shilka_nato"						"<c(FFFFFF)e(shadow)>ZSU-23-4</c>"}
				;t15
					{"t-15"								"<c(FFFFFF)e(shadow)>Т-15 Барбарис </c>"}
					{"t-15_au220"						"<c(FFFFFF)e(shadow)>T-15 Кинжал</c>"}
				;t62_cw
					{"t62_cw"							"<c(FFFFFF)e(shadow)>T-62 обр.1972</c>"}
					{"t62m"								"<c(FFFFFF)e(shadow)>T-62М обр.1983</c>"}
					{"t62m_v2"							"<c(FFFFFF)e(shadow)>T-62М обр.1983</c>"}
					{"t62md"							"<c(FFFFFF)e(shadow)>T-62МД</c>"}
				;t90sm
					{"t90sm"							"<c(FFFFFF)e(shadow)>T-90CМ Тагил - (ПКМТ)</c>"}
					{"t90sm_zpy12"						"<c(FFFFFF)e(shadow)>T-90CМ Тагил (НСВТ)</c>"}
				{"9s18_kupol"							"<c(FFFFFF)e(shadow)>9C18 Купол</c>"}
				{"bmpt"									"<c(FFFFFF)e(shadow)>БМПТ</c>"}
				{"bmr-3"								"<c(FFFFFF)e(shadow)>БМР-3М Вепрь</c>"}
				{"t-14"									"<c(FFFFFF)e(shadow)>T-14 Армата</c>"}
				{"t-55"									"<c(FFFFFF)e(shadow)>T-55А</c>"}
				{"t-90a"								"<c(FFFFFF)e(shadow)>T-90А Владимир</c>"}
				{"t34-85_cw"							"<c(FFFFFF)e(shadow)>T-34-85</c>"}
				{"t64"									"<c(FFFFFF)e(shadow)>T-64А обр.1971</c>"}
				{"tor_m1"								"<c(FFFFFF)e(shadow)>9К331 Тор-М1</c>"}
				{"tor_m1_cn"							"<c(FFFFFF)e(shadow)>9К331 Тор-М1 (Китай)</c>"}
				{"tor_m2"								"<c(FFFFFF)e(shadow)>9К332 Тор-М2</c>"}
				{"tor_m2_early"							"<c(FFFFFF)e(shadow)>9К331М Тор-М2 ранний</c>"}
				{"tunguska"								"<c(FFFFFF)e(shadow)>2С6 Тунгуска</c>"}
			;ukr
				{"bm_oplot"								"<c(FFFFFF)e(shadow)>БМ Оплот</c>"}
				{"t-64b"								"<c(FFFFFF)e(shadow)>T-64Б Сосна обр.1980</c>"}
				{"t-64bv"								"<c(FFFFFF)e(shadow)>T-64БВ Скиф</c>"}
				{"t-64bm1"								"<c(FFFFFF)e(shadow)>T-64БМ1 Булат</c>"}
				{"t-64bm2"								"<c(FFFFFF)e(shadow)>T-64БМ2 Булат</c>"}
			;usa
				;m1a1_all_model
					{"m1a1_FEP"							"<c(FFFFFF)e(shadow)>M1A1 FEP</c>"}
					{"m1a1_new"							"<c(FFFFFF)e(shadow)>M1A1HA</c>"}
					{"m1a2_sep"							"<c(FFFFFF)e(shadow)>M1A2B</c>"}
					{"m1a2sep3"							"<c(FFFFFF)e(shadow)>M1A2C</c>"}
					{"m1ip_1"							"<c(FFFFFF)e(shadow)>M1 IPM1 1984</c>"}
					{"m1ip_2"							"<c(FFFFFF)e(shadow)>M1 IPM1 1984</c>"}
				;m1a1tusk_2_new
					{"m1a2tusk_2_new"					"<c(FFFFFF)e(shadow)>M1A2A TUSK II</c>"}
					{"m1a2tusk_2_m2_new"				"<c(FFFFFF)e(shadow)>M1A2A TUSK</c>"}
				{"M1_Abrams"							"<c(FFFFFF)e(shadow)>M1 Abrams</c>"}
				{"m1a2tusk"								"<c(FFFFFF)e(shadow)>M1A2A TUSK</c>"}
				{"m60a3"								"<c(FFFFFF)e(shadow)>M60A3</c>"}
		;train_modern
			{"2te10"									"<c(FFFFFF)e(shadow)>2ТЕ10</c>"}
			{"locomote_tgmz_1010"						"<c(FFFFFF)e(shadow)>ТГМЗ 1010</c>"}
	;cannon
		{"browning_m2hb_stan"							"<c(FFFFFF)e(shadow)>Browning M2HB</c>"}
		{"browning_m2hb_stan_nato"						"<c(FFFFFF)e(shadow)>Browning M2HB</c>"}
		{"kpvt"											"<c(FFFFFF)e(shadow)>КПВТ</c>"}
;new_entities
	;-supply_crates
		;for_mp
			{"supply_nato_pvo_aviation"					"<c(FFFFFF)e(shadow)>Aвиабоеприпасы</c>"}
			{"supply_rus_art_eng"						"<c(FFFFFF)e(shadow)>Топливо и Арт/ПВО боеприпасы</c>"}
			{"supply_rus_bmp_btr_tanks"					"<c(FFFFFF)e(shadow)>Боеприпасы бронетехники</c>"}
			{"supply_rus_light_weap"					"<c(FFFFFF)e(shadow)>Боеприпасы</c>"}
			{"supply_rus_pvo_aviation"					"<c(FFFFFF)e(shadow)>Aвиабоеприпасы</c>"}	
			{"supply_usa_art_eng"						"<c(FFFFFF)e(shadow)>Боеприпасы Арт/ПВО</c>"}			
			{"supply_usa_bmp_btr_tanks"					"<c(FFFFFF)e(shadow)>Боеприпасы бронетехники</c>"}
			{"supply_usa_light_weap"					"<c(FFFFFF)e(shadow)>Боеприпасы</c>"}
			{"supply_usa_pvo_aviation"					"<c(FFFFFF)e(shadow)>Aвиабоеприпасы</c>"}
;service
	;for_mp
		;mp_flag
			{"abn_mp_flag"								"<c(FFFFFF)e(shadow)>Полевая артиллерия НАТО</c>"}
			{"armbr_mp_flag"							"<c(FFFFFF)e(shadow)>Танковая бригада</c>"}
			{"artbr_mp_flag"							"<c(FFFFFF)e(shadow)>Артбригада</c>"}
			{"bund_mp_flag"								"<c(FFFFFF)e(shadow)>Бундесвер</c>"}
			{"cbn_mp_flag"								"<c(FFFFFF)e(shadow)>Сводный контингент экспедиционных сил</c>"}
			{"chi_dummy_flag"							"<c(FFFFFF)e(shadow)>Кита́йская Наро́дная Респу́блика</c>"}
			{"cnair_mp_flag"							"<c(FFFFFF)e(shadow)>Авиационная бригада</c>"}
			{"cnart_mp_flag"							"<c(FFFFFF)e(shadow)>Артбригада</c>"}
			{"cnheavy_mp_flag"							"<c(FFFFFF)e(shadow)>Тяжелая бригада</c>"}
			{"cnmed_mp_flag"							"<c(FFFFFF)e(shadow)>Средняя бригада</c>"}
			{"cnsam_mp_flag"							"<c(FFFFFF)e(shadow)>Бригада ПВО</c>"}
			{"cnsco_mp_flag"							"<c(FFFFFF)e(shadow)>Сводный контингент ШОС</c>"}
			{"fra_mp_flag"								"<c(FFFFFF)e(shadow)>Вооружённые силы Франции</c>"}
			{"gb_mp_flag"								"<c(FFFFFF)e(shadow)>Вооруженные силы Его Величества</c>"}
			{"idf_mp_flag"								"<c(FFFFFF)e(shadow)>Цахал (АОИ)</c>"}
			{"mot_mp_flag"								"<c(FFFFFF)e(shadow)>Мотострелковая бригада</c>"}
			{"nato_aa_mp_flag"							"<c(FFFFFF)e(shadow)>Противовоздушная и противоракетная оборона НАТО</c>"}
			{"nato_dummy_flag"							"<c(FFFFFF)e(shadow)>НАТО</c>"}
			{"nrf_mp_flag"								"<c(FFFFFF)e(shadow)>Воздушное командование союзников НАТО</c>"}
			{"pvo_mp_flag"								"<c(FFFFFF)e(shadow)>Бригада ПВО</c>"}
			{"rus_dummy_flag"							"<c(FFFFFF)e(shadow)>Российская Федерация</c>"}
			{"specbr_mp_flag"							"<c(FFFFFF)e(shadow)>Бригада морской пехоты</c>"}
			{"usa_aa_mp_flag"							"<c(FFFFFF)e(shadow)>Командование воздушно-космической обороны США</c>"}
			{"usa_dummy_flag"							"<c(FFFFFF)e(shadow)>США</c>"}
			{"usaf_mp_flag"								"<c(FFFFFF)e(shadow)>ВВС США (USAF)</c>"}
			{"usarmy_mp_flag"							"<c(FFFFFF)e(shadow)>Армия США</c>"}
			{"usart_mp_flag"							"<c(FFFFFF)e(shadow)>Отделение полевой артиллерии армии США</c>"}
			{"usmc_mp_flag"								"<c(FFFFFF)e(shadow)>Корпус морской пехоты США (USMC)</c>"}
			{"vdv_mp_flag"								"<c(FFFFFF)e(shadow)>Бригада ВДВ</c>"}
			{"vvs_mp_flag"								"<c(FFFFFF)e(shadow)>Бригада ВКС</c>"}
		;persistent_marker
			{"persistent_marker_cn"						"<c(FFFFFF)e(shadow)>Положение цели</c>"}
			{"persistent_marker_nato"					"<c(FFFFFF)e(shadow)>Положение цели</c>"}
			{"persistent_marker_rus"					"<c(FFFFFF)e(shadow)>Положение цели</c>"}
			{"persistent_marker_usa"					"<c(FFFFFF)e(shadow)>Положение цели</c>"}
;vehicle+infantry
	;cn
		{"pzrk2_cn"										"<c(FFFFFF)e(shadow)><e(shadow)>Мобильный отряд ПЗРК</c>"}
	;nato
		{"pzrk2_nato"									"<c(FFFFFF)e(shadow)><e(shadow)>Мобильный отряд ПЗРК</c>"}
	;rus
		{"pzrk2_rus"									"<c(FFFFFF)e(shadow)><e(shadow)>Мобильный отряд ПЗРК</c>"}
	;usa
		{"pzrk2_usa"									"<c(FFFFFF)e(shadow)><e(shadow)>Мобильный отряд ПЗРК</c>"}
;AS2
	;faunua
		{"chiken"										"<c(FFFFFF)e(shadow)>Курица</c>"}
		{"cow"											"<c(FFFFFF)e(shadow)>Корова</c>"}
		{"horse"										"<c(FFFFFF)e(shadow)>Лошадь</c>"}
		{"horse_bones"									"<c(FFFFFF)e(shadow)>Лошадь</c>"}
;CTA
	;cta_entities
		;fanua
			{"carp"										"<c(FFFFFF)e(shadow)>Карп</c>"}
			{"crab"										"<c(FFFFFF)e(shadow)>Краб</c>"}
			{"dog"										"<c(FFFFFF)e(shadow)>Собака</c>"}
			{"fish"										"<c(FFFFFF)e(shadow)>Рыба</c>"}
			{"goat"										"<c(FFFFFF)e(shadow)>Коза</c>"}
			{"hawk"										"<c(FFFFFF)e(shadow)>Ястреб</c>"}
			{"pig"										"<c(FFFFFF)e(shadow)>Свинья</c>"}
			{"raven"									"<c(FFFFFF)e(shadow)>Ворона"}
			{"seagull"									"<c(FFFFFF)e(shadow)>Чайка</c>"}
			{"shark"									"<c(FFFFFF)e(shadow)>Акула</c>"}
			{"sheep"									"<c(FFFFFF)e(shadow)>Овца</c>"}
			{"swan"										"<c(FFFFFF)e(shadow)>Лебедь</c>"}
		;vehicle
			;civilian
				;car
					{"car"								"<c(FFFFFF)e(shadow)>Civilian car</c>"}
					{"car_taxi"							"<c(FFFFFF)e(shadow)>Civilian taxi</c>"}
				;truck
					{"truck"							"<c(FFFFFF)e(shadow)>Civilian truck</c>"}
					{"truck_low_loader"					"<c(FFFFFF)e(shadow)>Civilian truck</c>"}
					{"truck_trailer"					"<c(FFFFFF)e(shadow)>Dump truck</c>"}
					{"truck_trailer_cementmixer"		"<c(FFFFFF)e(shadow)>Civilian truck</c>"}
					{"truck_trailer_closed"				"<c(FFFFFF)e(shadow)>Civilian truck</c>"}
				{"bus"									"<c(FFFFFF)e(shadow)>Civilian minibus</c>"}
				{"car_small"							"<c(FFFFFF)e(shadow)>Civilian car</c>"}
				{"train_cabin"							"<c(FFFFFF)e(shadow)>Passenger carriage</c>"}
				{"train_engine"							"<c(FFFFFF)e(shadow)>Civilian locomotive</c>"}
				{"train_fuelwagen"						"<c(FFFFFF)e(shadow)>Fuel tank</c>"}
				{"train_wagen"							"<c(FFFFFF)e(shadow)>Freight platform</c>"}
				{"train_wagen_2"						"<c(FFFFFF)e(shadow)>Freight platform</c>"}
				{"train_wagen_3"						"<c(FFFFFF)e(shadow)>Freight platform</c>"}
				{"train_wagen_container"				"<c(FFFFFF)e(shadow)>Cargo container</c>"}
				{"truck_small"							"<c(FFFFFF)e(shadow)>Civilian truck</c>"}
;unavailable
	;nato
		{"abn_hqcar"									"<c(FFFFFF)e(shadow)>Артиллерийская бригада</c>"}
		{"cbn_hqcar"									"<c(FFFFFF)e(shadow)>Сводный контингент экспедиционных сил</c>"}
		{"fra_hqcar"									"<c(FFFFFF)e(shadow)>Armee de terre</c>"}
		{"gb_hqcar"										"<c(FFFFFF)e(shadow)>Her Majesty's Armed Forces</c>"}
		{"mq9_nato"										"<c(FFFFFF)e(shadow)>MQ-9A Block 1</c>"}
		{"mq9_nato_recon"								"<c(FFFFFF)e(shadow)>MQ-9A Block 1 (recon)</c>"}
		{"nrf_hqcar"									"<c(FFFFFF)e(shadow)>Воздушное командование союзников НАТО</c>"}
		{"patriot_launcher_nato"						"<c(FFFFFF)e(shadow)>MIM-104 Patriot ПУ</c>"}
		{"patriot_radar_nato"							"<c(FFFFFF)e(shadow)>MIM-104 Patriot РЛС</c>"}
		{"uh60_nato"									"<c(FFFFFF)e(shadow)>UH-60 Black Hawk</c>"}
	;rus
		{"9k57_uragan"									"<c(FFFFFF)e(shadow)>9К57 Ураган</c>"}
		{"bmp1"											"<c(FFFFFF)e(shadow)>БМП-1<</c>"}
		{"bmp2"											"<c(FFFFFF)e(shadow)>БМП-2<</c>"}
		{"bmp2m"										"<c(FFFFFF)e(shadow)>БМП-2М Бережок</c>"}
		{"mtlb_no_ammobox"								"<c(FFFFFF)e(shadow)>МТ-ЛБ </c>"}
		{"t62"											"<c(FFFFFF)e(shadow)>Т-62 обр. 1972</c>"}
	;usa
		{"Humvee"										"<c(FFFFFF)e(shadow)>HUMVEE</c>"}
		{"M1A1"											"<c(FFFFFF)e(shadow)>M1A1HA</c>"}
		{"cougar"										"<c(FFFFFF)e(shadow)>Cougar 4x4</c>"}
		{"m1a1_shield_new"								"<c(FFFFFF)e(shadow)>M1A1HA</c>"}
		{"m1a2_all_model"								"<c(FFFFFF)e(shadow)>M1A2B</c>"}
		{"m1a2tusk_new"									"<c(FFFFFF)e(shadow)>M1A2A TUSK</c>"}
		{"m1ip"											"<c(FFFFFF)e(shadow)>M1IP</c>"}
		{"m2a3_btr"										"<c(FFFFFF)e(shadow)>M2A3 Bradley</c>"}
		{"m2a3_new"										"<c(FFFFFF)e(shadow)>M2A3 Bradley</c>"}
		{"mortarfru"									"<c(FFFFFF)e(shadow)>MO-120-RT61</c>"}
		{"ngrd_mp_flag"									"<c(FFFFFF)e(shadow)>Национальная гвардия США</c>"}	