;------------------ SFX by Terminator ------------

;------------------ GERMAN -----------------------
{"steyr_rso tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/pz2"	        }
		{link_sound "engine"			        "vehicle/engine/pz1"		}
		{link_sound "engine_end"		        "vehicle/engine/pz2_end"	}
		{link_sound "exhaust"			        "vehicle/engine/pz2_up" 	}
	}
	("burn_by_engine" args 0.3)
}
{"sdkfz303 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			        "vehicle/engine/dodge_move_new"	}
		{link_sound "engine"			        "vehicle/wheels/valami"	        }
		{link_sound "engine_end"		        "vehicle/engine/pz1_end"        }
		{link_sound "exhaust"			         "vehicle/engine/Dodge_end"     }
	}
	("burn_by_engine" args 0.3)
}
{"pz1 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/pz1"	        }
		{link_sound "engine"			        "vehicle/engine/pz1"	        }
		{link_sound "engine_end"		        "vehicle/engine/pz1_end"        }
		{link_sound "rotate_turret" 	                "vehicle/turret/light1"	        }
		{link_sound "exhaust"			        "vehicle/engine/pz1_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"pz1b tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/pz1"	        }
		{link_sound "engine"			        "vehicle/engine/pz1"	        }
		{link_sound "engine_end"		        "vehicle/engine/pz1_end"        }
		{link_sound "rotate_turret" 	                "vehicle/turret/light1"	        }
		{link_sound "exhaust"			        "vehicle/engine/pz1_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"marder_3h tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track7"  }
		{link_sound "engine"				"vehicle/engine/pz2"            }
		{link_sound "engine_end"			"vehicle/engine/pz2_end"        }
		{link_sound "exhaust"		  		"vehicle/engine/pz2_up"	        }
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"hetzer tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track5"  }
		{link_sound "engine"				"vehicle/engine/hetzer_engine"  }
		{link_sound "engine_end"			"vehicle/engine/sdkfz251_end"   }
		{link_sound "exhaust"		  		"vehicle/engine/hetzer_up2"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"sdkfz234 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/wheels"         }
		{link_sound "engine"				"vehicle/engine/sdkfz251"       }
		{link_sound "engine_end"			"vehicle/engine/sdkfz251_end"   }
		{link_sound "exhaust"		  		"vehicle/engine/sdkfz251_up"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"pz3 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/pz3"            }
		{link_sound "engine"				"vehicle/engine/pz3"            }
		{link_sound "engine_end"			"vehicle/engine/pz3_stop2"      }
		{link_sound "exhaust"		  		"vehicle/engine/pz3_up2"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"pz3m tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/pz3"            }
		{link_sound "engine"				"vehicle/engine/pz3"            }
		{link_sound "engine_end"			"vehicle/engine/pz3_stop2"      }
		{link_sound "exhaust"		  		"vehicle/engine/pz3_up2"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"wespe tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/pz3"	        }
		{link_sound "engine"			        "vehicle/engine/hetzer"		}
		{link_sound "engine_end"		        "vehicle/engine/pz2_end"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/heavy1"	        }
		{link_sound "exhaust"			        "vehicle/engine/pz2_up"	  	}
	}
	("burn_by_engine" args 0.3)
}
{"stug3g tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/pz3"            }
		{link_sound "engine"				"vehicle/engine/pz3"            }
		{link_sound "engine_end"			"vehicle/engine/pz3_stop2"      }
		{link_sound "exhaust"		  		"vehicle/engine/pz3_up2"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"stuh42 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/pz3"            }
		{link_sound "engine"				"vehicle/engine/pz3"            }
		{link_sound "engine_end"			"vehicle/engine/pz3_stop2"      }
		{link_sound "exhaust"		  		"vehicle/engine/pz3_up2"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"elefant tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/jugdpanther"    }
		{link_sound "engine"				"vehicle/engine/pz6"            }
		{link_sound "engine_end"			"vehicle/engine/pz6_end"        }
		{link_sound "exhaust"		  		"vehicle/engine/pz6_up"	        }
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"jagdtiger tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"     }
		{link_sound "engine"				"vehicle/engine/pz6-old"        }
		{link_sound "engine_end"			"vehicle/engine/pz6_end-old"    }
		{link_sound "exhaust"		  		"vehicle/engine/pz6_up-old"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"pz6bh tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"     }
		{link_sound "engine"				"vehicle/engine/pz6-old"        }
		{link_sound "engine_end"			"vehicle/engine/pz6_end-old"    }
		{link_sound "exhaust"		  		"vehicle/engine/pz6_up-old"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/pz6"	        }
	}
	("burn_by_engine" args 0.3)
}
{"pz5g tank"
	{on "add_movement_sound" overload
		{link_sound "move"			         "vehicle/tracks/jugdpanther"	 }
		{link_sound "engine"			         "vehicle/engine/pz5_engine"	 }
		{link_sound "engine_end"		         "vehicle/engine/jugdpanther_end"}
		{link_sound "rotate_turret" 		         "vehicle/turret/heavy"	         }
		{link_sound "exhaust"			         "vehicle/engine/jugdpanther_up" }
	}
	("burn_by_engine" args 0.3)
}
;------------------ USA --------------------------
{"m10wolverine tank"
	{on "add_movement_sound" overload 
		{link_sound "move"				 "vehicle/tracks/mk2"	        }
		{link_sound "engine"			         "vehicle/engine/m10wolverine"	}
		{link_sound "engine_end"		         "vehicle/engine/m4_end"	}
		{link_sound "rotate_turret" 	                 "vehicle/turret/sherman"	}
		{link_sound "exhaust"			         "vehicle/engine/m4a2_up"	}
	}
	("burn_by_engine" args 0.3)
}
{"m18 tank"
	{on "add_movement_sound" overload 
		{link_sound "move"				 "vehicle/tracks/mk2"	        }
		{link_sound "engine"			         "vehicle/engine/m18hellcat"	}
		{link_sound "engine_end"		         "vehicle/engine/m4_end"	}
		{link_sound "rotate_turret" 	                 "vehicle/turret/sherman"	}
		{link_sound "exhaust"			         "vehicle/engine/m4a2_up"	}
	}
	("burn_by_engine" args 0.3)
}
{"m20 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m8grayhound"    }
		{link_sound "engine"				"vehicle/engine/m8grayhound"    }
		{link_sound "engine_end"			"vehicle/engine/m8grayhound_end"}
		{link_sound "exhaust"		  		"vehicle/engine/m8grayhound_up"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"m24 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m3stuart"	}
		{link_sound "engine"			        "vehicle/engine/chaffee_engine"	}
		{link_sound "engine_end"		        "vehicle/engine/m4_end"	        }
		{link_sound "rotate_turret" 	                "vehicle/turret/sherman"	}
		{link_sound "exhaust"			        "vehicle/engine/m4a2_up"	}
	}
	("burn_by_engine" args 0.3)
}
{"m4a3e2_jumbo tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m3a1"           }
		{link_sound "engine"				"vehicle/engine/sherman_engine3"}
		{link_sound "engine_end"			"vehicle/engine/sherman_end2"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"m4a3e2_jumbo_76 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m3a1"           }
		{link_sound "engine"				"vehicle/engine/sherman_engine3"}
		{link_sound "engine_end"			"vehicle/engine/sherman_end2"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/sherman"	}
	}
	("burn_by_engine" args 0.3)
}
{"m4a2_76w tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m4a2"           }
		{link_sound "engine"				"vehicle/engine/sherman_engine" }
		{link_sound "engine_end"			"vehicle/engine/sherman_end"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/sherman"	}
	}
	("burn_by_engine" args 0.3)
}
{"m26_pershing tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/mk7"            }
		{link_sound "engine"				"vehicle/engine/sherman_engine3"}
		{link_sound "engine_end"			"vehicle/engine/sherman_end2"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up2"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/is"	        }
	}
	("burn_by_engine" args 0.3)
}
{"m26e4 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/mk2"            }
		{link_sound "engine"				"vehicle/engine/sherman_engine3"}
		{link_sound "engine_end"			"vehicle/engine/sherman_end2"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up2"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/is"	        }
	}
	("burn_by_engine" args 0.3)
}
{"m4a4_firefly tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/mk2"            }
		{link_sound "engine"				"vehicle/engine/sherman_engine3"}
		{link_sound "engine_end"			"vehicle/engine/sherman_end"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"m4a3_105 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m4a2"           }
		{link_sound "engine"				"vehicle/engine/sherman_engine" }
		{link_sound "engine_end"			"vehicle/engine/sherman_end"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"m36 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m3a1"           }
		{link_sound "engine"				"vehicle/engine/sherman_engine" }
		{link_sound "engine_end"			"vehicle/engine/sherman_end"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up2"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"m8 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			        "vehicle/tracks/m3stuart_move"	}
		{link_sound "engine"			        "vehicle/engine/v-2"		}
		{link_sound "engine_end"		        "vehicle/engine/v-2_end"        }
                {link_sound "exhaust"		  	        "vehicle/engine/v-2_up"	        }
		{link_sound "rotate_turret" 	                "vehicle/turret/light"	        }
	}
	("burn_by_engine" args 0.3)
}
{"m3stuart tank"
	{on "add_movement_sound" overload
		{link_sound "move"			        "vehicle/tracks/m3stuart"	}
		{link_sound "engine"		                "vehicle/engine/v-2"	        }
		{link_sound "engine_end"		        "vehicle/engine/v-2_end"        }
                {link_sound "exhaust"		  	        "vehicle/engine/v-2_up"         }
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_turret"  }
	}
	("burn_by_engine" args 0.3)
}
{"m7 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m3stuart_move"  }
		{link_sound "engine"				"vehicle/engine/radial_high"    }
		{link_sound "engine_end"			"vehicle/engine/radial_stop"	}
		{link_sound "exhaust"		  		"vehicle/engine/radial_start"	}
	}
	("burn_by_engine" args 0.3)
}
{"m5a1 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/m3stuart"	}
		{link_sound "engine"			        "vehicle/engine/m3stuart"	}
		{link_sound "engine_end"	 	        "vehicle/engine/tankengine_end"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/light"	        }
		{link_sound "exhaust"			        "vehicle/engine/tankengine_up"	}
	}
	("burn_by_engine" args 0.3)
}
;------------------ BRITISH ----------------------
{"mk2daimler"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/wheels"		}
		{link_sound "engine"			        "vehicle/engine/sdkfz234"	}
		{link_sound "engine_end"		        "vehicle/engine/sdkfz234_end"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/light1"		}
		{link_sound "exhaust"			        "vehicle/engine/sdkfz234_up"    }
		{link_sound "idle"			        "vehicle/engine/sdkfz222_idle"  }
	}
	("burn_by_engine" args 0.3)
}
{"mk2 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/light_track1"   }
		{link_sound "engine"				"vehicle/engine/eng_engine4"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"     }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up1"	}
	}
	("burn_by_engine" args 0.3)
}
{"mk2a tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track7"  }
		{link_sound "engine"				"vehicle/engine/eng_engine4"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"     }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up1"	}
	}
	("burn_by_engine" args 0.3)
}
{"universal_carrier tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/light_track0"   }
		{link_sound "engine"				"vehicle/engine/eng_engine1"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/small1"         }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"bishop tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track1"  }
		{link_sound "engine"				"vehicle/engine/eng_engine3"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end3"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/small1"         }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up3"	}
	}
	("burn_by_engine" args 0.3)
}
{"mk3 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track4"  }
		{link_sound "engine"				"vehicle/engine/eng_engine2"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end3"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"     }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up2"	}
	}
	("burn_by_engine" args 0.3)
}
{"mk6 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track5"  }
		{link_sound "engine"				"vehicle/engine/eng_engine2"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end3"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"     }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up4"	}
	}
	("burn_by_engine" args 0.3)
}
{"mk7 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/light_track0"   }
		{link_sound "engine"				"vehicle/engine/eng_engine1"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/small1"         }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up3"	}
	}
	("burn_by_engine" args 0.3)
}
{"crusaderaa1 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track0"  }
		{link_sound "engine"				"vehicle/engine/eng_engine1"    }
		{link_sound "engine_end"			"vehicle/engine/eng_id3"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"     }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up3"	}
	}
	("burn_by_engine" args 0.3)
}
{"crusaderaa2 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track0"  }
		{link_sound "engine"				"vehicle/engine/eng_engine1"    }
		{link_sound "engine_end"			"vehicle/engine/eng_id3"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"     }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up3"	}
	}
	("burn_by_engine" args 0.3)
}
{"cromwell_mk_vi tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track7"  }
		{link_sound "engine"				"vehicle/engine/eng_engine3"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end3"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/smedium1"       }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up3"	}
	}
	("burn_by_engine" args 0.3)
}
{"cromwell_mk_vii tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track7"  }
		{link_sound "engine"				"vehicle/engine/eng_engine3"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end3"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/mk7_turret"     }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up3"	}
	}
	("burn_by_engine" args 0.3)
}
{"cometa34 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track1"  }
		{link_sound "engine"				"vehicle/engine/eng_engine6"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end5"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/mk7_turret"     }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up5"	}
	}
	("burn_by_engine" args 0.3)
}
{"m4a4 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/mk2"            }
		{link_sound "engine"				"vehicle/engine/sherman_engine3"}
		{link_sound "engine_end"			"vehicle/engine/sherman_end"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"m4 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/mk2"            }
		{link_sound "engine"				"vehicle/engine/sherman_engine3"}
		{link_sound "engine_end"			"vehicle/engine/sherman_end"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
{"centurion tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track1"  }
		{link_sound "engine"				"vehicle/engine/eng_engine5"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end5"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/mk7_turret"     }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up5"	}
	}
	("burn_by_engine" args 0.3)
}
{"churchill_avre tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"     }
		{link_sound "engine"				"vehicle/engine/churchill"      }
		{link_sound "engine_end"			"vehicle/engine/eng_end5"	}
                {link_sound "rotate_turret" 	              "vehicle/turret/Churchill _turret"}
		{link_sound "exhaust"		  		"vehicle/engine/eng_up6"	}
	}
	("burn_by_engine" args 0.3)
}
{"churchill_mk_vii tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"     }
		{link_sound "engine"				"vehicle/engine/churchill"      }
		{link_sound "engine_end"			"vehicle/engine/eng_end5"	}
                {link_sound "rotate_turret" 	              "vehicle/turret/Churchill _turret"}
		{link_sound "exhaust"		  		"vehicle/engine/eng_up6"	}
	}
	("burn_by_engine" args 0.3)
}
{"churchill_mk_vii tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"     }
		{link_sound "engine"				"vehicle/engine/churchill"      }
		{link_sound "engine_end"			"vehicle/engine/eng_end5"	}
                {link_sound "rotate_turret" 	              "vehicle/turret/Churchill _turret"}
		{link_sound "exhaust"		  		"vehicle/engine/eng_up6"	}
	}
	("burn_by_engine" args 0.3)
}
{"black_prince tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"     }
		{link_sound "engine"				"vehicle/engine/churchill"      }
		{link_sound "engine_end"			"vehicle/engine/eng_end5"	}
                {link_sound "rotate_turret" 	              "vehicle/turret/Churchill _turret"}
		{link_sound "exhaust"		  		"vehicle/engine/eng_up6"	}
	}
	("burn_by_engine" args 0.3)
}
{"churchill_crocodile tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"     }
		{link_sound "engine"				"vehicle/engine/churchill"      }
		{link_sound "engine_end"			"vehicle/engine/eng_end5"	}
                {link_sound "rotate_turret" 	              "vehicle/turret/Churchill _turret"}
		{link_sound "exhaust"		  		"vehicle/engine/eng_up6"	}
	}
	("burn_by_engine" args 0.3)
}
{"mk4 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"     }
		{link_sound "engine"				"vehicle/engine/churchill"      }
		{link_sound "engine_end"			"vehicle/engine/eng_end5"	}
                {link_sound "rotate_turret" 	              "vehicle/turret/Churchill _turret"}
		{link_sound "exhaust"		  		"vehicle/engine/eng_up6"	}
	}
	("burn_by_engine" args 0.3)
}
{"archer tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/light_track4"   }
		{link_sound "engine"				"vehicle/engine/eng_engine3"    }
		{link_sound "engine_end"			"vehicle/engine/eng_end3"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/small1"         }
		{link_sound "exhaust"		  		"vehicle/engine/eng_up3"	}
	}
	("burn_by_engine" args 0.3)
}
{"achilles tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/light_track4"   }
		{link_sound "engine"				"vehicle/engine/sherman_engine3"}
		{link_sound "engine_end"			"vehicle/engine/sherman_end"	}
		{link_sound "exhaust"		  		"vehicle/engine/sherman_up"	}
		{link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"	}
	}
	("burn_by_engine" args 0.3)
}
;------------------ RUS --------------------------
{"bt7a tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/bt"		}
		{link_sound "engine"			        "vehicle/engine/V-2"		}
		{link_sound "engine_end"		        "vehicle/engine/V-2_end"	}
		{link_sound "exhaust"			        "vehicle/engine/V-2_up"	        }
		{link_sound "rotate_turret" 	                "vehicle/turret/light"	        }
	}
	("burn_by_engine" args 0.3)
}
{"t70 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/t-70"           }
		{link_sound "rotate_turret" 	                "vehicle/turret/light"		}
		{link_sound "engine"			        "vehicle/engine/gaz"		}
		{link_sound "engine_end"		        "vehicle/engine/gaz_end"	}
		{link_sound "exhaust"			        "vehicle/engine/gaz_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"su76 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track5"  }
		{link_sound "engine"			        "vehicle/engine/t26"		}
		{link_sound "engine_end"		        "vehicle/engine/bt_end"	        }
		{link_sound "exhaust"			        "vehicle/engine/bt_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"t26 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/bt"		}
		{link_sound "rotate_turret" 	                "vehicle/turret/light"		}
		{link_sound "engine"			        "vehicle/engine/t26"		}
		{link_sound "engine_end"		        "vehicle/engine/t26_end"	}
		{link_sound "exhaust"			        "vehicle/engine/t26_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"ba11 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/wheels"         }
		{link_sound "engine"				"vehicle/engine/ba11"           }
		{link_sound "engine_end"			"vehicle/engine/ba11_end"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/small1"         }
		{link_sound "exhaust"		  		"vehicle/engine/ba11_up"	}
	}
	("burn_by_engine" args 0.3)
}
{"ba64 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/wheels"         }
		{link_sound "engine"				"vehicle/engine/ba11"           }
		{link_sound "engine_end"			"vehicle/engine/ba11_end"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/small1"         }
		{link_sound "exhaust"		  		"vehicle/engine/ba11_up"	}
	}
	("burn_by_engine" args 0.3)
}
{"ba20 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/wheels"         }
		{link_sound "engine"				"vehicle/engine/ba20"           }
		{link_sound "engine_end"			"vehicle/engine/ba20_end"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/small1"         }
		{link_sound "exhaust"		  		"vehicle/engine/ba20_up"	}
	}
	("burn_by_engine" args 0.3)
}
{"kv1 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/kv"             }
		{link_sound "engine"				"vehicle/engine/kv"             }
		{link_sound "engine_end"			"vehicle/engine/kv_end"	        }
                {link_sound "rotate_turret" 	                "vehicle/turret/turret2"        }
		{link_sound "exhaust"		  		"vehicle/engine/kv_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"kv2 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/kv"             }
		{link_sound "engine"				"vehicle/engine/kv"             }
		{link_sound "engine_end"			"vehicle/engine/kv_end"	        }
                {link_sound "rotate_turret" 	                "vehicle/turret/turret2"        }
		{link_sound "exhaust"		  		"vehicle/engine/kv_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"kv85 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/kv"             }
		{link_sound "engine"				"vehicle/engine/kv"             }
		{link_sound "engine_end"			"vehicle/engine/kv_end"	        }
                {link_sound "rotate_turret" 	                "vehicle/turret/turret2"        }
		{link_sound "exhaust"		  		"vehicle/engine/kv_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"is1 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/is"             }
		{link_sound "engine"				"vehicle/engine/is2_engine"     }
		{link_sound "engine_end"			"vehicle/engine/is2_stop"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/turret11"       }
		{link_sound "exhaust"		  		"vehicle/engine/is2_start"	}
	}
	("burn_by_engine" args 0.3)
}
{"is2 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/is"             }
		{link_sound "engine"				"vehicle/engine/is2_engine"     }
		{link_sound "engine_end"			"vehicle/engine/is2_stop"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/turret11"       }
		{link_sound "exhaust"		  		"vehicle/engine/is2_start"	}
	}
	("burn_by_engine" args 0.3)
}
{"is3 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/is"             }
		{link_sound "engine"				"vehicle/engine/is2_engine"     }
		{link_sound "engine_end"			"vehicle/engine/is2_stop"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/turret11"       }
		{link_sound "exhaust"		  		"vehicle/engine/is2_start"	}
	}
	("burn_by_engine" args 0.3)
}
{"t34_0 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/t34b"           }
		{link_sound "engine"				"vehicle/engine/t34_old"        }
		{link_sound "engine_end"			"vehicle/engine/t34_end_old"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/turret4"        }
		{link_sound "exhaust"		  		"vehicle/engine/t34_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"t34_1 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/t34b"           }
		{link_sound "engine"				"vehicle/engine/t34_old"        }
		{link_sound "engine_end"			"vehicle/engine/t34_end_old"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/turret4"        }
		{link_sound "exhaust"		  		"vehicle/engine/t34_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"t34_2 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/t34b"           }
		{link_sound "engine"				"vehicle/engine/t34_old"        }
		{link_sound "engine_end"			"vehicle/engine/t34_end_old"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/turret4"        }
		{link_sound "exhaust"		  		"vehicle/engine/t34_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"su85 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track6"     }
		{link_sound "engine"				"vehicle/engine/t34b"           }
		{link_sound "engine_end"			"vehicle/engine/t34_end2"	}
		{link_sound "exhaust"		  		"vehicle/engine/t34_up2"	}
	}
	("burn_by_engine" args 0.3)
}
{"su122 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track6"     }
		{link_sound "engine"				"vehicle/engine/t34b"           }
		{link_sound "engine_end"			"vehicle/engine/t34_end2"	}
		{link_sound "exhaust"		  		"vehicle/engine/t34_up2"	}
	}
	("burn_by_engine" args 0.3)
}
{"su100 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track6"     }
		{link_sound "engine"				"vehicle/engine/t34b"           }
		{link_sound "engine_end"			"vehicle/engine/t34_end2"	}
		{link_sound "exhaust"		  		"vehicle/engine/t34_up2"	}
	}
	("burn_by_engine" args 0.3)
}
{"t34_3 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/t34b"           }
		{link_sound "engine"				"vehicle/engine/t34_old"        }
		{link_sound "engine_end"			"vehicle/engine/t34_end_old"	}
                {link_sound "rotate_turret" 	                "vehicle/turret/turret4"        }
		{link_sound "exhaust"		  		"vehicle/engine/t34_up"	        }
	}
	("burn_by_engine" args 0.3)
}
{"isu152 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			        "vehicle/tracks/is"		}
		{link_sound "rotate_turret" 		        "vehicle/turret/heavy1"		}
		{link_sound "engine"			        "vehicle/engine/is2_engine"	}
		{link_sound "engine_end"		        "vehicle/engine/is2_stop"	}
		{link_sound "exhaust"			        "vehicle/engine/is2_start"	}
	}
	("burn_by_engine" args 0.3)
}
{"isu122 tank"
	{on "add_movement_sound" overload
		{link_sound "move"			         "vehicle/tracks/is"		}
		{link_sound "rotate_turret" 		         "vehicle/turret/heavy1"	}
		{link_sound "engine"			         "vehicle/engine/is2_engine"	}
		{link_sound "engine_end"		         "vehicle/engine/is2_stop"	}
		{link_sound "exhaust"			         "vehicle/engine/is2_start"	}
	}
	("burn_by_engine" args 0.3)
}
;------------------ JAPON ------------------------

{"ho-ha3mgun tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track5"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine1"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/light1"             }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}
{"chi-ri tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/chi-ha"             }
		{link_sound "engine"				"vehicle/engine/Japan_engine3"      }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_endbig"}
                {link_sound "rotate_turret" 	                "vehicle/turret/turret2"            }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_upbig" }
	}
	("burn_by_engine" args 0.3)
}
{"chi-ha120 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track0"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine2"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/light"              }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}
{"chi-ha47 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track0"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine2"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/light"              }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}
{"chi-ha57 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track0"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine2"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/light"              }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}
{"ha-go tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track7"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine1"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/light1"             }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}
{"ke-nu tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track5"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine1"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/light1"             }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}
{"chi-he tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"         }
		{link_sound "engine"				"vehicle/engine/Jap_engine5"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/manual_turret"      }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_upbig" }
	}
	("burn_by_engine" args 0.3)
}
{"chi-nu tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track5"         }
		{link_sound "engine"				"vehicle/engine/Jap_engine4"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_endbig"}
                {link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"         }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_upbig" }
	}
	("burn_by_engine" args 0.3)
}
{"chi-to tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track6"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine7big"     }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_endbig"}
                {link_sound "rotate_turret" 	                "vehicle/turret/manual_gun"         }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_upbig" }
	}
	("burn_by_engine" args 0.3)
}
{"ho-i tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"         }
		{link_sound "engine"				"vehicle/engine/Jap_engine7big"     }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_endbig"}
                {link_sound "rotate_turret" 	                "vehicle/turret/turret4"            }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_upbig" }
	}
	("burn_by_engine" args 0.3)
}
{"ho-ri tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"         }
		{link_sound "engine"				"vehicle/engine/Jap_engine3"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/light"              }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up   " }
	}
	("burn_by_engine" args 0.3)
}
{"ho-ri_1 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"         }
		{link_sound "engine"				"vehicle/engine/Jap_engine6big"     }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/turret4"            }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_upbig" }
	}
	("burn_by_engine" args 0.3)
}
{"ho-ni1 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track5"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine4"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/turret4"            }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}
{"ho-ni2 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track5"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine4"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/turret4"            }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}
{"ho-ni_3 tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track5"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine2"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/turret4"            }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}
{"ha-to tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track0"         }
		{link_sound "engine"				"vehicle/engine/Jap_engine6big"     }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/turret4"            }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_upbig" }
	}
	("burn_by_engine" args 0.3)
}
{"ho-ro tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/medium_track7"      }
		{link_sound "engine"				"vehicle/engine/Jap_engine1"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/light1"             }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}
{"ss-d tank"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/tracks/big_track5"         }
		{link_sound "engine"				"vehicle/engine/Jap_engine2"        }
		{link_sound "engine_end"			"vehicle/engine/Japan_engine_end"   }
                {link_sound "rotate_turret" 	                "vehicle/turret/manual_turret"      }
		{link_sound "exhaust"		  		"vehicle/engine/Japan_engine_up"    }
	}
	("burn_by_engine" args 0.3)
}